// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define L4D2_API_WAIT_TEST_CLOCK
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include "api_wait_commands.h"
#include <cstdlib>
#include <thread>
#include <string>
namespace l4d2_api_wait { uint64_t testClock = 0; }
using namespace l4d2_api_wait;
static void require(bool value, const char* reason) {
  if (!value) { std::fprintf(stderr, "API wait test failed: %s\n", reason); std::exit(1); }
}
static void earlyReturn() {
  ApiScope api(Api::IndexLock);
  testClock += 25;
  Span resource(Metric::ResourceWait);
  testClock += 75;
  return;
}
int main() {
  require(!initialize(false, "client"), "disabled initialization remains inert");
  require(!state, "disabled API wait has no statistics table");
  { ApiScope api(Api::CreateTexture); Span wait(Metric::ResponseWait); queued(); }
  require(localStats == nullptr && queuedCommands.load() == 0 && top == nullptr, "disabled scopes do not claim storage or count commands");
  frequency = 1000000;
  state = new DiagnosticState();
  enabled.store(true);
  {
    ApiScope api(Api::CreateTexture);
    testClock = 1000;
    {
      Span submit(Metric::Submit);
      testClock = 1100;
      { Span mutex(Metric::CommandMutexWait); testClock = 1500; }
      testClock = 2000;
      { Span full(Metric::DataQueueWait); testClock = 4000; }
      testClock = 6000;
    }
    testClock = 6500;
    {
      Span response(Metric::ResponseWait);
      require(localStats->activeApi.load() == static_cast<unsigned>(Api::CreateTexture)
        && localStats->activeMetric.load() == static_cast<unsigned>(Metric::ResponseWait), "ongoing API and wait stage are observable before completion");
      testClock = 9000;
    }
    { ApiScope nested(Api::SurfaceLockRect); }
    testClock = 10000;
  }
  auto& rows = localStats->rows[static_cast<unsigned>(Api::CreateTexture)];
  require(rows[0].calls.load() == 1 && rows[0].ticks.load() == 10000, "complete API wall time recorded once");
  require(rows[static_cast<unsigned>(Metric::Submit)].ticks.load() == 2600
    && rows[static_cast<unsigned>(Metric::Submit)].inclusiveTicks.load() == 5000, "submit excludes nested waits from exclusive time");
  uint64_t partition = 0;
  for (unsigned i = 1; i < kMetrics; ++i) { partition += rows[i].ticks.load(); }
  require(partition == rows[0].ticks.load(), "exclusive attribution partitions wall time without double counting");
  require(localStats->rows[static_cast<unsigned>(Api::SurfaceLockRect)][0].calls.load() == 0, "nested wrapper helper is not counted as another API");
  require(rows[0].slow[0].load() == 1 && rows[0].slow[2].load() == 1 && rows[0].slow[3].load() == 0, "inclusive slow-call threshold buckets");
  require(top == nullptr && root == nullptr && localStats->inflight.load() == 0, "scope restoration after completion");
  require(localStats->activeApi.load() == kApis && localStats->activeMetric.load() == kMetrics,
    "completed calls do not leave false ongoing wait markers");
  earlyReturn();
  auto& returned = localStats->rows[static_cast<unsigned>(Api::IndexLock)];
  require(returned[0].ticks.load() == 100 && returned[static_cast<unsigned>(Metric::ResourceWait)].ticks.load() == 75,
    "early returns preserve API and wait accounting");
  {
    Span notFull(Metric::CommandQueueWait, Api::Other, false);
    testClock += 500;
  }
  auto& queue = localStats->rows[static_cast<unsigned>(Api::Other)][static_cast<unsigned>(Metric::CommandQueueWait)];
  require(queue.calls.load() == 0, "non-full queue does not count a wait or start timing");
  {
    Span full(Metric::CommandQueueWait, Api::Other, false);
    full.start(); testClock += 1000; full.finish(); full.finish();
  }
  require(queue.calls.load() == 1 && queue.ticks.load() == 1000, "actual full episode counts once even with explicit finish");
  // Reproduce the actual upload nesting, including wait inside retention.
  {
    ApiScope api(Api::SurfaceUnlockRect);
    { Span lock(Metric::DeviceMutex); testClock += 10; }
    {
      Span upload(Metric::UploadLocal); testClock += 20;
      {
        Span submit(Metric::Submit); testClock += 30;
        { Span serialize(Metric::Serialize); testClock += 40; }
        {
          Span reserve(Metric::BlobReserve); testClock += 50;
          { Span wait(Metric::DataQueueWait); testClock += 60; }
        }
        { Span copy(Metric::PayloadCopyHash); testClock += 70; }
        { Span commit(Metric::BlobCommit); testClock += 80; }
        { Span hashFinish(Metric::UploadLocal); testClock += 90; }
      }
    }
    { Span release(Metric::ShadowRelease); testClock += 100; }
    {
      Span retention(Metric::Retention); testClock += 110;
      { Span completion(Metric::ResourceWait); testClock += 120; }
    }
    testClock += 130;
  }
  auto& uploadRows = localStats->rows[static_cast<unsigned>(Api::SurfaceUnlockRect)];
  uint64_t uploadPartition = 0;
  for (unsigned i = 1; i < kMetrics; ++i) { uploadPartition += uploadRows[i].ticks.load(); }
  require(uploadRows[0].ticks.load() == 910 && uploadPartition == 910,
    "upload child phases partition the API wall time, including repeated metric nesting");
  require(uploadRows[static_cast<unsigned>(Metric::Submit)].ticks.load() == 30
    && uploadRows[static_cast<unsigned>(Metric::BlobReserve)].ticks.load() == 50
    && uploadRows[static_cast<unsigned>(Metric::Retention)].ticks.load() == 110,
    "serialization, copy and existing waits are excluded from their parent exclusive totals");
  require(uploadRows[static_cast<unsigned>(Metric::UploadLocal)].ticks.load() == 110
    && uploadRows[static_cast<unsigned>(Metric::PayloadCopy)].calls.load() == 0
    && uploadRows[static_cast<unsigned>(Metric::PayloadCopyHash)].ticks.load() == 70,
    "hashing copy is distinct from pure copy and upload-local counts exclusive setup/finish");
  require(commandApi(Commands::IDirect3DDevice9Ex_CreateTexture) == Api::CreateTexture
    && commandApi(Commands::IDirect3DSurface9_UnlockRect) == Api::SurfaceUnlockRect
    && commandApi(Commands::Bridge_TestReadbackRecovery) == Api::Readback, "resource wire command classification");
  require(backend([] { return 42; }) == 42, "backend wrapper preserves the return value");
  Stats concurrent;
  std::thread first([&] { for (int i = 0; i < 10000; ++i) { concurrent.add(10, 5); } });
  std::thread second([&] { for (int i = 0; i < 10000; ++i) { concurrent.add(20, 10); } });
  first.join(); second.join();
  require(concurrent.calls.load() == 20000 && concurrent.ticks.load() == 150000 && concurrent.maxTicks.load() == 20,
    "concurrent aggregate updates do not lose counts or maximum duration");
  std::thread attributed([] { require(threadStats() != nullptr && localStats->id.load() == GetCurrentThreadId(), "per-thread attribution"); });
  attributed.join();
  Writer writer; writer.role = "test"; writer.startTick = GetTickCount64();
  writer.file = CreateFileW(L"api-wait-test.log", GENERIC_WRITE | GENERIC_READ, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
  require(writer.file != INVALID_HANDLE_VALUE, "create test snapshot output");
  writer.snapshot();
  SetFilePointer(writer.file, 0, nullptr, FILE_BEGIN);
  char output[24000] {}; DWORD length = 0;
  require(ReadFile(writer.file, output, sizeof(output) - 1, &length, nullptr) != FALSE, "read diagnostic snapshot");
  const std::string text(output, length);
  require(text.find("schema=2") != std::string::npos
    && text.find("metric=payload_copy_hash") != std::string::npos
    && text.find("queue_delay=unknown gpu_time=unknown") != std::string::npos
    && text.find("metric=server_response_wait") != std::string::npos
    && text.find("L4D2_API_WAIT_END snapshot=1") != std::string::npos, "complete snapshot with explicit limits and phase data");
  CloseHandle(writer.file); DeleteFileW(L"api-wait-test.log");
  // Synthetic scopes above enabled counters directly, without creating a
  // worker. Restore the startup state before testing real initialization.
  enabled.store(false);
  localStats = nullptr; delete state; state = nullptr;
  require(initialize(true, "client", 1000), "native diagnostic worker initialization");
  wchar_t realLog[100] {};
  swprintf_s(realLog, 100, L"l4d2-api-wait-client-%lu.log", GetCurrentProcessId());
  bool complete = false;
  const auto deadline = GetTickCount64() + 4000;
  while (!complete && GetTickCount64() < deadline) {
    HANDLE log = CreateFileW(realLog, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE, nullptr, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (log != INVALID_HANDLE_VALUE) {
      char data[24000] {}; DWORD bytes = 0;
      if (ReadFile(log, data, sizeof(data) - 1, &bytes, nullptr)) {
        complete = std::string(data, bytes).find("L4D2_API_WAIT_END snapshot=1") != std::string::npos;
      }
      CloseHandle(log);
    }
    if (!complete) { Sleep(10); }
  }
  require(complete, "private worker writes a complete snapshot independently of Present or API completion");
  std::puts("API wait diagnostics: disabled path, nested partition, returns, backpressure, atomic aggregation and snapshots passed");
}
