// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#ifdef SEMANTIC
static unsigned passed = 0;
static void check(bool condition) { if (!condition) { std::abort(); } ++passed; }
static void semantics() {
  Transport t; activeTransport = &t;
  Buffer vb(11), vb2(12), ib(21), ib2(22);
  {
    Direct3DDevice9Ex_LSS<true, true> d;
    check(d.SetStreamSource(0, &vb, 4, 16) == S_OK && !d.lastMatch);
    const auto references = vb.objects();
    check(d.SetStreamSource(0, &vb, 4, 16) == S_OK && d.lastMatch);
    check(vb.objects() == references && vb.interfaces() == 1 && !vb.destroyed);
    check(t.packets.size() == 2); // B always submits, including matches.
    d.SetStreamSource(0, &vb, 8, 16); check(!d.lastMatch);
    d.SetStreamSource(0, &vb, 8, 20); check(!d.lastMatch);
    d.SetStreamSource(0, nullptr, 0, 0); check(!d.lastMatch);
    d.SetStreamSource(0, nullptr, 99, 99); check(d.lastMatch);
    d.SetIndices(&ib); check(!d.lastMatch);
    d.SetIndices(&ib); check(d.lastMatch && ib.objects() == 2);
    Recording block;
    d.m_stateRecording = &block;
    d.SetStreamSource(0, &vb, 4, 16); d.SetStreamSource(0, &vb, 4, 16);
    d.SetIndices(&ib); d.SetIndices(&ib);
    check(!d.lastMatch && block.m_dirtyFlags.streams[0] && block.m_dirtyFlags.streamOffsetsAndStrides[0] && block.m_dirtyFlags.indices);
    check(*d.m_state.streams[0] == nullptr && *block.m_captureState.streams[0] == &vb);
    check(ib.objects() == 3); // Live binding and recorded binding both own refs.
    d.m_stateRecording = nullptr;
    d.SetStreamSource(0, &vb, 4, 16); d.SetIndices(&ib);
    Host h; for (const auto& p : t.packets) { h.process(p); }
    float vertices[9]{}; UINT index[3]{};
    d.DrawPrimitiveUP(4, 1, vertices, 12); h.process(t.packets.back());
    check(h.streams[0] == 0 && *d.m_state.streams[0] == &vb);
    d.SetStreamSource(0, &vb, 4, 16);
    check(d.lastMatch && h.streams[0] != vb.id); // Unsafe equality counterexample.
    h.process(t.packets.back()); check(h.streams[0] == vb.id);
    d.DrawIndexedPrimitiveUP(4, 0, 3, 1, index, D3DFMT_INDEX16, vertices, 12); h.process(t.packets.back());
    d.SetIndices(&ib); check(d.lastMatch && h.indices != ib.id);
    h.process(t.packets.back()); check(h.indices == ib.id);
    t.backendFail = true; t.responses = true;
    check(d.SetIndices(&ib2) == D3DERR_INVALIDCALL);
    h.process(t.packets.back(), true);
    check(d.SetIndices(&ib2) == D3DERR_INVALIDCALL && d.lastMatch && h.indices != ib2.id);
    t.responses = false;
    check(d.SetStreamSource(1, &vb2, 0, 16) == S_OK);
    h.process(t.packets.back(), true);
    d.SetStreamSource(1, &vb2, 0, 16); check(d.lastMatch && h.streams[1] != vb2.id);
    t.backendFail = false; t.failPublication = true;
    const auto published = t.packets.size();
    d.SetIndices(nullptr); d.SetIndices(nullptr);
    check(d.lastMatch && t.packets.size() == published && h.indices == ib.id);
    t.failPublication = false;
    // Externally supplied deterministic scheduling point after the production
    // state lock is released, before its ClientMessage construction.
    t.packets.clear();
    afterUnlock = [&]() { d.SetIndices(&ib2); };
    d.SetIndices(&ib);
    check(t.packets.size() == 2 && t.packets[0].data[0] == ib2.id && t.packets[1].data[0] == ib.id);
    Host reordered; for (const auto& p : t.packets) { reordered.process(p); }
    d.SetIndices(&ib2); check(d.lastMatch && reordered.indices != ib2.id);
    // Real two-thread schedule with the state mutex enabled; no data race needed.
    std::atomic<unsigned> phase{0}; t.packets.clear();
    std::thread first([&]() {
      activeTransport = &t;
      afterUnlock = [&]() { phase.store(1); while (phase.load() != 2) { std::this_thread::yield(); } };
      d.SetStreamSource(2, &vb, 0, 16);
    });
    std::thread second([&]() {
      activeTransport = &t;
      while (phase.load() != 1) { std::this_thread::yield(); }
      d.SetStreamSource(2, &vb2, 0, 16); phase.store(2);
    });
    first.join(); second.join();
    Host concurrent; for (const auto& p : t.packets) { concurrent.process(p); }
    check(concurrent.streams[2] == vb.id && *d.m_state.streams[2] == &vb2);
    d.SetStreamSource(2, &vb2, 0, 16); check(d.lastMatch && concurrent.streams[2] != vb2.id);
    // Pointer identity and lifetime, including allocator address reuse.
    d.SetIndices(&ib); ib.Release();
    check(!ib.destroyed && ib.interfaces() == 0);
    d.SetIndices(nullptr); check(!ib.destroyed); // Block still owns the object.
    block.m_captureState.indices.reset(nullptr); check(ib.destroyed);
    alignas(Buffer) unsigned char storage[sizeof(Buffer)];
    auto* old = new (storage) Buffer(101); d.SetIndices(old); d.SetIndices(nullptr); old->Release(); old->~Buffer();
    auto* replacement = new (storage) Buffer(102); d.SetIndices(replacement);
    check(!d.lastMatch && t.packets.back().data[0] == 102);
    d.SetIndices(nullptr); replacement->Release(); replacement->~Buffer();
  }
  // Compare A/B traces and reference results with diagnostics OFF and ON.
  for (bool diagnostics : {false, true}) {
    Transport a, b; Buffer va(31), ia(32);
    Direct3DDevice9Ex_LSS<true, false> da;
    Direct3DDevice9Ex_LSS<true, true> db;
    da.m_dataKnown = std::make_unique<Flags>(); db.m_dataKnown = std::make_unique<Flags>();
    l4d2_data::enabled.store(diagnostics);
    for (unsigned n = 0; n < 1000; ++n) {
      activeTransport = &a; da.SetStreamSource(0, n % 7 ? &va : nullptr, n % 4, 16); da.SetIndices(n % 5 ? &ia : nullptr);
      activeTransport = &b; db.SetStreamSource(0, n % 7 ? &va : nullptr, n % 4, 16); db.SetIndices(n % 5 ? &ia : nullptr);
    }
    check(a.packets.size() == b.packets.size());
    bool equal = true;
    for (size_t n = 0; n < a.packets.size(); ++n) { equal &= a.packets[n].command == b.packets[n].command && a.packets[n].data == b.packets[n].data; }
    check(equal && va.interfaces() == 1 && ia.interfaces() == 1);
  }
  std::printf("{\"assertions\":%u,\"C_enabled\":false,\"unsafe_boundaries\":[\"DrawPrimitiveUP\",\"DrawIndexedPrimitiveUP\",\"backend_failure_sync\",\"backend_failure_async\",\"publication_failure\",\"reordered_indices\",\"two_thread_streams\"],\"reset_stateblock_apply\":\"source audit only; no C qualification\"}\n", passed);
}
int main() { semantics(); }
#else
template<bool Check> static void benchmark(bool stream, unsigned rate, size_t count) {
  // Inputs and transport storage are allocated before the batch timer.
  std::vector<unsigned> inputs(count);
  unsigned value = 0, accumulator = 0;
  uint64_t expectedMatches = 0;
  for (size_t n = 0; n < count; ++n) {
    accumulator += rate;
    bool same = accumulator >= 10000;
    if (same) { accumulator -= 10000; if (n) { ++expectedMatches; } }
    else { value ^= 1; }
    inputs[n] = value;
  }
  Transport t(count); activeTransport = &t;
  Buffer first(11), second(12);
  Direct3DDevice9Ex_LSS<true, Check> d;
  const auto cpuStart = std::clock();
  const auto start = std::chrono::steady_clock::now();
  for (auto value : inputs) {
    if (stream) { d.SetStreamSource(0, value ? &second : &first, 4, 16); }
    else { d.SetIndices(value ? &second : &first); }
  }
  const auto clientEnd = std::chrono::steady_clock::now();
  const auto cpuEnd = std::clock();
  Host host;
  for (const auto& p : t.packets) { host.process(p); }
  const auto hostEnd = std::chrono::steady_clock::now();
  assert(t.packets.size() == count);
  if constexpr (Check) { assert(d.matches == expectedMatches && d.checks == count); }
  const auto ns = [](auto duration) { return std::chrono::duration<double, std::nano>(duration).count(); };
  std::printf("{\"calls\":%zu,\"commands\":%zu,\"wire_bytes_theoretical\":%zu,\"matches\":%llu,\"client_ns_per_call\":%.4f,\"client_cpu_ns_per_call\":%.4f,\"host_adapter_ns_per_call\":%.4f,\"total_ns_per_call\":%.4f,\"host_final\":%u}\n", count, t.packets.size(), count * (stream ? 32 : 20), static_cast<unsigned long long>(Check ? d.matches : expectedMatches), ns(clientEnd - start) / count, 1e9 * (cpuEnd - cpuStart) / CLOCKS_PER_SEC / count, ns(hostEnd - clientEnd) / count, ns(hostEnd - start) / count, stream ? host.streams[0] : host.indices);
}
int main(int argc, char** argv) {
  if (argc != 5) { return 2; }
  const bool stream = std::string(argv[2]) == "stream";
  const auto rate = static_cast<unsigned>(std::stoul(argv[3]));
  const auto count = std::stoull(argv[4]);
  if (argv[1][0] == 'A') { benchmark<false>(stream, rate, count); }
  else { benchmark<true>(stream, rate, count); }
}
#endif
