// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
// Investigation-only adapters. They are not the Windows transport or GPU backend.
#include <array>
#include <atomic>
#include <cassert>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <utility>
#include <vector>
using UINT = uint32_t;
using ULONG = uint32_t;
using UID = uint32_t;
using HRESULT = int32_t;
using D3DPRIMITIVETYPE = uint32_t;
using D3DFORMAT = uint32_t;
constexpr HRESULT S_OK = 0, D3DERR_INVALIDCALL = -1;
constexpr D3DFORMAT D3DFMT_INDEX16 = 101;
#define ZoneScoped
#define LogFunctionCall()
#define CONST const
// INSERT_PRODUCTION_REFS
struct RefStorage { std::atomic<uint64_t> refs{0}; };
struct Buffer : RefStorage, D3DRefCounted {
  UINT id;
  bool destroyed = false;
  explicit Buffer(UINT value) : D3DRefCounted(refs, [this]() { destroyed = true; }), id(value) { incRef<Ref::Both>(); }
  UINT getId() const { return id; }
  ULONG AddRef() { return incRef<Ref::Both>(); }
  ULONG Release() { return decRef<Ref::Both>(); }
  ULONG objects() const { return getRef<Ref::Object>(); }
  ULONG interfaces() const { return getRef<Ref::Interface>(); }
};
using Direct3DVertexBuffer9_LSS = Buffer;
using Direct3DIndexBuffer9_LSS = Buffer;
using IDirect3DVertexBuffer9 = Buffer;
using IDirect3DIndexBuffer9 = Buffer;
template<typename T, typename U> T bridge_cast(U* pointer) { return static_cast<T>(pointer); }
namespace Commands {
enum D3D9Command : uint16_t { IDirect3DDevice9Ex_SetStreamSource, IDirect3DDevice9Ex_SetIndices, IDirect3DDevice9Ex_DrawPrimitiveUP, IDirect3DDevice9Ex_DrawIndexedPrimitiveUP };
}
struct State {
  std::array<D3DAutoPtr, 16> streams;
  std::array<UINT, 16> streamOffsets{}, streamStrides{};
  D3DAutoPtr indices;
};
struct Flags { std::array<bool, 16> streams{}, streamOffsetsAndStrides{}; bool indices = false; };
struct Recording { State m_captureState; Flags m_dirtyFlags; };
namespace l4d2_data {
inline std::atomic<bool> enabled{false};
inline void stateSet(uint16_t, bool, unsigned, bool, bool) {}
}
struct Packet { Commands::D3D9Command command; std::array<UINT, 16> data{}; UINT size = 0; };
struct Transport {
  std::mutex mutex;
  std::vector<Packet> packets;
  bool failPublication = false, backendFail = false, responses = false;
  UID uid = 1;
  explicit Transport(size_t capacity = 32) { packets.reserve(capacity); }
};
inline thread_local Transport* activeTransport = nullptr;
inline thread_local HRESULT lastResult = S_OK;
// IPC adapter deliberately retains the second, independent submission mutex.
struct ClientMessage {
  Transport& transport = *activeTransport;
  std::unique_lock<std::mutex> lock;
  Packet packet;
  ClientMessage(Commands::D3D9Command command, UID) : lock(transport.mutex), packet{command, {}, 0} {}
  UID get_uid() const { return transport.uid; }
  void send_data(UINT value) { assert(packet.size < packet.data.size()); packet.data[packet.size++] = value; }
  void send_data(UINT bytes, const void*) { send_data(bytes); }
  template<typename... T> void send_many(T... values) { (send_data(static_cast<UINT>(values)), ...); }
  ~ClientMessage() {
    if (!transport.failPublication) { transport.packets.push_back(packet); }
    ++transport.uid;
    lastResult = transport.responses && (transport.backendFail || transport.failPublication) ? D3DERR_INVALIDCALL : S_OK;
  }
};
#define WAIT_FOR_OPTIONAL_SERVER_RESPONSE(name, failure, uid) { (void)(uid); return lastResult; }
inline UINT GetIndexCount(D3DPRIMITIVETYPE, UINT primitives) { return primitives * 3; }
#ifdef SEMANTIC
inline thread_local std::function<void()> afterUnlock;
#endif
template<bool EnableSync, bool Check> struct Direct3DDevice9Ex_LSS {
  State m_state;
  Recording* m_stateRecording = nullptr;
  std::unique_ptr<Flags> m_dataKnown;
  std::recursive_mutex mutex;
  bool lastMatch = false;
  uint64_t checks = 0, matches = 0;
  UID getId() const { return 1; }
  HRESULT SetStreamSource(UINT, IDirect3DVertexBuffer9*, UINT, UINT);
  HRESULT SetIndices(IDirect3DIndexBuffer9*);
  HRESULT DrawPrimitiveUP(D3DPRIMITIVETYPE, UINT, const void*, UINT);
  HRESULT DrawIndexedPrimitiveUP(D3DPRIMITIVETYPE, UINT, UINT, UINT, const void*, D3DFORMAT, const void*, UINT);
};
template<typename Device> struct Guard {
  Device* device;
  explicit Guard(Device* value) : device(value) { device->mutex.lock(); }
  ~Guard() {
    device->mutex.unlock();
#ifdef SEMANTIC
    if (afterUnlock) { auto callback = std::move(afterUnlock); afterUnlock = {}; callback(); }
#endif
  }
};
#define BRIDGE_DEVICE_LOCKGUARD() Guard guard(this)
// Deterministic Host oracle for binding transitions only. No GPU timing claim.
struct Host {
  std::array<UINT, 16> streams{}, offsets{}, strides{};
  UINT indices = 0;
  void process(const Packet& p, bool fail = false) {
    if (fail) { return; }
    switch (p.command) {
      case Commands::IDirect3DDevice9Ex_SetStreamSource:
        streams[p.data[0]] = p.data[1];
        if (p.data[1]) { offsets[p.data[0]] = p.data[2]; strides[p.data[0]] = p.data[3]; }
        break;
      case Commands::IDirect3DDevice9Ex_SetIndices: indices = p.data[0]; break;
      case Commands::IDirect3DDevice9Ex_DrawPrimitiveUP: streams[0] = offsets[0] = strides[0] = 0; break;
      case Commands::IDirect3DDevice9Ex_DrawIndexedPrimitiveUP: streams[0] = offsets[0] = strides[0] = indices = 0; break;
    }
  }
};
