// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
// Deterministic adapters; the production LockableBuffer template is generated unchanged.

#include <d3d9.h>
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <memory>
#include <queue>
#include <sstream>
#include <string>
#include <type_traits>
#include <vector>
#include "data_diagnostics.h"
#include "util_commands.h"
struct BaseDirect3DDevice9Ex_LSS {};
template<typename T> struct Direct3DResource9_LSS {
  Direct3DResource9_LSS(T*, BaseDirect3DDevice9Ex_LSS*) {}
  uint32_t getId() const { return 1; }
};
struct GlobalOptions {
  static bool getUseSharedHeap() { return false; }
  static bool getUseSharedHeapForDynamicBuffers() { return false; }
  static bool getUseSharedHeapForStaticBuffers() { return false; }
  static bool getAlwaysCopyEntireStaticBuffer() { return false; }
};
struct ClientOptions { static bool getOptimizedDynamicLock() { return false; } };
namespace l4d2_memory {
enum class Kind { Vertex, Index };
inline uint64_t liveBytes = 0;
inline uint8_t* allocate(size_t size, Kind, unsigned, unsigned, unsigned, bool) {
  auto* result = new uint8_t[size](); liveBytes += size; return result;
}
inline void released(size_t size, Kind) { liveBytes -= size; }
}
namespace SharedHeap {
using AllocId = uint32_t;
constexpr AllocId kInvalidId = UINT32_MAX;
inline AllocId allocate(size_t) { return kInvalidId; }
inline void deallocate(AllocId) {}
inline uint8_t* getBuf(AllocId) { return nullptr; }
}
template<typename T> T align(T value, size_t alignment) { return (value + alignment - 1) & ~(alignment - 1); }
template<typename... T> std::string format_string(const char*, T...) { return {}; }
namespace bridge_util { enum class LogLevel { Trace }; }
struct Logger {
  static bool isEnabled(bridge_util::LogLevel) { return false; }
  template<typename Message> static void traceLazy(Message&&) {}
  static void trace(const std::string&) {} static void err(const std::string&) {}
};
struct Channel { uint32_t* get_data_ptr() const { return nullptr; } };
struct DeviceBridge { static Channel getWriterChannel() { return {}; } };
struct Update { Commands::D3D9Command command; uint32_t offset, size, flags; std::vector<uint8_t> bytes; };
static std::vector<Update> updates;
struct ClientMessage {
  Update update;
  ClientMessage(Commands::D3D9Command command, uint32_t, Commands::Flags = 0) : update { command, 0, 0, 0, {} } {}
  ~ClientMessage() { updates.push_back(std::move(update)); }
  template<typename A, typename B, typename C> void send_many(A offset, B size, C flags) {
    update.offset = static_cast<uint32_t>(offset); update.size = static_cast<uint32_t>(size); update.flags = static_cast<uint32_t>(flags);
  }
  template<typename T> void send_many(T) {}
  void send_data(uint32_t) {}
  void send_data(size_t size, const void* data) {
    const auto* first = static_cast<const uint8_t*>(data); update.bytes.assign(first, first + size);
  }
  uint8_t* begin_data_blob(size_t) { return nullptr; }
  void end_data_blob() {}
};
