// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

template<typename T> class Buffer : public LockableBuffer<T> {
  using Desc = std::conditional_t<std::is_same_v<T, IDirect3DVertexBuffer9>, D3DVERTEXBUFFER_DESC, D3DINDEXBUFFER_DESC>;
public:
  explicit Buffer(const Desc& desc) : LockableBuffer<T>(nullptr, nullptr, desc) {}
  using LockableBuffer<T>::lock;
  using LockableBuffer<T>::unlock;
};
static int failures = 0;
static void check(bool value, const char* message) { if (!value) { ++failures; std::cerr << message << '\n'; } }
template<typename T> void run(const char* name, D3DFORMAT format, D3DPOOL pool = D3DPOOL_DEFAULT) {
  using Desc = std::conditional_t<std::is_same_v<T, IDirect3DVertexBuffer9>, D3DVERTEXBUFFER_DESC, D3DINDEXBUFFER_DESC>;
  Desc desc {}; desc.Size = 64; desc.Usage = D3DUSAGE_WRITEONLY; desc.Pool = pool; desc.Format = format;
  updates.clear();
  Buffer<T> buffer(desc);
  void* data = nullptr;
  check(buffer.lock(0, 0, &data, 0) == S_OK, "initial full Lock failed");
  std::memset(data, 0x55, 64); buffer.unlock();
  check(updates.back().offset == 0 && updates.back().size == 64, "initial wire range differs");
  check(buffer.lock(0, 64, &data, 0) == S_OK, "second Lock failed");
  static_cast<uint8_t*>(data)[12] = 0xaa; buffer.unlock();
  const auto& current = updates.back();
  check(current.bytes[12] == 0xaa && current.bytes[11] == 0x55 && current.bytes[13] == 0x55, "actual full-shadow path lost untouched bytes inside Lock");
  std::vector<uint8_t> emptyStaging(64); emptyStaging[12] = 0xaa;
  check(emptyStaging != current.bytes, "counterexample did not distinguish empty staging from existing semantics");
  void* first = nullptr; void* second = nullptr;
  check(buffer.lock(8, 16, &first, 0) == S_OK && buffer.lock(12, 8, &second, 0) == S_OK, "actual multiple Lock behavior differs");
  check(static_cast<uint8_t*>(first) + 4 == second, "actual overlapping locks do not alias");
  static_cast<uint8_t*>(second)[0] = 0xbb; buffer.unlock();
  check(updates.back().offset == 8 && updates.back().bytes[4] == 0xbb, "FIFO Unlock lost overlapping write");
  buffer.unlock();
  check(buffer.lock(48, 0, &data, 0) == S_OK, "offset-to-end Lock failed");
  std::memset(data, 0xcc, 16); buffer.unlock();
  check(updates.back().offset == 48 && updates.back().size == 16, "size=0 did not mean offset-to-end");
  const auto count = updates.size();
  buffer.unlock();
  check(updates.size() == count, "benign Unlock-without-Lock sent an update");
  std::vector<uint8_t> host(64);
  for (const auto& update : updates) {
    check(update.command == (std::is_same_v<T, IDirect3DVertexBuffer9> ? Commands::IDirect3DVertexBuffer9_Unlock : Commands::IDirect3DIndexBuffer9_Unlock), "buffer upload command mapping differs");
    check(update.flags == 0 && update.bytes.size() == update.size, "normal wire flags/byte count differs");
    std::memcpy(host.data() + update.offset, update.bytes.data(), update.size);
  }
  check(host[0] == 0x55 && host[12] == 0xbb && host[47] == 0x55 && host[48] == 0xcc, "range uploads corrupted unrelated Host bytes");
  std::cout << name << ": existing partial-write preservation and overlapping Lock verified; fresh staging counterexample reproduced\n";
}
template<typename T> void runDynamic(D3DFORMAT format) {
  using Desc = std::conditional_t<std::is_same_v<T, IDirect3DVertexBuffer9>, D3DVERTEXBUFFER_DESC, D3DINDEXBUFFER_DESC>;
  Desc desc {}; desc.Size = 64; desc.Usage = D3DUSAGE_WRITEONLY | D3DUSAGE_DYNAMIC; desc.Pool = D3DPOOL_DEFAULT; desc.Format = format;
  const auto before = buffer_contract::liveBytes;
  updates.clear();
  {
    Buffer<T> buffer(desc);
    check(buffer_contract::liveBytes == before + 64, "dynamic buffer stopped allocating its existing full shadow");
    void* data = nullptr;
    check(buffer.lock(0, 64, &data, D3DLOCK_DISCARD) == S_OK, "dynamic DISCARD Lock changed");
    std::memset(data, 0x66, 64); buffer.unlock();
    check(updates.back().flags == D3DLOCK_DISCARD, "dynamic DISCARD flag changed on wire");
    check(buffer.lock(16, 8, &data, D3DLOCK_NOOVERWRITE) == S_OK, "dynamic NOOVERWRITE Lock changed");
    std::memset(data, 0x77, 8); buffer.unlock();
    check(updates.back().offset == 16 && updates.back().size == 8 && updates.back().flags == D3DLOCK_NOOVERWRITE, "dynamic partial protocol changed");
    check(buffer.lock(32, 8, &data, 0) == S_OK, "Lock before destruction failed");
  }
  check(buffer_contract::liveBytes == before, "destroy while locked retained shadow storage");
}
static void runReadable() {
  D3DVERTEXBUFFER_DESC desc {}; desc.Size = 64; desc.Format = D3DFMT_VERTEXDATA; desc.Pool = D3DPOOL_MANAGED;
  updates.clear();
  Buffer<IDirect3DVertexBuffer9> buffer(desc);
  void* data = nullptr;
  check(buffer.lock(0, 64, &data, 0) == S_OK, "readable initial Lock failed");
  std::memset(data, 0x88, 64); buffer.unlock();
  check(buffer.lock(8, 16, &data, D3DLOCK_READONLY) == S_OK, "readable Lock changed");
  check(static_cast<const uint8_t*>(data)[0] == 0x88, "non-WRITEONLY historical contents changed");
  const auto count = updates.size(); buffer.unlock();
  check(updates.size() == count, "READONLY Unlock started uploading");
}
static void failedUploadContract() {
  D3DVERTEXBUFFER_DESC desc {}; desc.Size = 64; desc.Usage = D3DUSAGE_DYNAMIC; desc.Format = D3DFMT_VERTEXDATA;
  const auto before = buffer_contract::liveBytes;
  updates.clear();
  {
    Buffer<IDirect3DVertexBuffer9> buffer(desc);
    void* data = nullptr;
    check(buffer.lock(0,64,&data,D3DLOCK_DISCARD) == S_OK,"failure setup lock");
    std::memset(data,0xa7,64);
    failSubmissionTest=true;
    check(buffer.unlock()==D3DERR_DEVICELOST,"failed upload must return failure");
    check(updates.empty(),"failed upload published update");
    check(buffer.unlock()==D3DERR_DEVICELOST,"failed upload must preserve lock record");
    check(buffer_contract::liveBytes==before+64,"failed upload released shadow");
    failSubmissionTest=false;
  }
  check(buffer_contract::liveBytes==before,"failed upload destruction leaked shadow");
  transportHealthyTest=false;
  { Buffer<IDirect3DVertexBuffer9> buffer(desc); void* data=reinterpret_cast<void*>(1);
    check(buffer.lock(0,64,&data,0)==D3DERR_DEVICELOST && !data,"failed transport returned writable pointer"); }
  transportHealthyTest=true;optimizedLockTest=true;
  { Buffer<IDirect3DVertexBuffer9> buffer(desc); void* data=reinterpret_cast<void*>(1);
    check(buffer.lock(0,64,&data,0)==D3DERR_DEVICELOST && !data,"failed optimized reservation returned pointer"); }
  optimizedLockTest=false;
  check(updates.empty(),"failed reserved lock published update");
}
int main() {
  failedUploadContract();
  run<IDirect3DVertexBuffer9>("VB", D3DFMT_VERTEXDATA);
  run<IDirect3DVertexBuffer9>("VB managed", D3DFMT_VERTEXDATA, D3DPOOL_MANAGED);
  run<IDirect3DIndexBuffer9>("IB16", D3DFMT_INDEX16);
  run<IDirect3DIndexBuffer9>("IB32", D3DFMT_INDEX32);
  runDynamic<IDirect3DVertexBuffer9>(D3DFMT_VERTEXDATA);
  runDynamic<IDirect3DIndexBuffer9>(D3DFMT_INDEX16);
  runReadable();
  check(buffer_contract::liveBytes == 0, "fixture shadow allocations did not balance");
  check(!l4d2_observation::memoryMonitoring && !l4d2_memory::nextSample
    && !l4d2_memory::bytes[1] && !l4d2_memory::bytes[2], "OFF observer initialized or updated statistics");
  buffer_contract::failAllocation = true;
  bool allocationFailed = false;
  try { delete[] l4d2_buffer::allocate(64, l4d2_memory::Kind::Vertex, true); }
  catch (const std::bad_alloc&) { allocationFailed = true; }
  buffer_contract::failAllocation = false;
  check(allocationFailed && !buffer_contract::liveBytes, "Core allocation failure contract changed");
  return failures;
}
