// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <algorithm>
#include <array>
#include <atomic>
#include <cstdint>
#include <cstdio>
#include <future>
#include <new>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

class GlobalOptions {
public:
  static DWORD getCommandTimeout() { return 5000; }
};
#include "util_circularqueue.h"
#include "util_commands.h"
#include "util_atomiccircularqueue.h"

using bridge_util::Result;
struct Item {
  Commands::D3D9Command command = Commands::Bridge_Any;
  uint32_t sequence = 0;
  uint32_t checksum = 0;
};
using Writer = bridge_util::AtomicCircularQueue<Item, bridge_util::Accessor::Writer>;
using Reader = bridge_util::AtomicCircularQueue<Item, bridge_util::Accessor::Reader>;
constexpr size_t kMapSize = 4096;
constexpr size_t kQueueSize = 8;
constexpr uint32_t kMessageCount = 100000;

void require(bool condition, const char* message) {
  if (!condition) { throw std::runtime_error(message); }
}
std::string uniqueName() {
  static uint32_t ordinal = 0;
  return "Local\\L4D2QueueTest-" + std::to_string(GetCurrentProcessId()) + "-" +
    std::to_string(GetTickCount64()) + "-" + std::to_string(++ordinal);
}
struct Memory {
  HANDLE handle;
  void* data;
  explicit Memory(const std::string& name, bool create = true) {
    handle = create ? CreateFileMappingA(INVALID_HANDLE_VALUE, nullptr, PAGE_READWRITE,
      0, static_cast<DWORD>(kMapSize), name.c_str()) :
      OpenFileMappingA(FILE_MAP_ALL_ACCESS, FALSE, name.c_str());
    require(handle != nullptr, "shared mapping failed");
    data = MapViewOfFile(handle, FILE_MAP_ALL_ACCESS, 0, 0, kMapSize);
    if (!data) { CloseHandle(handle); throw std::runtime_error("mapping view failed"); }
  }
  ~Memory() { UnmapViewOfFile(data); CloseHandle(handle); }
  Memory(const Memory&) = delete;
};
uint64_t fileTime(const FILETIME& time) {
  return (static_cast<uint64_t>(time.dwHighDateTime) << 32) | time.dwLowDateTime;
}
uint64_t threadCpu() {
  FILETIME creation{}, exit{}, kernel{}, user{};
  require(GetThreadTimes(GetCurrentThread(), &creation, &exit, &kernel, &user) != FALSE,
    "thread CPU query failed");
  return fileTime(kernel) + fileTime(user);
}

void testIdleAndCancel() {
  const auto name = uniqueName();
  Memory memory(name);
  Writer writer(name, memory.data, kMapSize, kQueueSize);
  Reader reader(name, memory.data, kMapSize, kQueueSize);
  std::atomic<bool> cancel{false};
  std::promise<void> started;
  auto task = std::async(std::launch::async, [&] {
    const auto before = threadCpu();
    started.set_value();
    Result result = Result::Success;
    reader.peek(result, 0, &cancel);
    require(result == Result::Timeout, "cancellation was not observed");
    return threadCpu() - before;
  });
  started.get_future().wait();
  Sleep(500);
  const auto start = GetTickCount64();
  cancel.store(true);
  const auto cpu = task.get();
  require(GetTickCount64() - start < 2000, "cancellation stalled");
  require(cpu < 1000000, "idle reader consumed more than 100 ms of CPU");
  std::printf("idle reader CPU: %.3f ms / 500 ms\n", static_cast<double>(cpu) / 10000.0);
}
void testTimeoutAndCompatibility() {
  const auto name = uniqueName();
  Memory memory(name);
  Writer writer(name, memory.data, kMapSize, kQueueSize);
  Reader reader(name, memory.data, kMapSize, kQueueSize);
  auto start = GetTickCount64();
  Result result = Result::Success;
  reader.peek(result, 25);
  require(result == Result::Timeout && GetTickCount64() - start >= 25,
    "peek timeout was not respected");
  result = Result::Success;
  reader.pull(result, 25);
  require(result == Result::Timeout, "pull did not report timeout");

  // An old producer does not advertise the wake protocol in its padding.
  auto* protocol = reinterpret_cast<std::atomic<uint32_t>*>(
    static_cast<char*>(memory.data) + 192);
  protocol->store(0);
  std::thread producer([&] { Sleep(20); writer.push(Item{Commands::Bridge_Any, 7, 9}); });
  const auto value = reader.pull(result, 5000);
  producer.join();
  require(result == Result::Success && value.sequence == 7, "legacy producer fallback failed");
}
void testNotificationCoalescing() {
  const auto name = uniqueName();
  Memory memory(name);
  Writer writer(name, memory.data, kMapSize, kQueueSize);
  Reader reader(name, memory.data, kMapSize, kQueueSize);
  auto* waiting = reinterpret_cast<std::atomic<uint32_t>*>(
    static_cast<char*>(memory.data) + 64);
  const auto before = l4d2_queue::counters.snapshot();
  waiting->store(1);
  for (uint32_t i = 0; i < kQueueSize - 1; ++i) {
    require(writer.push(Item{Commands::Bridge_Any, i, 0}) == Result::Success,
      "notification burst stalled");
  }
  require(l4d2_queue::counters.snapshot().signals == before.signals + 1 && !waiting->load(),
    "a waiting reader was notified repeatedly for one burst");
  for (uint32_t i = 0; i < kQueueSize - 1; ++i) {
    Result result = Result::Failure;
    const auto item = reader.pull(result, 1000);
    require(result == Result::Success && item.sequence == i, "coalesced wake lost a command");
  }
  waiting->store(1);
  require(writer.push(Item{}) == Result::Success &&
    l4d2_queue::counters.snapshot().signals == before.signals + 2,
    "a rearmed reader was not notified");
}
void testCounters() {
  l4d2_queue::Counters counters;
  std::thread first([&] {
    for (unsigned i = 0; i < 1000; ++i) {
      counters.waited(true, false);
      counters.signaled(true);
      counters.blocked(11);
    }
  });
  for (unsigned i = 0; i < 1000; ++i) {
    counters.waited(false, true);
    counters.signaled(false);
    counters.legacyWait();
    counters.blocked(7);
  }
  first.join();
  const auto s = counters.snapshot();
  require(s.waits == 2000 && s.timeouts == 1000 && s.failures == 1000 &&
    s.signals == 1000 && s.signalFailures == 1000 && s.legacyWaits == 1000 &&
    s.fullWaits == 2000 && s.fullWaitMs == 18000 && s.maxFullWaitMs == 11,
    "concurrent queue counters lost updates");
}
void testWakeAndWrap() {
  const auto name = uniqueName();
  Memory memory(name);
  Writer writer(name, memory.data, kMapSize, kQueueSize);
  Reader reader(name, memory.data, kMapSize, kQueueSize);
  auto task = std::async(std::launch::async, [&] {
    for (uint32_t i = 0; i < kMessageCount; ++i) {
      Result result = Result::Failure;
      const Item value = reader.pull(result, 5000);
      require(result == Result::Success && value.sequence == i &&
        value.checksum == (i ^ 0xa55a5aa5u), "wake/wrap sequence was corrupted");
    }
  });
  Sleep(25);
  for (uint32_t i = 0; i < kMessageCount; ++i) {
    require(writer.push(Item{Commands::Bridge_Any, i, i ^ 0xa55a5aa5u}) == Result::Success,
      "writer stalled");
    if (i % 101 == 0) { SwitchToThread(); }
  }
  task.get();
  require(reader.isEmpty(), "queue was not drained");
}
void runReader(const std::string& name) {
  Memory memory(name, false);
  Reader reader(name, memory.data, kMapSize, kQueueSize);
  for (uint32_t i = 0; i < kMessageCount; ++i) {
    Result result = Result::Failure;
    const auto value = reader.pull(result, 5000);
    require(result == Result::Success && value.sequence == i &&
      value.checksum == (i ^ 0xa55a5aa5u), "cross-process sequence was corrupted");
  }
}
void testPeer(const std::wstring& executable) {
  const auto name = uniqueName();
  Memory memory(name);
  Writer writer(name, memory.data, kMapSize, kQueueSize);
  std::wstring command = L"\"" + executable + L"\" --reader " + std::wstring(name.begin(), name.end());
  STARTUPINFOW startup{};
  startup.cb = sizeof(startup);
  PROCESS_INFORMATION process{};
  require(CreateProcessW(executable.c_str(), command.data(), nullptr, nullptr, FALSE,
    0, nullptr, nullptr, &startup, &process) != FALSE, "peer launch failed");
  CloseHandle(process.hThread);
  try {
    Sleep(25);
    for (uint32_t i = 0; i < kMessageCount; ++i) {
      require(writer.push(Item{Commands::Bridge_Any, i, i ^ 0xa55a5aa5u}) == Result::Success,
        "cross-process writer stalled");
      if (i % 8191 == 0) { Sleep(12); }
    }
    require(WaitForSingleObject(process.hProcess, 30000) == WAIT_OBJECT_0, "peer stalled");
    DWORD exitCode = 1;
    require(GetExitCodeProcess(process.hProcess, &exitCode) != FALSE && exitCode == 0,
      "peer failed");
  } catch (...) {
    TerminateProcess(process.hProcess, 1);
    CloseHandle(process.hProcess);
    throw;
  }
  CloseHandle(process.hProcess);
}
int wmain(int argc, wchar_t** argv) {
  l4d2_observation::memoryMonitoring = true;
  try {
    if (argc == 3 && std::wstring(argv[1]) == L"--reader") {
      const std::wstring wideName = argv[2];
      std::string name;
      for (const wchar_t character : wideName) {
        require(static_cast<uint32_t>(character) < 128, "expected ASCII test mapping name");
        name.push_back(static_cast<char>(character));
      }
      runReader(name);
    } else {
      require(argc == 2, "expected peer executable path");
      testIdleAndCancel();
      testTimeoutAndCompatibility();
      testNotificationCoalescing();
      testCounters();
      testWakeAndWrap();
      testPeer(argv[1]);
      std::puts("Command queue tests passed");
    }
    return 0;
  } catch (const std::exception& error) {
    std::fprintf(stderr, "%s\n", error.what());
    return 1;
  }
}
