// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#pragma once
// Force-included only in the observation regression executable and its objects.
#include <windows.h>
#include <d3d9.h>
#include <dxgi1_4.h>
#include <psapi.h>
#include <tlhelp32.h>
#include <algorithm>
#include <atomic>
#include <thread>
#include <mutex>
#include <filesystem>
#include <functional>
#include <map>
#include <memory>
#include <string>
#include <vector>

namespace diagnostic_work {
inline std::atomic<unsigned> scans { 0 }, clocks { 0 }, files { 0 }, threads { 0 };
inline std::atomic<unsigned> hooks { 0 }, windows { 0 }, modules { 0 }, locks { 0 }, allocations { 0 };
inline SIZE_T WINAPI query(LPCVOID address, PMEMORY_BASIC_INFORMATION result, SIZE_T size) {
  ++scans; return VirtualQuery(address, result, size);
}
inline ULONGLONG WINAPI tick() { ++clocks; return GetTickCount64(); }
inline BOOL WINAPI counter(PLARGE_INTEGER result) { ++clocks; return QueryPerformanceCounter(result); }
inline BOOL WINAPI frequency(PLARGE_INTEGER result) { ++clocks; return QueryPerformanceFrequency(result); }
inline HANDLE WINAPI fileW(LPCWSTR name, DWORD access, DWORD share, LPSECURITY_ATTRIBUTES security,
  DWORD disposition, DWORD flags, HANDLE templateFile) {
  ++files; return CreateFileW(name, access, share, security, disposition, flags, templateFile);
}
inline HANDLE WINAPI fileA(LPCSTR name, DWORD access, DWORD share, LPSECURITY_ATTRIBUTES security,
  DWORD disposition, DWORD flags, HANDLE templateFile) {
  ++files; return CreateFileA(name, access, share, security, disposition, flags, templateFile);
}
inline HANDLE WINAPI thread(LPSECURITY_ATTRIBUTES security, SIZE_T size, LPTHREAD_START_ROUTINE start,
  LPVOID context, DWORD flags, LPDWORD id) {
  ++threads; return CreateThread(security, size, start, context, flags, id);
}
inline HHOOK WINAPI hook(int kind, HOOKPROC callback, HINSTANCE instance, DWORD id) {
  ++hooks; return SetWindowsHookExW(kind, callback, instance, id);
}
inline HWND WINAPI window(DWORD extended, LPCWSTR type, LPCWSTR title, DWORD style, int x, int y,
  int width, int height, HWND parent, HMENU menu, HINSTANCE instance, LPVOID context) {
  ++windows; return CreateWindowExW(extended, type, title, style, x, y, width, height, parent, menu, instance, context);
}
inline HANDLE WINAPI snapshot(DWORD flags, DWORD id) { ++modules; return CreateToolhelp32Snapshot(flags, id); }
inline HMODULE WINAPI module(LPCWSTR name) { ++modules; return GetModuleHandleW(name); }
inline void WINAPI exclusive(PSRWLOCK lock) { ++locks; AcquireSRWLockExclusive(lock); }
inline void WINAPI shared(PSRWLOCK lock) { ++locks; AcquireSRWLockShared(lock); }
}
#define VirtualQuery diagnostic_work::query
#define GetTickCount64 diagnostic_work::tick
#define QueryPerformanceCounter diagnostic_work::counter
#define QueryPerformanceFrequency diagnostic_work::frequency
#define CreateFileW diagnostic_work::fileW
#define CreateFileA diagnostic_work::fileA
#define CreateThread diagnostic_work::thread
#define SetWindowsHookExW diagnostic_work::hook
#define CreateWindowExW diagnostic_work::window
#define CreateToolhelp32Snapshot diagnostic_work::snapshot
#define GetModuleHandleW diagnostic_work::module
#define AcquireSRWLockExclusive diagnostic_work::exclusive
#define AcquireSRWLockShared diagnostic_work::shared
