// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
// Only the complete executable checks bytes. The floor is not semantically valid.
namespace {
[[noreturn]] void fail(const char* message) { std::fprintf(stderr, "%s\n", message); std::exit(2); }
void check(bool value, const char* message) { if (!value) { fail(message); } }
unsigned assertions = 0;
void expect(bool value, const char* message) { check(value, message); ++assertions; }
using Clock = std::chrono::steady_clock;
double cpuNs() {
  FILETIME creation{}, exit{}, kernel{}, user{};
  check(GetThreadTimes(GetCurrentThread(), &creation, &exit, &kernel, &user) != 0, "GetThreadTimes");
  ULARGE_INTEGER k{}, u{}; k.LowPart=kernel.dwLowDateTime; k.HighPart=kernel.dwHighDateTime;
  u.LowPart=user.dwLowDateTime; u.HighPart=user.dwHighDateTime;
  return static_cast<double>(k.QuadPart + u.QuadPart) * 100.0;
}
template<typename T> struct TestedBuffer : LockableBuffer<T> {
  using Base = LockableBuffer<T>;
  using Desc = std::conditional_t<std::is_same_v<T, IDirect3DVertexBuffer9>, D3DVERTEXBUFFER_DESC, D3DINDEXBUFFER_DESC>;
  TestedBuffer(BaseDirect3DDevice9Ex_LSS* device, const Desc& desc) : Base(nullptr, device, desc) {}
  using Base::lock;
  HRESULT Unlock() {
    l4d2_api_wait::ApiScope timing(std::is_same_v<T, IDirect3DVertexBuffer9> ? l4d2_api_wait::Api::VertexUnlock : l4d2_api_wait::Api::IndexUnlock);
    std::lock_guard<std::recursive_mutex> guard(this->device->mutex);
    this->unlock();
    return S_OK;
  }
};
constexpr size_t kCommandSlots=65536, kMemory=64u*1024*1024;
struct ChannelPair {
  WriterChannel writer;
  ReaderChannel reader;
  ChannelPair() : writer("UploadCost", kMemory, kCommandSlots, 0), reader("UploadCost", kMemory, kCommandSlots, 0) {
    DeviceBridge::s_pWriterChannel=&writer;
    check(sizeof(Header)==12 && sizeof(void*)==4, "native x86 layout required");
  }
  ~ChannelPair() {
    DeviceBridge::s_pWriterChannel=nullptr;
    // The production channel does not free its process-local progress flag.
    delete writer.pbCmdInProgress;
    delete reader.pbCmdInProgress;
  }
  void resetData() {
    // Staged, drained experiment. No pending command or live blob is retained.
    check(writer.commands->isEmpty(), "reset requires drained command queue");
    auto* w=writer.data; auto* r=reader.data;
    void* wp=w->data(); void* rp=r->data();
    w->~DataQueue(); r->~DataQueue();
    new(w) DataQueue("UploadCostData", Accessor::Writer, wp, writer.m_dataMemSize, 0);
    new(r) DataQueue("UploadCostData", Accessor::Reader, rp, reader.m_dataMemSize, 0);
    *writer.serverDataPos=-1; *writer.clientDataExpectedPos=-1; *writer.serverResetPosRequired=false;
  }
  struct Packet { Header header; UINT uid, offset, bytes, lockFlags; const uint8_t* data; };
  Packet consume() {
    Result result;
    Packet p{}; p.header=reader.commands->pull(result, 1000);
    check(RESULT_SUCCESS(result), "header publication lost");
    p.uid=reader.data->pull(); p.offset=reader.data->pull(); p.bytes=reader.data->pull(); p.lockFlags=reader.data->pull();
    void* blob=nullptr; auto bytes=reader.data->pull(&blob);
    check(bytes==p.bytes && reader.data->get_pos()==p.header.dataOffset, "codec fields / end position");
    p.data=static_cast<const uint8_t*>(blob);
    *reader.serverDataPos=reader.data->get_pos();
    return p;
  }
};
template<typename T> void semantics(ChannelPair& channel) {
  using Buffer=TestedBuffer<T>; typename Buffer::Desc desc{};
  desc.Size=256; desc.Usage=D3DUSAGE_DYNAMIC | D3DUSAGE_WRITEONLY;
  BaseDirect3DDevice9Ex_LSS device; Buffer buffer(&device, desc);
  channel.resetData();
  void* full=nullptr;
  expect(buffer.lock(0, 0, &full, D3DLOCK_DISCARD)==S_OK, "whole lock");
  for (unsigned i=0;i<desc.Size;++i) { static_cast<uint8_t*>(full)[i]=static_cast<uint8_t>(i); }
  auto uid=DeviceBridge::s_cmdUID;
  expect(buffer.Unlock()==S_OK, "unlock result");
  auto p=channel.consume();
  expect(p.uid==uid && p.header.pHandle==1 && p.header.flags==0, "UID/object/header flags");
  expect(p.header.command==(std::is_same_v<T, IDirect3DVertexBuffer9> ? Commands::IDirect3DVertexBuffer9_Unlock : Commands::IDirect3DIndexBuffer9_Unlock), "VB/IB opcode");
  expect(p.offset==0 && p.bytes==256 && p.lockFlags==D3DLOCK_DISCARD, "whole range");
  expect(std::memcmp(p.data, full, 256)==0, "complete shadow payload");
  void* partial=nullptr;
  expect(buffer.lock(17, 51, &partial, D3DLOCK_NOOVERWRITE)==S_OK, "partial lock");
  std::memset(partial, 0xe5, 51); buffer.Unlock(); p=channel.consume();
  expect(p.offset==17 && p.bytes==51 && p.lockFlags==D3DLOCK_NOOVERWRITE, "partial metadata");
  expect(std::memcmp(p.data, partial, 51)==0, "odd-size payload / alignment");
  expect(static_cast<uint8_t*>(full)[16]==16 && static_cast<uint8_t*>(full)[68]==68, "unwritten history");
  expect(buffer.lock(253, 0, &partial, 0)==S_OK, "size zero tail"); buffer.Unlock(); p=channel.consume();
  expect(p.offset==253 && p.bytes==3 && std::memcmp(p.data, partial, 3)==0, "tail bytes");
  expect(buffer.lock(250, 100, &partial, 0)==S_OK, "existing oversize behavior"); buffer.Unlock(); p=channel.consume();
  expect(p.offset==250 && p.bytes==6, "existing clamp behavior");
  expect(buffer.lock(0, 1, nullptr, 0)==D3DERR_INVALIDCALL, "null output error");
  uid=DeviceBridge::s_cmdUID; buffer.Unlock();
  expect(channel.writer.commands->isEmpty() && DeviceBridge::s_cmdUID==uid, "benign unmatched unlock");
  expect(buffer.lock(3, 16, &partial, D3DLOCK_READONLY)==S_OK, "readonly lock"); buffer.Unlock();
  expect(channel.writer.commands->isEmpty() && DeviceBridge::s_cmdUID==uid, "readonly no upload");
  void* first=nullptr; void* second=nullptr;
  buffer.lock(1, 4, &first, 0); buffer.lock(9, 8, &second, 0);
  buffer.Unlock(); p=channel.consume(); expect(p.offset==1 && p.bytes==4, "multiple locks FIFO first");
  buffer.Unlock(); p=channel.consume(); expect(p.offset==9 && p.bytes==8, "multiple locks FIFO second");
  buffer.lock(0, 16, &partial, 0); gbBridgeRunning=false; buffer.Unlock(); gbBridgeRunning=true;
  expect(channel.writer.commands->isEmpty() && !channel.writer.pbCmdInProgress->load(), "bridge disabled publication cleanup");
}
template<typename T> void benchmark(ChannelPair& channel, unsigned size, bool streaming, bool warm) {
  using Buffer=TestedBuffer<T>; typename Buffer::Desc desc{};
  desc.Size=streaming ? 64u*1024*1024 : 1024u*1024;
  desc.Usage=D3DUSAGE_DYNAMIC | D3DUSAGE_WRITEONLY;
  BaseDirect3DDevice9Ex_LSS device; Buffer buffer(&device, desc);
  void* base=nullptr; buffer.lock(0, 0, &base, D3DLOCK_READONLY); buffer.Unlock();
  std::memset(base, 0xa7, desc.Size);
  // Bound both call count and copied bytes; timers run only around batches.
  const size_t calls=warm ? 4096 : (std::max)(size_t(4096), (std::min)(size_t(1000000), size_t(128u*1024*1024)/size));
  const size_t batch=(std::min)(size_t(60000), size_t(16u*1024*1024)/(size+32));
  double upload=0, cpu=0, consume=0; size_t cursor=0, total=0;
  for (size_t done=0;done<calls;) {
    channel.resetData();
    const size_t count=(std::min)(batch, calls-done);
    for (size_t i=0;i<count;++i) {
      void* data=nullptr;
      check(buffer.lock(static_cast<UINT>(cursor), size, &data, D3DLOCK_NOOVERWRITE)==S_OK, "prepare lock");
      cursor=streaming ? (cursor+size <= desc.Size-size ? cursor+size : 0) : 0;
    }
    const double cpuStart=cpuNs(); const auto start=Clock::now();
    for (size_t i=0;i<count;++i) { buffer.Unlock(); }
    const auto end=Clock::now(); const double cpuEnd=cpuNs();
    upload+=std::chrono::duration<double,std::nano>(end-start).count(); cpu+=cpuEnd-cpuStart;
    const auto consumeStart=Clock::now();
    for (size_t i=0;i<count;++i) {
      const auto p=channel.consume();
      check(p.bytes==size && p.header.flags==0 && p.lockFlags==D3DLOCK_NOOVERWRITE, "benchmark framing");
      total+=p.bytes;
    }
    consume+=std::chrono::duration<double,std::nano>(Clock::now()-consumeStart).count();
    done+=count;
  }
  check(total==calls*size, "payload count");
  std::printf("{\"calls\":%zu,\"batch_calls\":%zu,\"payload_bytes\":%zu,\"wire_bytes_without_tail_padding\":%zu,\"upload_ns\":%.6f,\"upload_cpu_ns\":%.6f,\"consume_ns\":%.6f}\n", calls, batch, total, calls*(32+bridge_util::align<size_t>(size,4)), upload/calls, cpu/calls, consume/calls);
}
}
int main(int argc, char** argv) {
  ChannelPair channel;
  if (argc==2 && std::string(argv[1])=="semantic") {
#ifdef L4D2_COST_NO_COPY
    fail("no-copy floor cannot validate payload semantics");
#else
    semantics<IDirect3DVertexBuffer9>(channel); semantics<IDirect3DIndexBuffer9>(channel);
    std::printf("{\"assertions\":%u,\"payload_equivalent\":true,\"scope\":\"fixture full path only; no optimization\"}\n", assertions);
    return 0;
#endif
  }
  check(argc>=5 && std::string(argv[1])=="bench", "usage: bench vb|ib size hot|stream [warm]");
  unsigned size=static_cast<unsigned>(std::stoul(argv[3])); check(size>0 && size<=262144, "size range");
  if (std::string(argv[2])=="vb") { benchmark<IDirect3DVertexBuffer9>(channel, size, std::string(argv[4])=="stream", argc>5); }
  else if (std::string(argv[2])=="ib") { benchmark<IDirect3DIndexBuffer9>(channel, size, std::string(argv[4])=="stream", argc>5); }
  else { fail("unknown buffer kind"); }
}
