// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
// Test boundaries: options, logger, COM owner, shadow allocation and peer state.
#include <d3d9.h>
#include <algorithm>
#include <array>
#include <cassert>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <memory>
#include <mutex>
#include <queue>
#include <sstream>
#include <string>
#include <thread>
#include <type_traits>
#include <vector>
#include "config/global_options.h"
#include "log/log.h"
#include "util_common.h"
#include "util_commands.h"
#include "util_circularbuffer.h"
#include "util_semaphore.h"
#include "util_ipcchannel.h"
#include "api_wait_diagnostics.h"
#include "data_diagnostics.h"
#include "exception_diagnostics.h"
using namespace bridge_util;
#define ZoneScoped
bool gbBridgeRunning = true;
bridge_util::Guid gUniqueIdentifier;
struct BridgeState {
  enum class ProcessState { Running, DoneProcessing };
  static ProcessState getServerState_NoLock() { return ProcessState::Running; }
};
// INSERT_PRODUCTION_BRIDGE
struct BaseDirect3DDevice9Ex_LSS { std::recursive_mutex mutex; };
template<typename T> struct Direct3DResource9_LSS {
  BaseDirect3DDevice9Ex_LSS* device;
  Direct3DResource9_LSS(T*, BaseDirect3DDevice9Ex_LSS* owner) : device(owner) {}
  uint32_t getId() const { return 1; }
};
struct ClientOptions { static bool getOptimizedDynamicLock() { return false; } };
namespace l4d2_memory {
enum class Kind { Vertex, Index };
inline void released(size_t, Kind) {}
}
namespace l4d2_buffer {
inline uint8_t* allocate(size_t size, l4d2_memory::Kind, bool) { return new uint8_t[size](); }
}
namespace SharedHeap {
using AllocId = uint32_t;
constexpr AllocId kInvalidId = UINT32_MAX;
inline AllocId allocate(size_t) { return kInvalidId; }
inline void deallocate(AllocId) {}
inline uint8_t* getBuf(AllocId) { return nullptr; }
}
