// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

#define NOMINMAX
#include "host_memory_diagnostics.h"
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

uint64_t value(const std::string& line, const std::string& key) {
  const auto pos = line.find(key + "=");
  if (pos == std::string::npos) { return UINT64_MAX; }
  return std::stoull(line.substr(pos + key.size() + 1), nullptr, 0);
}

int main(int argc, char** argv) {
  l4d2_observation::memoryMonitoring = true;
  if (argc != 2) { return 1; }
  l4d2_host_memory::ResourceInventory inventory;
  using Kind = l4d2_host_memory::ResourceKind;
  inventory.track(1, 11, Kind::Texture);
  inventory.track(1, 11, Kind::Texture);
  inventory.track(1, 12, Kind::CubeTexture);
  inventory.track(2, 22, Kind::Surface);
  inventory.erase(2, true);
  inventory.erase(99);
  auto totals = inventory.snapshot();
  if (totals.handles != 1 || totals.live[0] != 0 || totals.live[1] != 1 ||
      totals.registrations != 4 || totals.rebinds != 1 || totals.replacements != 1 ||
      totals.destroys != 1 || totals.unlinks != 1 || totals.missingErases != 1) { return 11; }
  inventory.erase(1);
  if (inventory.snapshot().handles || inventory.snapshot().live[1]) { return 12; }
  inventory.track(3, 33, Kind::Texture);
  l4d2_queue::counters.waited(true, false);
  l4d2_queue::counters.blocked(17);
  {
    l4d2_host_memory::Recorder recorder;
    l4d2_host_memory::Objects objects;
    objects.resourceTotals = inventory.snapshot();
    objects.resources = 1;
    // No hardware is required: an impossible adapter must remain explicitly invalid.
    recorder.setGpuAdapter(UINT32_MAX, UINT32_MAX);
    if (!recorder.isOpen() || !recorder.sample(objects, "baseline")) { return 2; }
    constexpr size_t allocationSize = 64 * 1024 * 1024;
    auto* memory = static_cast<volatile unsigned char*>(VirtualAlloc(nullptr,
      allocationSize, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE));
    if (!memory) { return 3; }
    constexpr size_t mappingSize = 32 * 1024 * 1024;
    const auto section = CreateFileMappingW(INVALID_HANDLE_VALUE, nullptr, PAGE_READWRITE,
      0, static_cast<DWORD>(mappingSize), nullptr);
    if (!section) { return 13; }
    const auto view = MapViewOfFile(section, FILE_MAP_ALL_ACCESS, 0, 0, mappingSize);
    if (!view) { CloseHandle(section); return 14; }
    for (size_t i = 0; i < allocationSize; i += 4096) { memory[i] = 1; }
    const auto start = GetTickCount64();
    volatile uint64_t work = 0;
    while (GetTickCount64() - start < 100) { ++work; }
    if (!recorder.sample(objects, "allocated", GetCurrentProcess())) { return 4; }
    if (!VirtualFree(const_cast<unsigned char*>(memory), 0, MEM_RELEASE)) { return 5; }
    if (!UnmapViewOfFile(view) || !CloseHandle(section)) { return 15; }
    if (!recorder.sample(objects, "released")) { return 6; }
  }
  std::ifstream file(argv[1]);
  std::vector<std::string> lines;
  std::string line;
  while (std::getline(file, line)) { lines.push_back(line); }
  if (lines.size() != 3) { return 7; }
  for (const auto& record : lines) {
    if (value(record, "counters_valid") != 1 || value(record, "commit_valid") != 1 ||
        value(record, "physical_valid") != 1 || value(record, "handles_valid") != 1 ||
        !value(record, "processors") || value(record, "pid") != GetCurrentProcessId() ||
        value(record, "schema") != 3 || value(record, "q_wait_events") != 1 ||
        value(record, "q_wait_timeouts") != 1 || value(record, "q_full_wait_ms") != 17) { return 8; }
    if (value(record, "address_memory_valid") != 1 || !value(record, "address_regions") ||
        value(record, "resource_inventory_valid") != 1 || value(record, "texture_handles") != 1 ||
        value(record, "resource_replace_total") != 1 || value(record, "gpu_local_valid") != 0 ||
        value(record, "gpu_nonlocal_valid") != 0 || value(record, "gpu_vendor") != UINT32_MAX) { return 16; }
    const auto freeBytes = value(record, "address_free_bytes");
    const auto largestFreeBlock = value(record, "address_largest_free_block");
    if (freeBytes == UINT64_MAX || largestFreeBlock == UINT64_MAX ||
        !largestFreeBlock || largestFreeBlock > freeBytes) { return 18; }
  }
  const uint64_t minimumChange = 48 * 1024 * 1024;
  const auto baseline = value(lines[0], "private_bytes");
  const auto allocated = value(lines[1], "private_bytes");
  const auto released = value(lines[2], "private_bytes");
  if (allocated < baseline + minimumChange || released + minimumChange > allocated) { return 9; }
  if (value(lines[1], "address_private_commit") < value(lines[0], "address_private_commit") + minimumChange ||
      value(lines[2], "address_private_commit") + minimumChange > value(lines[1], "address_private_commit") ||
      value(lines[1], "address_mapped_commit") < value(lines[0], "address_mapped_commit") + 24 * 1024 * 1024 ||
      value(lines[2], "address_mapped_commit") + 24 * 1024 * 1024 > value(lines[1], "address_mapped_commit")) { return 17; }
  // Committed private memory and a mapped section both consume address space.
  // Releasing them must restore it in both x86 and x64 processes.
  const auto baselineFree = value(lines[0], "address_free_bytes");
  const auto allocatedFree = value(lines[1], "address_free_bytes");
  const auto releasedFree = value(lines[2], "address_free_bytes");
  if (baselineFree < allocatedFree + minimumChange ||
      releasedFree < allocatedFree + minimumChange) { return 19; }
  if (value(lines[0], "cpu_valid") != 0 || value(lines[1], "cpu_valid") != 1 ||
      value(lines[1], "client_exit_code_valid") != 1 ||
      value(lines[1], "client_exit_code") != STILL_ACTIVE ||
      value(lines[1], "cpu_kernel_100ns") + value(lines[1], "cpu_user_100ns") <=
      value(lines[0], "cpu_kernel_100ns") + value(lines[0], "cpu_user_100ns")) { return 10; }
  return 0;
}
