// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include <cstdarg>
#include <cstdio>
#include <cstdint>
#include <cassert>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

// Deterministic Win32/COM adapters; production method bodies are inserted below.
using DWORD = unsigned long;
using ULONG = unsigned long;
using HRESULT = int32_t;
using HINSTANCE = void*;
using HHOOK = void*;
using HOOKPROC = void(*)();
using LPDIRECTINPUTA = void*;
using LPDIRECTINPUTW = void*;
using LPUNKNOWN = void*;
using Create = HRESULT(*)(HINSTANCE, DWORD, void**, LPUNKNOWN);
#define WINAPI
#define FAILED(result) ((result) < 0)
constexpr int WH_CALLWNDPROC = 4, WH_GETMESSAGE = 3, WH_KEYBOARD = 2, WH_KEYBOARD_LL = 13;

static unsigned formats = 0, lastErrorReads = 0, functionCalls = 0, missingCalls = 0;
static bool debugEnabled = false, throwLog = false;
static std::vector<std::string> warnings, debugMessages;
static DWORD lastError = 0;
static int failedHook = 0;
static std::vector<int> installed, removed;
static std::unordered_map<int, HHOOK> gWinHooks;

static std::string format_string(const char* pattern, ...) {
  ++formats;
  char buffer[512] {};
  va_list args;
  va_start(args, pattern);
  std::vsnprintf(buffer, sizeof(buffer), pattern, args);
  va_end(args);
  return buffer;
}
struct Logger {
  static void warn(const std::string& text) {
    lastError = 999;
    if (throwLog) { throw std::runtime_error("observer failure"); }
    warnings.push_back(text);
  }
  template<class Producer> static void debugLazy(Producer producer) {
    if (debugEnabled) {
      if (throwLog) { throw std::runtime_error("observer failure"); }
      debugMessages.push_back(producer());
    }
  }
};
struct ClientOptions {
  inline static bool customHooks = false;
  static bool getOverrideCustomWinHooks() { return customHooks; }
};
static DWORD GetCurrentThreadId() { return 73; }
static DWORD GetLastError() { ++lastErrorReads; return lastError; }
static void HookedCallWndProc() {}
static void HookedGetMsgProc() {}
static void HookedKeyboardProc() {}
static HHOOK SetWindowsHookEx(int id, HOOKPROC proc, HINSTANCE module, DWORD thread) {
  if (id == WH_KEYBOARD_LL || !proc || module || thread != 73) {
    throw std::runtime_error("Unexpected global hook or installation arguments");
  }
  installed.push_back(id);
  if (id == failedHook) { lastError = 1428; return nullptr; }
  return reinterpret_cast<HHOOK>(static_cast<uintptr_t>(id));
}
static void UnhookWindowsHookEx(HHOOK hook) {
  if (!hook) { throw std::runtime_error("Unhook called with null handle"); }
  removed.push_back(static_cast<int>(reinterpret_cast<uintptr_t>(hook)));
}

static bool gClientUsesDirectInput = false;
static HRESULT createResult = 0;
static unsigned createCalls = 0;
static DWORD seenVersion = 0;
static HINSTANCE seenInstance = nullptr;
static LPUNKNOWN seenOuter = nullptr;
static void** seenOutput = nullptr;
static char seenApi = 0;
static HRESULT create(HINSTANCE instance, DWORD version, void** output, LPUNKNOWN outer) {
  ++createCalls;
  seenVersion = version; seenInstance = instance; seenOutput = output; seenOuter = outer;
  return createResult;
}
static HRESULT createA(HINSTANCE instance, DWORD version, void** output, LPUNKNOWN outer) {
  seenApi = 'A'; return create(instance, version, output, outer);
}
static HRESULT createW(HINSTANCE instance, DWORD version, void** output, LPUNKNOWN outer) {
  seenApi = 'W'; return create(instance, version, output, outer);
}
#define LogStaticFunctionCall() (++functionCalls)
#define LogFunctionCall() (++functionCalls)
#define LogMissingFunctionCall() (++missingCalls)
struct D3DBase {
  ULONG refs = 1;
  unsigned releases = 0, additions = 0, destructions = 0;
  ULONG AddRef() { ++additions; return ++refs; }
  ULONG Release() { ++releases; if (!--refs) { ++destructions; } return refs; }
};
struct Direct3DQuery9_LSS : D3DBase {
  ULONG AddRef();
  ULONG Release();
};

// PRODUCTION_METHODS

static void check(bool success, const char* message) {
  if (!success) { throw std::runtime_error(message); }
}
static void clearLogs() { warnings.clear(); debugMessages.clear(); formats = 0; }
int main() {
  try {
    InputWinHooksAttach();
    check(installed.empty() && formats == 0 && lastErrorReads == 0, "OFF installed or observed hooks");
    ClientOptions::customHooks = true;
    InputWinHooksAttach();
    check(installed == std::vector<int>({4, 3, 2}), "Thread hooks changed or invalid LL hook attempted");
    InputWinHooksDetach();
    check(removed.size() == 3 && gWinHooks.empty(), "Valid hooks not detached");
    installed.clear(); removed.clear();
    failedHook = WH_GETMESSAGE;
    InputWinHooksAttach();
    check(warnings.size() == 1 && warnings[0].find("idHook=3 error=1428") != std::string::npos,
          "Hook error not captured immediately");
    check(lastErrorReads == 1 && installed.size() == 3, "Failure stopped independent hook installation");
    InputWinHooksDetach();
    check(removed.size() == 2, "Failed hook handle detached");
    throwLog = true;
    InputWinHooksAttach();
    check(gWinHooks.size() == 3, "Observer failure stopped hook setup");
    InputWinHooksDetach();
    throwLog = false;
    clearLogs();

    void* output = reinterpret_cast<void*>(uintptr_t(17));
    const auto instance = reinterpret_cast<HINSTANCE>(uintptr_t(19));
    const auto outer = reinterpret_cast<LPUNKNOWN>(uintptr_t(23));
    for (char api : {'A', 'W'}) {
      const auto invoke = api == 'A' ? DirectInput7Hook::HookedDirectInputCreateA
                                    : DirectInput7Hook::HookedDirectInputCreateW;
      for (DWORD version : {0x050aul, 0x0700ul}) {
        clearLogs(); debugEnabled = false; createResult = 1;
        const auto before = createCalls;
        check(invoke(instance, version, &output, outer) == 1, "Successful HRESULT changed");
        check(createCalls == before + 1 && seenApi == api && seenVersion == version
          && seenInstance == instance && seenOutput == &output && seenOuter == outer
          && output == reinterpret_cast<void*>(uintptr_t(17)), "Original arguments/call count changed");
        check(warnings.empty() && debugMessages.empty() && formats == 0, "Quiet success formatted a log");
      }
      debugEnabled = true;
      check(invoke(instance, 0x050a, &output, outer) == 1, "Legacy success changed");
      check(warnings.empty() && debugMessages.size() == 1
        && debugMessages[0].find("legacy version 0x050a") != std::string::npos, "Legacy request mislabeled unsupported");
      throwLog = true;
      check(invoke(instance, 0x050a, &output, outer) == 1, "Debug observer failure changed success");
      throwLog = false;
      clearLogs(); createResult = -17;
      check(invoke(instance, 0x050a, &output, outer) == -17, "Failed HRESULT changed");
      const char* expected = sizeof(unsigned long) == 4
        ? "requestedVersion=0x050a HRESULT=0xffffffef"
        : "requestedVersion=0x050a HRESULT=0xffffffffffffffef";
      check(warnings.size() == 1 && warnings[0].find(expected) != std::string::npos,
        "Failure omitted raw version or HRESULT");
      throwLog = true;
      check(invoke(instance, 0x050a, &output, outer) == -17, "Log failure changed original result");
      throwLog = false;
    }
    check(gClientUsesDirectInput, "Existing input selection tracking changed");
    Direct3DQuery9_LSS query;
    const auto before = functionCalls;
    check(query.AddRef() == 2 && query.Release() == 1 && query.Release() == 0,
      "Query failed to delegate reference operations/results");
    check(query.additions == 1 && query.releases == 2 && query.destructions == 1
      && missingCalls == 0 && functionCalls == before + 3, "Query lifecycle delegation or log classification changed");
    std::puts("PASS: hooks OFF/ON/failure; original DirectInput A/W versions/results; lazy logs; Query delegation");
    return 0;
  } catch (const std::exception& error) {
    std::fprintf(stderr, "FAIL: %s\n", error.what());
    return 1;
  }
}
