// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.

#define NOMINMAX
#include "buffer_shadow.h"
#include "pagefile_shadow.h"
#include <fstream>
#include <iterator>
#include <limits>
#include <string>
#include <memory>
#include <vector>

int testShadowCache() {
  using namespace l4d2_memory;
  SYSTEM_INFO system {};
  GetSystemInfo(&system);
  const size_t budget = system.dwAllocationGranularity;
  {
    PagefileShadow a, b;
    if (a.acquire(0, budget)) { return 10; }
    auto* first = a.acquire(4096, budget);
    if (!first) { return 11; }
    for (size_t i = 0; i < 4096; ++i) { first[i] = static_cast<uint8_t>(i); }
    if (!b.acquire(4096, budget) || a.get() != first) { return 12; }
    b.release(budget);
    if (b.get() || !a.get()) { return 13; } // Locked a cannot be evicted.
    if (a.acquire(4096, budget) != first) { return 14; }
    a.release(0);
    if (!a.get()) { return 15; } // Nested lock still pins the view.
    a.release(0);
    if (a.get() || bytes[0] || surfaceViewBudgetBytes ||
        surfaceBackingBytes != 8192 || surfaceBackingCount != 2) { return 16; }
    auto* restored = a.acquire(4096, budget);
    if (!restored) { return 17; }
    for (size_t i = 0; i < 4096; ++i) {
      if (restored[i] != static_cast<uint8_t>(i)) { return 18; }
    }
    a.release(budget);
    if (!b.acquire(4096, budget) || a.get()) { return 19; }
    b.release(budget);
    if (surfaceViewBudgetBytes > budget) { return 20; }
  }
  if (bytes[0] || objects[0] || surfaceBackingBytes || surfaceBackingCount ||
      surfaceViewBudgetBytes) { return 21; }
  {
    std::vector<std::unique_ptr<PagefileShadow>> shadows;
    for (unsigned i = 0; i < 128; ++i) {
      auto shadow = std::make_unique<PagefileShadow>();
      auto* data = shadow->acquire(4096, 4 * budget);
      if (!data) { return 22; }
      data[0] = static_cast<uint8_t>(i);
      data[4095] = static_cast<uint8_t>(255 - i);
      shadow->release(4 * budget);
      if (surfaceViewBudgetBytes > 4 * budget) { return 23; }
      shadows.push_back(std::move(shadow));
    }
    for (unsigned i = 0; i < shadows.size(); ++i) {
      auto* data = shadows[i]->acquire(4096, 4 * budget);
      if (!data || data[0] != static_cast<uint8_t>(i) ||
          data[4095] != static_cast<uint8_t>(255 - i)) { return 24; }
      shadows[i]->release(0);
    }
  }
  if (bytes[0] || objects[0] || surfaceBackingBytes || surfaceBackingCount ||
      surfaceViewBudgetBytes) { return 25; }
  return 0;
}

int main(int argc, char** argv) {
  l4d2_observation::memoryMonitoring = true;
  if (argc != 2) { return 1; }
  using namespace l4d2_memory;
  l4d2_queue::counters.waited(true, false);
  l4d2_queue::counters.blocked(17);
  auto surface = l4d2_buffer::allocate(4096, Kind::Surface);
  auto vertex = l4d2_buffer::allocate(8192, Kind::Vertex, true);
  auto index = l4d2_buffer::allocate(2048, Kind::Index);
  if (bytes[0] != 4096 || bytes[1] != 8192 || bytes[2] != 2048 ||
      objects[0] != 1 || objects[1] != 1 || objects[2] != 1) { return 2; }
  if (allocatedBytes[1] != 8192 || allocatedBytes[2] != 2048 || allocationCount[1] != 1
      || allocationCount[2] != 1 || peakBytes[1] != 8192 || peakBytes[2] != 2048) { return 30; }
  const auto privateRegion = VirtualAlloc(nullptr, 16 * 1024 * 1024, MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE);
  const auto mapping = CreateFileMappingW(INVALID_HANDLE_VALUE, nullptr, PAGE_READWRITE, 0, 8 * 1024 * 1024, nullptr);
  const auto view = mapping ? MapViewOfFile(mapping, FILE_MAP_ALL_ACCESS, 0, 0, 0) : nullptr;
  if (!privateRegion || !view) { return 31; }
  const auto va = scanAddressSpace();
  if (!va.complete || va.committed != va.privateCommitted + va.mappedCommitted + va.imageCommitted + va.otherCommitted
      || va.reserved != va.privateReserved + va.mappedReserved + va.imageReserved + va.otherReserved
      || va.free + va.reserved + va.committed != va.limit
      || va.privateCommitted < 16 * 1024 * 1024 || va.mappedCommitted < 8 * 1024 * 1024 || !va.imageCommitted) { return 32; }
  if (!UnmapViewOfFile(view) || !CloseHandle(mapping) || !VirtualFree(privateRegion, 0, MEM_RELEASE)) { return 33; }
  for (size_t i = 0; i < 8192; ++i) {
    if (vertex[i] != 0) { return 3; }
  }
  delete[] surface; released(4096, Kind::Surface);
  delete[] vertex; released(8192, Kind::Vertex);
  delete[] index; released(2048, Kind::Index);
  if (bytes[0] != 0 || bytes[1] != 0 || bytes[2] != 0 ||
      objects[0] != 0 || objects[1] != 0 || objects[2] != 0) { return 4; }
  if (freedBytes[1] != 8192 || freedBytes[2] != 2048 || freeCount[1] != 1 || freeCount[2] != 1) { return 34; }
  bool failed = false;
  try {
    auto impossible = l4d2_buffer::allocate(std::numeric_limits<size_t>::max(), Kind::Surface);
    delete[] impossible;
  } catch (const std::bad_alloc&) { failed = true; }
  if (!failed || bytes[0] != 0 || objects[0] != 0) { return 5; }
  const auto shadowResult = testShadowCache();
  if (shadowResult) { return shadowResult; }
  sample(true, "test-final");
  std::ifstream file(argv[1]);
  const std::string text((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
  if (text.find("event=allocation-failed") == std::string::npos ||
      text.find("event=test-final") == std::string::npos ||
      text.find("scan_complete=1") == std::string::npos ||
      text.find("counters_valid=1") == std::string::npos ||
      text.find("q_wait_events=1") == std::string::npos ||
      text.find("q_full_wait_ms=17") == std::string::npos ||
      text.find("cpu_times_valid=1") == std::string::npos ||
      text.find("schema=3") == std::string::npos ||
      text.find("va_mapped_committed=") == std::string::npos ||
      text.find("vertex_freed_bytes=8192") == std::string::npos ||
      text.find("index_allocations=1") == std::string::npos) { return 6; }
  return 0;
}
