// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define NOMINMAX
#include "pagefile_shadow.h"
#include <fstream>
#include <iterator>
#include <string>

int main(int argc, char** argv) {
  l4d2_observation::memoryMonitoring = true;
  if (argc != 2) { return 1; }
  using namespace l4d2_shadow;
  l4d2_shadow::Metadata meta;
  meta.resourceId = 42;
  meta.creationTime = GetTickCount64();
  meta.type = Type::Texture2DLevel;
  meta.width = 64; meta.height = 64; meta.format = 21;
  meta.usage = kDynamic; meta.pool = 0; meta.mip = 0;
  const auto baselineBytes = l4d2_memory::surfaceBackingBytes.load();
  {
    PagefileShadow shadow, disabled;
    disabled.configureDiagnostics(meta, false);
    if (!disabled.acquire(4096, 0)) { return 2; }
    disabled.release(0);
    if (l4d2_pageblock::context.used || l4d2_pageblock::context.metadataRecords) { return 3; }
    shadow.configureDiagnostics(meta, true, true);
    auto* first = shadow.acquire(4096, 0);
    if (!first) { return 4; }
    shadow.observeLock(0, true);
    for (size_t i = 0; i < 4096; ++i) { first[i] = static_cast<uint8_t>(i); }
    shadow.release(0); shadow.observeUnlock(0);
    if (shadow.get() || l4d2_memory::surfaceBackingBytes != baselineBytes + 8192) { return 5; }
    auto* restored = shadow.acquire(4096, 0);
    if (!restored) { return 6; }
    shadow.observeLock(kReadonly, false);
    for (size_t i = 0; i < 4096; ++i) {
      if (restored[i] != static_cast<uint8_t>(i)) { return 7; }
    }
    if (shadow.acquire(4096, 0) != restored) { return 8; }
    shadow.observeLock(0, true);
    shadow.release(0); shadow.observeUnlock(kReadonly);
    if (!shadow.get()) { return 9; }
    shadow.release(0); shadow.observeUnlock(0);
    if (shadow.get() || l4d2_pageblock::context.engine.aliveBytes != 4096) { return 10; }
  }
  if (l4d2_memory::surfaceBackingBytes != baselineBytes || l4d2_memory::surfaceViewBudgetBytes ||
      l4d2_pageblock::context.metadataRecords || l4d2_pageblock::context.engine.aliveBytes) { return 11; }
  l4d2_pageblock::summary(true);
  std::ifstream file(argv[1]);
  const std::string text((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
  for (const char* expected : { "PB_CONFIG", "event=destroyed", "resource_id=42", "lock_count=3",
      "readonly_locks=1", "full_locks=2", "partial_locks=1", "PB_SUMMARY", "event=client-detach",
      "scope=destroyed total_resources=1 total_backing_bytes=4096", "readonly_bytes=4096", "PB_SIM_LRU",
      "simulation_only=1", "diagnostic_only=1", "alive_resources=0 alive_backing_bytes=0" }) {
    if (text.find(expected) == std::string::npos) { return 12; }
  }
  return 0;
}
