// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#pragma once
#include <cassert>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <new>
#include <unordered_map>
#include "memory_diagnostics.h"
#include "host_memory_diagnostics.h"
#include "overlay_presenter.h"
#include "color_backend_diagnostics.h"
#include "data_diagnostics.h"
#include "exception_diagnostics.h"
#include "api_wait_diagnostics.h"
#include "pageblock_residency.h"
#include "steam_activity_diagnostics.h"

using l4d2_observation::InputDemand;
inline InputDemand requestedInput;
inline unsigned detours = 0, inputSetup = 0, messages = 0;
inline bool apiLog = false;
enum class LogLevel { Trace, Debug };
struct Logger { static void info(const std::string&) { ++messages; } static void err(const std::string&) { ++messages; } };
struct LazyLogger {
  static bool isEnabled(LogLevel) { return apiLog; }
  static void trace(const std::string&) { ++messages; }
  static void debug(const std::string&) { ++messages; }
  template<typename Message> static void traceLazy(Message&&);
  template<typename Message> static void debugLazy(Message&&);
};
struct GlobalOptions {
  static bool getExposeRemixApi() { return requestedInput.remix; }
  static bool getLogApiCalls() { return apiLog; }
  static bool getLogAllCalls() { return false; }
};
namespace DI { enum ForwardPolicy { Never, Always }; }
struct ClientOptions {
  static bool getUseVanillaDxvk() { return !requestedInput.remix; }
  static bool getHookMessagePump() { return requestedInput.messagePump; }
  static bool getOverrideCustomWinHooks() { return requestedInput.customHooks; }
  static bool getDisableExclusiveInput() { return requestedInput.exclusiveInput; }
  static DI::ForwardPolicy getForwardDirectInputMousePolicy() { return requestedInput.mouseForward ? DI::Always : DI::Never; }
  static DI::ForwardPolicy getForwardDirectInputKeyboardPolicy() { return requestedInput.keyboardForward ? DI::Always : DI::Never; }
};
struct Config {
  template<typename T> static T getOption(const char* key, T fallback) {
    if (!std::strcmp(key, "server.presenterWindow")) { return static_cast<T>(requestedInput.presenterWindow); }
    if (!std::strcmp(key, "server.presenterInput")) { return static_cast<T>(requestedInput.presenterInput); }
    if (!std::strcmp(key, "server.useVanillaDxvk")) { return static_cast<T>(!requestedInput.remix); }
    if (!std::strcmp(key, "client.steamOverlayInput")) { return static_cast<T>(requestedInput.steamInput); }
    return fallback;
  }
};
inline void DetourTransactionBegin() { ++detours; }
inline void DetourTransactionCommit() { ++detours; }
inline void DetourUpdateThread(HANDLE) { ++detours; }
inline void AttachConventionalInput() { ++inputSetup; }
inline void DetachConventionalInput() { ++inputSetup; }
struct DirectInput8Hook { static void attach() { ++inputSetup; } static void detach() { ++inputSetup; } };
using DirectInput7Hook = DirectInput8Hook;
struct DirectInputForwarder { static void init() { ++inputSetup; } };
inline void _LogFunctionCall(const std::string&, void*) { ++messages; }
template<typename... Args> std::string format_string(const char*, Args...) { ++messages; return {}; }
#define TRUNCATE_HANDLE(type, value) reinterpret_cast<type>(static_cast<uintptr_t>(value))
inline std::unique_ptr<l4d2_overlay::Presenter> gOverlayPresenter;
inline HWND gOverlayGameWindow = nullptr;
inline l4d2_host_memory::ResourceInventory gResourceInventory(false);
inline uint64_t gProcessedHostCommands = 0;
inline std::unordered_map<uint32_t, void*> gpD3DDevices, gpD3DResources, gpD3DVolumes,
  gpD3DVertexDeclarations, gpD3DStateBlocks, gpD3DVertexShaders, gpD3DPixelShaders,
  gpD3DSwapChains, gpD3DQuery;

namespace WndProc { void sampleSteamInput(); }
inline HWND g_hwnd = nullptr;
inline WNDPROC g_gameWndProc = nullptr;
inline std::atomic<bool> g_steamKnown { false }, g_steamActive { false };
inline auto OrigGetWindowLongW = &GetWindowLongW;
inline auto OrigGetWindowLongA = &GetWindowLongA;
struct MessageChannel { bool canSend() { return false; } };
inline MessageChannel* gpRemixMessageChannel = nullptr;
struct RemixState { static bool isUIActive() { return false; } };
inline l4d2_overlay::InputDiagnostics& inputDiagnostics() {
  static l4d2_overlay::InputDiagnostics instance(false, "client", [](const char*) { ++messages; });
  return instance;
}

// The exported production GC handler uses the real registry/reclaim. Only its
// process-wide runtime accessor is supplied by the deterministic test fixture.
inline l4d2_residency::Context* controlContext = nullptr;
namespace l4d2_residency {
inline Context& context() { assert(controlContext); return *controlContext; }
inline bool setPolicy(Policy policy) { context().policy = policy; return true; }
}
