// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
static_assert(sizeof(l4d2_data::Resource) == sizeof(void*), "D3D resource diagnostic state is optional");
void* operator new(size_t bytes) {
  ++diagnostic_work::allocations;
  if (diagnostic_work::failAllocation) { throw std::bad_alloc(); }
  if (void* data = std::malloc(bytes ? bytes : 1)) { return data; }
  throw std::bad_alloc();
}
void operator delete(void* data) noexcept { std::free(data); }
void operator delete(void* data, size_t) noexcept { std::free(data); }
void* operator new[](size_t bytes) { return ::operator new(bytes); }
void operator delete[](void* data) noexcept { std::free(data); }
void operator delete[](void* data, size_t) noexcept { std::free(data); }

static void learnedLoop(const char* mode) {
  using namespace l4d2_readback;
  using namespace diagnostic_work;
  configuredPolicy = "learned-aggressive";
  configuredDb = std::string(mode) + ".db";
  std::filesystem::remove(configuredDb);
  retentionDiagnostics = std::strcmp(mode, "lg-off") != 0;
  failRetentionFile = !std::strcmp(mode, "retention-log-failure");
  failRetentionWrite = !std::strcmp(mode, "retention-write-failure");
  unsigned readbacks = 0, acknowledgements = 0;
  struct Backend {
    Request request;
    Layout layout;
    std::vector<uint8_t> bytes;
    explicit Backend(const Request& r) : request(r) {
      l4d2_readback::layout(r.width, r.height, r.format, layout);
      bytes.assign(layout.bytes, 0x71);
    }
    HRESULT descriptor(D3DSURFACE_DESC& desc) {
      desc = { static_cast<D3DFORMAT>(request.format), D3DRTYPE_SURFACE, request.usage,
        static_cast<D3DPOOL>(request.pool), D3DMULTISAMPLE_NONE, 0, request.width, request.height };
      return S_OK;
    }
    HRESULT synchronize(Response& response) { response.flushRequested = response.eventWait = 1; return S_OK; }
    HRESULT lock(D3DLOCKED_RECT& locked) { locked = { static_cast<INT>(layout.rowBytes), bytes.data() }; return S_OK; }
    HRESULT unlock() { return S_OK; }
  };
  for (unsigned run = 0; run < 2; ++run) {
    l4d2_retention::Runtime runtime;
    auto& learned = runtime.context;
    assert(learned.enabled && !learned.fallback && learned.db.valid());
    if (failRetentionFile || failRetentionWrite || !retentionDiagnostics) { assert(!learned.log); }
    if (!std::strcmp(mode, "retention-callback-failure")) {
      learned.log = [](const char*) { throw std::bad_alloc(); };
    }
    learned.exchange = [&](const Request& r, Temporary& temporary, Response& response, uint64_t& elapsed) -> HRESULT {
      const auto hr = temporary.create(r); if (FAILED(hr)) { return hr; }
      Backend backend(r);
      assert(runShared(backend, r, true, true));
      assert(temporary.wait(1000) == WAIT_OBJECT_0);
      response = temporary.response(); elapsed = 0;
      if (acknowledgement(r)) { ++acknowledgements; } else { ++readbacks; }
      return response.hresult;
    };
    PagefileShadow backing;
    l4d2_residency::Context residency;
    residency.policy = l4d2_residency::Policy::LearnedAggressive;
    residency.exchange = learned.exchange;
    // A failing GC log must not replace its intrinsic results either.
    if (!std::strcmp(mode, "retention-callback-failure")) {
      residency.log = [](const char*) { throw std::bad_alloc(); };
      residency.userLog = [](const char*) { throw std::bad_alloc(); };
    }
    const D3DSURFACE_DESC desc { D3DFMT_DXT1, D3DRTYPE_SURFACE, 0, D3DPOOL_MANAGED,
      D3DMULTISAMPLE_NONE, 0, 256, 256 };
    l4d2_retention::Parent parent(learned, 1, 256, 256, 1, D3DFMT_DXT1, 0, D3DPOOL_MANAGED, "fixture:1234", true);
    l4d2_residency::Entry entry(residency, backing, 2, desc);
    entry.type = l4d2_shadow::Type::Texture2DLevel;
    parent.attach(0, 2, backing);
    entry.learnedDecision = [&] { return parent.decision(0); };
    entry.learnedRecovery = [&](uint32_t flags, const RECT& rect) { return parent.beforeLock(0, flags, rect); };
    entry.learnedEvicted = [&](uint64_t bytes) { parent.noteEvicted(0, bytes); };
    entry.learnedFailure = [&](const char* reason) { parent.reclaimFailure(reason); };
    Layout layout; assert(l4d2_readback::layout(256, 256, D3DFMT_DXT1, layout));
    auto* original = backing.acquire(layout.bytes, 0); assert(original);
    std::memset(original, 0x71, layout.bytes);
    Digest digest; assert(hashBytes(original, layout.bytes, digest) == S_OK);
    backing.release(0); entry.uploaded(layout.bytes); parent.uploaded(0, true, digest, S_OK);
    assert(!learned.fallback && !l4d2_observation::memoryMonitoring);
    assert(parent.decision(0) == (run ? l4d2_residency::LearnedDecision::Keep : l4d2_residency::LearnedDecision::Evictable));
    const auto gc = l4d2_residency::RunPageBlockGc(residency, l4d2_residency::PageBlockGcMode::Learned);
    assert(gc.pageBlocksEvicted == (run ? 0u : 1u));
    if (!run) {
      assert(backing.recoveryMissing() && !backing.backingBytes() && learned.db.records() == 0);
      assert(entry.beforeLock(D3DLOCK_READONLY, RECT { 0, 0, 256, 256 }));
      assert(!backing.recoveryMissing() && parent.decision(0) == l4d2_residency::LearnedDecision::Keep);
      auto* restored = backing.acquire(layout.bytes, 0); assert(restored);
      for (unsigned i = 0; i < layout.bytes; ++i) { assert(restored[i] == 0x71); }
      backing.release(0);
    }
    assert(learned.db.records() == 1 && !learned.fallback);
    if (runtime.file != INVALID_HANDLE_VALUE) { CloseHandle(runtime.file); }
  }
  assert(readbacks == 1 && acknowledgements == 1);
  assert(!l4d2_api_wait::state && !bridge_exception::testHistoryState());
  assert(!threads && !l4d2_memory::nextSample && !l4d2_memory::surfaceBackingBytes);
  std::printf("%s: LG DB miss/eviction/Host recovery/KEEP promotion/persisted DB hit passed; fallback=0\n", mode);
}

int main(int argc, char** argv) {
  assert(argc == 2);
  using namespace diagnostic_work;
  if (!std::strcmp(argv[1], "observer-failure")) {
    std::atomic<unsigned> calls { 0 };
    l4d2_observation::Observer observer;
    observer = [&](const char*) { ++calls; throw std::bad_alloc(); };
    std::thread first([&] { for (unsigned i = 0; i < 1000; ++i) { observer("failed"); } });
    std::thread second([&] { for (unsigned i = 0; i < 1000; ++i) { observer("failed"); } });
    first.join(); second.join();
    const auto failures = calls.load(); assert(failures && !observer);
    observer("disabled"); assert(calls == failures);
    l4d2_overlay::InputDiagnostics input(true, "test", [](const char*) { throw std::bad_alloc(); });
    input.sample(nullptr, nullptr, false); assert(!input.enabled());
    std::puts("observer-failure: concurrent failure stops observation; callback storage remains stable");
    return 0;
  }
  if (!std::strcmp(argv[1], "init-failure")) {
    failDiagnosticFiles = true;
    assert(!l4d2_api_wait::initialize(true, "client") && !l4d2_api_wait::state);
    assert(!l4d2_data::initialize("client", "test"));
    assert(!l4d2_color::initialize("client", "test"));
    failDiagnosticFiles = false; failThread = true;
    assert(!l4d2_api_wait::initialize(true, "client") && !l4d2_api_wait::state);
    assert(!l4d2_data::initialize("client", "test"));
    assert(!l4d2_color::initialize("client", "test"));
    auto* core = l4d2_buffer::allocate(64, l4d2_memory::Kind::Vertex, true); assert(core); delete[] core;
    std::puts("init-failure: file/thread failures isolated; no published ApiWait state; core allocation succeeds");
    return 0;
  }
  if (!std::strcmp(argv[1], "lg-off") || std::strstr(argv[1], "retention-")) { learnedLoop(argv[1]); return 0; }
  if (!std::strcmp(argv[1], "allocation-failure")) {
    bridge_exception::initialize(nullptr, false, true);
    failAllocation = true;
    assert(!l4d2_api_wait::initialize(true, "client") && !l4d2_api_wait::state);
    bridge_exception::CallScope call("failed", 1); bridge_exception::recordCommand(true, bridge_exception::Queue::Device, 1, 1);
    assert(!bridge_exception::testHistoryState());
    l4d2_host_memory::ResourceInventory inventory;
    assert(!inventory.snapshot().registrations);
    l4d2_color::DiagnosticMap<unsigned, unsigned> map;
    map[1] = 7; assert(!map.size());
    assert(!l4d2_color::initialize("client", "test"));
    assert(!l4d2_data::initialize("client", "test"));
    bool failed = false;
    try { delete[] l4d2_buffer::allocate(64, l4d2_memory::Kind::Vertex, true); }
    catch (const std::bad_alloc&) { failed = true; }
    assert(failed && !l4d2_memory::nextSample);
    failAllocation = false;
    auto* core = l4d2_buffer::allocate(64, l4d2_memory::Kind::Index, true); assert(core && !core[0]); delete[] core;
    std::puts("allocation-failure: optional state unavailable; core allocation/exception contract preserved");
    return 0;
  }
  if (!std::strcmp(argv[1], "data-on")) {
    assert(l4d2_data::initialize("client", "test"));
    l4d2_data::Resource present; present.open(l4d2_data::Kind::Vertex, 1, 64, 64);
    assert(present.testHasState());
    failAllocation = true;
    l4d2_data::Resource absent; absent.open(l4d2_data::Kind::Index, 2, 64, 64);
    assert(!absent.testHasState()); failAllocation = false;
    std::puts("data-on: metadata lazy allocation and nonfatal allocation failure passed");
    return 0;
  }
  if (!std::strcmp(argv[1], "monitor-on")) {
    l4d2_observation::memoryMonitoring = true;
    l4d2_memory::sample(true, "positive-control");
    assert(scans && files && clocks);
    std::printf("monitor-on: scans=%u files=%u clocks=%u\n", scans.load(), files.load(), clocks.load());
    return 0;
  }
  assert(!l4d2_observation::crashHistory(false, false, false));
  assert(l4d2_observation::crashHistory(false, false, true));
  assert(!l4d2_observation::crashHistory(true, false, true));
  assert(l4d2_observation::crashHistory(true, true, false));
  if (!std::strcmp(argv[1], "crash-on")) {
    bridge_exception::initialize(nullptr, false, true);
    bridge_exception::CallScope call("positive-control", 7);
    bridge_exception::CommandScope command(bridge_exception::Queue::Device, 1, 7, "positive-control");
    bridge_exception::recordCommand(true, bridge_exception::Queue::Device, 1, 7);
    assert(bridge_exception::testTracking() >= 3);
    assert(bridge_exception::testHistoryState());
    std::printf("crash-on: history_entries=%u\n", bridge_exception::testTracking());
    return 0;
  }
  if (!std::strcmp(argv[1], "logging-on")) {
    apiLog = true;
    unsigned producers = 0;
    FunctionEntryExitLogger api("positive-control", nullptr);
    LazyLogger::traceLazy([&] { ++producers; return std::string(); });
    LazyLogger::debugLazy([&] { ++producers; return std::string(); });
    assert(producers == 2 && messages >= 3);
    LazyLogger::traceLazy([]() -> std::string { throw std::bad_alloc(); });
    std::printf("logging-on: evaluated_producers=%u\n", producers);
    return 0;
  }
  if (!std::strcmp(argv[1], "input-on")) {
    requestedInput.presenterWindow = true;
    DInputHookAttach(); DInputHookDetach();
    assert(detours == 6 && inputSetup == 7);
    std::printf("input-on: detour_calls=%u input_setup=%u\n", detours, inputSetup);
    return 0;
  }
  assert(!std::strcmp(argv[1], "off"));
  bridge_exception::initialize(nullptr, false, false);
  // Fatal handler setup is correctness work, outside the continuous-path count.
  scans = 0; files = 0; clocks = 0; threads = 0; hooks = 0; windows = 0; modules = 0; locks = 0; allocations = 0;
  l4d2_host_memory::Recorder dormantHost(false);
  assert(!dormantHost.due() && !dormantHost.sample({}));
  dormantHost.setGpuAdapter(1, 1);
  l4d2_color::DiagnosticMap<unsigned, unsigned> dormantColorMap;
  const auto beforeHistory = bridge_exception::testTracking();
  for (unsigned i = 0; i < 1000; ++i) {
    l4d2_memory::sample(true, "pageblock-gc-before");
    l4d2_memory::sample(false, "allocation");
    assert(!l4d2_memory::scanAddressSpace().complete);
    sampleHostMemory(true, "lifecycle"); sampleHostMemory();
    gResourceInventory.track(i, i, l4d2_host_memory::ResourceKind::Surface);
    gResourceInventory.erase(i);
    l4d2_queue::counters.waited(true, true); l4d2_queue::counters.signaled(true);
    l4d2_queue::counters.legacyWait(); l4d2_queue::counters.blocked(1);
    bridge_exception::CallScope call("disabled", i);
    bridge_exception::CommandScope command(bridge_exception::Queue::Device, 1, i, "disabled");
    command.setUid(i); bridge_exception::recordCommand(true, bridge_exception::Queue::Device, 1, i);
    assert(!l4d2_api_wait::initialize(false, "client"));
    l4d2_api_wait::ApiScope timing(l4d2_api_wait::Api::Present); l4d2_api_wait::queued();
    assert(l4d2_api_wait::backend([] { return S_OK; }) == S_OK);
    l4d2_data::Resource resource;
    resource.open(l4d2_data::Kind::Vertex, i, 1024, 1024);
    resource.lock(0, 32, 0, S_OK); resource.upload(32); resource.unlock(true); resource.read(32);
    assert(!resource.testHasState());
    l4d2_data::Temporary temporary(1024); l4d2_data::Dispatch dispatch(1, false);
    l4d2_data::Wire wire; wire.add(32, 32, true);
    l4d2_data::sent(1, false, wire, true, 4); l4d2_data::received(1, false);
    l4d2_data::stateSet(1, true, 32); l4d2_data::backend(1, false, 32, S_OK);
    assert(!wire.bytes);
    assert(dormantColorMap.find(i) == dormantColorMap.end() && !dormantColorMap.size());
    dormantColorMap.erase(i);
    l4d2_color::record("disabled"); l4d2_color::observe(1, l4d2_color::State::Render, 1, 1, S_OK);
    l4d2_color::Digest digest;
    l4d2_color::upload(1, 1, "disabled", 1, 21, 32, 32, 1, 128, 0, digest, S_OK, S_OK, true);
    l4d2_color::backendSnapshot(reinterpret_cast<IDirect3DDevice9*>(1), 1, gpD3DResources,
      gpD3DPixelShaders, gpD3DVertexShaders, "disabled");
    DInputHookAttach(); DInputHookDetach(); WndProc::sampleSteamInput();
    D3DPRESENT_PARAMETERS pp {}; pp.Windowed = TRUE;
    configureOverlayPresenter(pp); assert(overlayPresentWindow(nullptr) == nullptr);
    FunctionEntryExitLogger api("Long_D3D9_API_Name_That_Would_Require_A_String_Allocation", nullptr);
    LazyLogger::traceLazy([] { assert(false); return std::string(); });
    LazyLogger::debugLazy([] { assert(false); return std::string(); });
    l4d2_pageblock::created(nullptr, 4096);
    l4d2_pageblock::locked(nullptr, 0, true);
    l4d2_pageblock::unlocked(nullptr, 0);
    l4d2_pageblock::destroyed(nullptr);
    l4d2_pageblock::summary();
  }
  assert(!gOverlayPresenter && !detours && !inputSetup && !messages);
  const auto history = bridge_exception::testTracking();
  assert(history == beforeHistory && history == 0);
  assert(!gResourceInventory.snapshot().handles && !gResourceInventory.snapshot().registrations);
  assert(!l4d2_queue::counters.snapshot().waits && !l4d2_queue::counters.snapshot().signals);
  assert(!l4d2_api_wait::queuedCommands && !l4d2_api_wait::localStats && !l4d2_api_wait::top);
  assert(!l4d2_api_wait::state && !bridge_exception::testHistoryState());
  assert(!scans && !files && !clocks && !threads && !hooks && !windows && !modules && !locks && !allocations);
  for (const auto kind : { l4d2_memory::Kind::Vertex, l4d2_memory::Kind::Index }) {
    auto* shadow = l4d2_buffer::allocate(64, kind, true); assert(shadow);
    for (unsigned i = 0; i < 64; ++i) { assert(shadow[i] == 0); shadow[i] = static_cast<uint8_t>(i); }
    delete[] shadow; l4d2_memory::released(64, kind);
  }
  assert(!files && !clocks && !scans && !l4d2_memory::nextSample && !l4d2_memory::bytes[1] && !l4d2_memory::bytes[2]);
  // Real shadow allocation and GC still work with the monitor off. Intrinsic
  // mapped-view queries and user GC result timing are counted separately.
  for (const auto mode : { l4d2_residency::PageBlockGcMode::Aggressive, l4d2_residency::PageBlockGcMode::Force }) {
  const auto beforeScans = scans.load();
  PagefileShadow backing;
  auto* bytes = backing.acquire(4096, 65536); assert(bytes); bytes[0] = 71; backing.release(65536);
  l4d2_residency::Context context;
  D3DSURFACE_DESC desc { D3DFMT_A8R8G8B8, D3DRTYPE_SURFACE, 0, D3DPOOL_MANAGED, D3DMULTISAMPLE_NONE, 0, 32, 32 };
  l4d2_residency::Entry entry(context, backing, 1, desc);
  entry.uploaded(4096);
  context.exchange = [](const l4d2_readback::Request& request, l4d2_readback::Temporary&,
      l4d2_readback::Response& response, uint64_t&) {
    response.stage = l4d2_readback::Stage::Complete; response.hresult = S_OK;
    response.width = request.width; response.height = request.height;
    response.format = request.format; response.mip = request.mip;
    return S_OK;
  };
  controlContext = &context;
  l4d2_control::Request request;
  request.version = l4d2_control::kDetailedVersion;
  request.operation = l4d2_control::Operation::Gc;
  request.value = static_cast<uint32_t>(mode);
  l4d2_control::DetailedResponse response;
  assert(L4D2BridgePageBlockControl(&request, &response.base) == S_OK);
  const auto& gc = response.base;
  assert(gc.pageBlocksScanned == 1 && gc.pageBlocksEvicted == 1 && gc.backingBytesReleased == 4096);
  assert(response.hostAckWaitCount == 1 && !files && !threads);
  assert(!l4d2_memory::nextSample && !l4d2_memory::surfaceBackingBytes && !l4d2_memory::bytes[0]);
  assert(scans == beforeScans + 1); // actual mapped view, no whole-process diagnostic scan
  std::printf("off: diagnostic scans/files/clocks/threads/hooks/windows/modules/locks/allocations=0; GC evicted=%llu bytes=%llu intrinsic_view_queries=%u\n", gc.pageBlocksEvicted, gc.backingBytesReleased, scans.load());
  }
  return 0;
}
