// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
void* operator new(size_t bytes) {
  ++diagnostic_work::allocations;
  if (void* data = std::malloc(bytes ? bytes : 1)) { return data; }
  throw std::bad_alloc();
}
void operator delete(void* data) noexcept { std::free(data); }
void operator delete(void* data, size_t) noexcept { std::free(data); }

int main(int argc, char** argv) {
  assert(argc == 2);
  using namespace diagnostic_work;
  if (!std::strcmp(argv[1], "monitor-on")) {
    l4d2_observation::memoryMonitoring = true;
    l4d2_memory::sample(true, "positive-control");
    assert(scans && files && clocks);
    std::printf("monitor-on: scans=%u files=%u clocks=%u\n", scans.load(), files.load(), clocks.load());
    return 0;
  }
  assert(!l4d2_observation::crashHistory(false, false, false));
  assert(l4d2_observation::crashHistory(false, false, true));
  assert(!l4d2_observation::crashHistory(true, false, true));
  assert(l4d2_observation::crashHistory(true, true, false));
  if (!std::strcmp(argv[1], "crash-on")) {
    bridge_exception::initialize(nullptr, false, true);
    bridge_exception::CallScope call("positive-control", 7);
    bridge_exception::CommandScope command(bridge_exception::Queue::Device, 1, 7, "positive-control");
    bridge_exception::recordCommand(true, bridge_exception::Queue::Device, 1, 7);
    assert(bridge_exception::testTracking() >= 3);
    std::printf("crash-on: history_entries=%u\n", bridge_exception::testTracking());
    return 0;
  }
  if (!std::strcmp(argv[1], "logging-on")) {
    apiLog = true;
    unsigned producers = 0;
    FunctionEntryExitLogger api("positive-control", nullptr);
    LazyLogger::traceLazy([&] { ++producers; return std::string(); });
    LazyLogger::debugLazy([&] { ++producers; return std::string(); });
    assert(producers == 2 && messages >= 3);
    std::printf("logging-on: evaluated_producers=%u\n", producers);
    return 0;
  }
  if (!std::strcmp(argv[1], "input-on")) {
    requestedInput.presenterWindow = true;
    DInputHookAttach(); DInputHookDetach();
    assert(detours == 6 && inputSetup == 7);
    std::printf("input-on: detour_calls=%u input_setup=%u\n", detours, inputSetup);
    return 0;
  }
  assert(!std::strcmp(argv[1], "off"));
  bridge_exception::initialize(nullptr, false, false);
  // Fatal handler setup is correctness work, outside the continuous-path count.
  scans = 0; files = 0; clocks = 0; threads = 0; hooks = 0; windows = 0; modules = 0; locks = 0; allocations = 0;
  l4d2_host_memory::Recorder dormantHost(false);
  assert(!dormantHost.due() && !dormantHost.sample({}));
  dormantHost.setGpuAdapter(1, 1);
  const auto beforeHistory = bridge_exception::testTracking();
  for (unsigned i = 0; i < 1000; ++i) {
    l4d2_memory::sample(true, "pageblock-gc-before");
    l4d2_memory::sample(false, "allocation");
    assert(!l4d2_memory::scanAddressSpace().complete);
    sampleHostMemory(true, "lifecycle"); sampleHostMemory();
    gResourceInventory.track(i, i, l4d2_host_memory::ResourceKind::Surface);
    gResourceInventory.erase(i);
    l4d2_queue::counters.waited(true, true); l4d2_queue::counters.signaled(true);
    l4d2_queue::counters.legacyWait(); l4d2_queue::counters.blocked(1);
    bridge_exception::CallScope call("disabled", i);
    bridge_exception::CommandScope command(bridge_exception::Queue::Device, 1, i, "disabled");
    command.setUid(i); bridge_exception::recordCommand(true, bridge_exception::Queue::Device, 1, i);
    assert(!l4d2_api_wait::initialize(false, "client"));
    l4d2_api_wait::ApiScope timing(l4d2_api_wait::Api::Present); l4d2_api_wait::queued();
    assert(l4d2_api_wait::backend([] { return S_OK; }) == S_OK);
    l4d2_data::Resource resource;
    resource.open(l4d2_data::Kind::Vertex, i, 1024, 1024);
    resource.lock(0, 32, 0, S_OK); resource.upload(32); resource.unlock(true); resource.read(32);
    l4d2_data::Temporary temporary(1024); l4d2_data::Dispatch dispatch(1, false);
    l4d2_data::Wire wire; wire.add(32, 32, true);
    l4d2_data::sent(1, false, wire, true, 4); l4d2_data::received(1, false);
    l4d2_data::stateSet(1, true, 32); l4d2_data::backend(1, false, 32, S_OK);
    assert(!wire.bytes);
    l4d2_color::record("disabled"); l4d2_color::observe(1, l4d2_color::State::Render, 1, 1, S_OK);
    l4d2_color::Digest digest;
    l4d2_color::upload(1, 1, "disabled", 1, 21, 32, 32, 1, 128, 0, digest, S_OK, S_OK, true);
    l4d2_color::backendSnapshot(reinterpret_cast<IDirect3DDevice9*>(1), 1, gpD3DResources,
      gpD3DPixelShaders, gpD3DVertexShaders, "disabled");
    DInputHookAttach(); DInputHookDetach(); WndProc::sampleSteamInput();
    D3DPRESENT_PARAMETERS pp {}; pp.Windowed = TRUE;
    configureOverlayPresenter(pp); assert(overlayPresentWindow(nullptr) == nullptr);
    FunctionEntryExitLogger api("Long_D3D9_API_Name_That_Would_Require_A_String_Allocation", nullptr);
    LazyLogger::traceLazy([] { assert(false); return std::string(); });
    LazyLogger::debugLazy([] { assert(false); return std::string(); });
    l4d2_pageblock::created(nullptr, 4096);
    l4d2_pageblock::locked(nullptr, 0, true);
    l4d2_pageblock::unlocked(nullptr, 0);
    l4d2_pageblock::destroyed(nullptr);
    l4d2_pageblock::summary();
  }
  assert(!gOverlayPresenter && !detours && !inputSetup && !messages);
  const auto history = bridge_exception::testTracking();
  assert(history == beforeHistory && history == 0);
  assert(!gResourceInventory.snapshot().handles && !gResourceInventory.snapshot().registrations);
  assert(!l4d2_queue::counters.snapshot().waits && !l4d2_queue::counters.snapshot().signals);
  assert(!l4d2_api_wait::queuedCommands && !l4d2_api_wait::localStats && !l4d2_api_wait::top);
  assert(!scans && !files && !clocks && !threads && !hooks && !windows && !modules && !locks && !allocations);
  // Real shadow allocation and GC still work with the monitor off. Intrinsic
  // mapped-view queries and user GC result timing are counted separately.
  PagefileShadow backing;
  auto* bytes = backing.acquire(4096, 65536); assert(bytes); bytes[0] = 71; backing.release(65536);
  l4d2_residency::Context context;
  D3DSURFACE_DESC desc { D3DFMT_A8R8G8B8, D3DRTYPE_SURFACE, 0, D3DPOOL_MANAGED, D3DMULTISAMPLE_NONE, 0, 32, 32 };
  l4d2_residency::Entry entry(context, backing, 1, desc);
  entry.uploaded(4096);
  context.exchange = [](const l4d2_readback::Request& request, l4d2_readback::Temporary&,
      l4d2_readback::Response& response, uint64_t&) {
    response.stage = l4d2_readback::Stage::Complete; response.hresult = S_OK;
    response.width = request.width; response.height = request.height;
    response.format = request.format; response.mip = request.mip;
    return S_OK;
  };
  const auto gc = l4d2_residency::RunPageBlockGc(context, l4d2_residency::PageBlockGcMode::Aggressive);
  assert(gc.pageBlocksScanned == 1 && gc.pageBlocksEvicted == 1 && gc.backingBytesReleased == 4096);
  assert(gc.hostAckWaitCount == 1 && !files && !threads);
  assert(!l4d2_memory::nextSample && !l4d2_memory::surfaceBackingBytes && !l4d2_memory::bytes[0]);
  assert(scans == 1); // actual mapped view, no whole-process diagnostic scan
  std::printf("off: diagnostic scans/files/clocks/threads/hooks/windows/modules/locks/allocations=0; GC evicted=%llu bytes=%llu intrinsic_view_queries=%u\n", gc.pageBlocksEvicted, gc.backingBytesReleased, scans.load());
  return 0;
}
