// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#include <atomic>
#include <cstdio>
#include <thread>
#include <stdexcept>
namespace bridge_util { enum class Result { Success, Timeout, Failure }; }
#include "ipc_c32_message_queue.h"
using bridge_util::Result;
void check(bool condition) { if (!condition) throw std::runtime_error("C32 regression"); }
std::string name() { static unsigned i=0; return "c32-"+std::to_string(ldb_ipc_v2::processId())+"-"+std::to_string(++i); }
void write(ldb_c32::MessageQueue& q, unsigned uid, Commands::D3D9Command cmd=Commands::IDirect3DDevice9Ex_SetRenderState) {
  check(q.beginInline({cmd,0,0,123})); check(q.scalar(uid)); check(q.scalar(uid ^ 0xa5a5u)); check(q.finishInline(cmd));
}
void read(ldb_c32::MessageQueue& q, unsigned uid) {
  Result r; const auto h=q.pull(r,1000); check(r==Result::Success && h.pHandle==123);
  unsigned words=0;const auto* body=q.readInline(words);check(words==2 && body[0]==uid && body[1]==(uid^0xa5a5u));q.finishRead();
}
int main() {
  try {
    {
      const auto n=name();ldb_c32::MessageQueue w(n,nullptr,0,0,true), r(n,nullptr,0,0,false);
      for(unsigned i=0;i<31;i++) write(w,i);
      Result result;r.peek(result,2);check(result==Result::Timeout);
      write(w,31);for(unsigned i=0;i<32;i++) read(r,i);
      check(r.isEmpty());
      write(w,32);check(w.pending());check(w.due(UINT64_MAX));check(w.flush());read(r,32);
      write(w,33);write(w,34,Commands::IDirect3DDevice9Ex_Present);read(r,33);read(r,34);check(!w.pending());
      for(unsigned i=0;i<63;i++)check(w.beginInline({Commands::IDirect3DDevice9Ex_SetIndices,0,0,123}) && w.scalar(i) && w.finishInline(Commands::IDirect3DDevice9Ex_SetIndices));
      check(w.flush());for(unsigned i=0;i<63;i++){r.pull(result,1000);check(result==Result::Success);r.finishRead();}
      // Aborted scalar prefix is available for the legacy blob fallback.
      check(w.beginInline({Commands::IDirect3DDevice9Ex_SetRenderState,0,0,123}));check(w.scalar(71));
      unsigned count=0;const auto* prefix=w.inlinePrefix(count);check(count==1 && prefix[0]==71);w.abortInline();check(w.flush());check(prefix[0]==71);
      check(w.pushExternal({Commands::IDirect3DVertexBuffer9_Unlock,0,17,123}));
      const auto ext=r.pull(result,1000);check(result==Result::Success && !(ext.flags&ldb_c32::Inline) && ext.dataOffset==17);r.finishRead();
      // Shutdown, Reset and lifecycle operations must never retain a tail.
      for(auto cmd:{Commands::Bridge_Terminate,Commands::IDirect3DDevice9Ex_Reset,Commands::IDirect3DTexture9_Destroy,Commands::IDirect3DQuery9_GetData}) {
        write(w,72,cmd);check(!w.pending());read(r,72);
      }
    }
    {
      const auto n=name();ldb_c32::MessageQueue w(n,nullptr,0,0,true),r(n,nullptr,0,0,false);
      std::thread host([&]{for(unsigned i=0;i<100000;i++) read(r,i);});
      for(unsigned i=0;i<100000;i++) { write(w,i); }
      check(w.flush());host.join();
    }
    {
      const auto n=name();ldb_c32::MessageQueue w(n,nullptr,0,0,true),r(n,nullptr,0,0,false);
      std::atomic<bool> cancel{true};Result result;r.peek(result,1,&cancel);check(result==Result::Timeout);
      w.fault();check(!w.beginInline({Commands::IDirect3DDevice9Ex_SetIndices,0,0,123}));check(!w.flush());
    }
    std::puts("C32_PASS batches/boundaries/lazy/abort/external/wrap/cancel/fault");return 0;
  }catch(const std::exception& e){std::fprintf(stderr,"%s\n",e.what());return 1;}
}
