// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
using Device = Bridge<BridgeId::Device>;
using Module = Bridge<BridgeId::Module>;
void require(bool b, const char* text) { if(!b) {std::fprintf(stderr,"C32_BRIDGE_FAIL %s\n",text);std::exit(2);} }
constexpr unsigned Count=12000;
bool streamOnly=false, threaded=false;
template<class B> void transfer() {
  ULONG64 cyclesBefore=0,cyclesAfter=0;QueryThreadCycleTime(GetCurrentThread(),&cyclesBefore);
  const auto begin=std::chrono::steady_clock::now();
#ifdef REMIX_BRIDGE_CLIENT
  auto send = [&](unsigned i) {
    {
      ldb_c32::ApiEntryScope entry;
      if (!threaded && i%3==0) {
        typename B::Command c(Commands::IDirect3DDevice9Ex_SetRenderState, i%17,0,bridge_data::fields(i, i^0x1234u));
        require(c.finish()==Result::Success,"known inline finish");
      } else {
        typename B::Command c(Commands::IDirect3DDevice9Ex_SetRenderState,threaded ? 0 : i%17);
        if (threaded) { i=static_cast<unsigned>(c.get_uid()); }
        c.send_many(i,i^0x1234u);
        if(!streamOnly && i%3==2) {std::array<uint8_t,512> blob{};blob.fill(static_cast<uint8_t>(i));c.send_data(blob.size(),blob.data());}
        require(c.finish()==Result::Success,"generic finish");
      }
    }
    if (!threaded && i == 1) {
      Sleep(2);
      { ldb_c32::ApiEntryScope localGetterEntry; require(!B::getWriterChannel().commands->pending(), "local getter lazy flush"); }
    }
    if(!threaded && i%101==0) {
      require(B::waitForCommand(Commands::Bridge_Response,2000,nullptr,true,i)==Result::Success,"RPC wait");
      require(B::get_data()==i,"RPC payload");B::pop_front();
    }
  };
  if (threaded) {
    std::vector<std::thread> writers;
    for(unsigned t=0;t<4;++t) {writers.emplace_back([&] {for(unsigned i=0;i<Count/4;i++)send(i);});}
    for(auto& writer:writers)writer.join();
  } else {for(unsigned i=0;i<Count;i++)send(i);}
  require(B::flushCommands(),"final flush");
#else
  const uint8_t* retained=nullptr;uint64_t pinned=0;
  for(unsigned i=0;i<Count;i++) {
    require(B::waitForCommand(Commands::Bridge_Any,2000)==Result::Success,"request wait");
    const auto h=B::pop_front();require(h.pHandle==(threaded ? 0 : i%17),"resource order");
    require(B::get_data()==i,"UID");
    if(!threaded && i%3==0) {const auto p=B::template get_packet<2>(false);require(p.fields[0]==i && p.fields[1]==(i^0x1234u),"known body");}
    else {require(B::get_data()==i && B::get_data()==(i^0x1234u),"generic body");}
    if(!streamOnly && i%3==2) {
      if(retained) {for(unsigned j=0;j<512;j++)require(retained[j]==static_cast<uint8_t>(i-3),"retained Lock contents");B::unpinRead(7);}
      B::pinRead(7);void* ptr=nullptr;require(B::get_data(&ptr)==512,"blob length");
      for(unsigned j=0;j<512;j++)require(static_cast<uint8_t*>(ptr)[j]==static_cast<uint8_t>(i),"every blob byte");
      retained=static_cast<const uint8_t*>(ptr);
    }
    bool inlineUnpin = !streamOnly && i%9==4;
    if (inlineUnpin) {
      require(retained!=nullptr,"inline unpin lease");
      for(unsigned j=0;j<512;j++)require(retained[j]==static_cast<uint8_t>(i-2),"inline unpin every byte");
      B::unpinRead(7);retained=nullptr;
    }
    B::end_read_data();
    if (inlineUnpin) {require(B::getReaderChannel().control->consumed.load()==B::getReaderChannel().data->cursor(),"inline unpin failed to advance Data Ring credits");}
    if(!streamOnly && i%3==2) {pinned=B::getReaderChannel().control->consumed.load();}
    else if(retained) {require(B::getReaderChannel().control->consumed.load()==pinned,"inline command advanced pinned data");}
    if(!threaded && i%101==0) {typename B::Command reply(Commands::Bridge_Response,i);reply.send_data(i);require(reply.finish()==Result::Success,"reply finish");}
    if(i%1024==0)Sleep(1);
  }
  B::destroyReadPins(7);
#endif
  QueryThreadCycleTime(GetCurrentThread(),&cyclesAfter);
  const auto ns=std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::steady_clock::now()-begin).count();
  std::printf("C32_TIMING cycles=%llu commands=%u wall_ns=%lld threaded=%u\n",static_cast<unsigned long long>(cyclesAfter-cyclesBefore),Count,static_cast<long long>(ns),threaded?1u:0u);
}
template<class B> void uploadWrap() {
  constexpr unsigned Bytes = 80000;
  for (unsigned i = 0; i < 32; ++i) {
#ifdef REMIX_BRIDGE_CLIENT
    // The first upload positions the ring near its middle. The Surface layout
    // then has UID + RECT blob + flags + format + pitch before a large blob.
    { std::vector<uint8_t> bytes(68000, static_cast<uint8_t>(i));
      if (i % 2) {
        typename B::Command c(Commands::IDirect3DDevice9Ex_SetRenderState, i, 0, bridge_data::payload(bytes.size(), bytes.data()));
        require(c.finish()==Result::Success,"known-packet wrap positioning upload");
      } else {
        typename B::Command c(Commands::IDirect3DDevice9Ex_SetRenderState, i);
        c.send_data(bytes.size(), bytes.data()); require(c.finish()==Result::Success,"wrap positioning upload");
      } }
    { typename B::Command c(Commands::IDirect3DSurface9_UnlockRect, i);
      const std::array<uint32_t,4> rect {{0,0,100,200}};
      c.send_data(sizeof(rect), rect.data()); c.send_many(0,21,400);
      auto* data=c.begin_data_blob(Bytes);require(data!=nullptr,"Surface wrap blob reservation");
      std::memset(data,static_cast<uint8_t>(i^0x5a),Bytes);c.end_data_blob();
      require(c.finish()==Result::Success,"Surface wrap finish"); }
#else
    require(B::waitForCommand(Commands::Bridge_Any,2000)==Result::Success,"positioning wait");
    auto h=B::pop_front();require(h.command==Commands::IDirect3DDevice9Ex_SetRenderState && h.pHandle==i,"positioning header");
    require(B::get_data()==i*2,"positioning UID");void* data=nullptr;require(B::get_data(&data)==68000,"positioning length");
    for(unsigned j=0;j<68000;++j)require(static_cast<uint8_t*>(data)[j]==static_cast<uint8_t>(i),"positioning bytes");B::end_read_data();
    require(B::waitForCommand(Commands::Bridge_Any,2000)==Result::Success,"Surface wrap wait");
    h=B::pop_front();require(h.command==Commands::IDirect3DSurface9_UnlockRect && h.pHandle==i,"padding reached dispatch");
    require(B::get_data()==i*2+1,"Surface UID changed by padding");
    require(B::get_data(&data)==16,"RECT length");const std::array<uint32_t,4> rect {{0,0,100,200}};
    require(std::memcmp(data,rect.data(),16)==0,"relocated RECT");
    require(B::get_data()==0 && B::get_data()==21 && B::get_data()==400,"relocated scalar prefix");
    require(B::get_data(&data)==Bytes,"Surface bytes length");
    for(unsigned j=0;j<Bytes;++j)require(static_cast<uint8_t*>(data)[j]==static_cast<uint8_t>(i^0x5a),"Surface upload bytes");
    B::end_read_data();
#endif
  }
  std::puts("C32_SURFACE_WRAP_PASS 32 large uploads, every byte, padding hidden from dispatch");
}
#ifdef REMIX_BRIDGE_CLIENT
int faultCase(const std::wstring& mode) {
  GlobalOptions::timeout=2;GlobalOptions::retries=2;
  const size_t memory=256+256*sizeof(Header)+32768*sizeof(uint32_t);
  WriterChannel w("FaultForward",memory,256,32768);ReaderChannel r("FaultReply",memory,256,32768);Device::install(&w,&r);
  if (mode==L"abort") {
    Device::Command c(Commands::IDirect3DDevice9Ex_SetRenderState);
    c.send_data(7);unsigned before=0;w.commands->inlinePrefix(before);
    c.abort();c.send_data(99);unsigned after=0;w.commands->inlinePrefix(after);
    require(before==after,"write after abort");require(c.finish()!=Result::Success,"abort accepted");
  } else {
    {Device::Command c(Commands::IDirect3DDevice9Ex_SetRenderState);c.send_data(7);require(c.finish()==Result::Success,"tail prepare");}
    require(Device::waitForCommand(Commands::Bridge_Response,1,nullptr,true,0)!=Result::Success,"missing reply accepted");
  }
  require(!gbBridgeRunning.load() && !Device::healthy(),"failure did not stop bridge");
  {Device::Command c(Commands::IDirect3DDevice9Ex_SetRenderState);c.send_data(99);require(c.finish()!=Result::Success,"post-fault command accepted");}
  std::puts("C32_PRODUCTION_FAIL_CLOSED_PASS");return 0;
}
#endif
int wmain(int argc,wchar_t** argv) {
  try {
#ifdef REMIX_BRIDGE_CLIENT
    if (argc==2) {return faultCase(argv[1]);}
#endif
    require(argc==3,"GUID/mode argument");
    streamOnly=std::wstring(argv[2])==L"stream";threaded=std::wstring(argv[2])==L"threaded";
    require(gUniqueIdentifier.setGuid(&argv[1]),"GUID valid");
    const size_t memory=256+256*sizeof(Header)+32768*sizeof(uint32_t);
#ifdef REMIX_BRIDGE_CLIENT
    WriterChannel dw("DeviceForward",memory,256,32768),mw("ModuleForward",memory,256,32768);
    ReaderChannel dr("DeviceReply",memory,256,32768),mr("ModuleReply",memory,256,32768);
#else
    ReaderChannel dr("DeviceForward",memory,256,32768),mr("ModuleForward",memory,256,32768);
    WriterChannel dw("DeviceReply",memory,256,32768),mw("ModuleReply",memory,256,32768);
#endif
    Device::install(&dw,&dr);Module::install(&mw,&mr);
    if (std::wstring(argv[2])==L"upload-wrap") { uploadWrap<Device>();uploadWrap<Module>(); }
    else { transfer<Device>();transfer<Module>(); }
    std::puts("C32_BRIDGE_PASS inline/generic/known/blob/RPC/retained-Lock/Device/Module/wrap/slow-host");return 0;
  } catch (...) {std::puts("C32_BRIDGE_EXCEPTION");return 3;}
}
