// SPDX-License-Identifier: MIT
// Copyright (c) 2026 yeyunyyds.
// All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
#define LDB_IPC_V2_TEST
#define LDB_IPC_V2_METRICS
#include "../../experiments/ipc-v2/transport.h"
#include <array>
#include <cstdio>
#include <cstdlib>
#include <mutex>
#include <thread>
#include <vector>
#ifndef _WIN32
#include <sys/wait.h>
#endif
using namespace ldb_ipc_v2;
void require(bool value, const char* description) {
  if (!value) { throw std::runtime_error(description); }
}
std::string uniqueName() {
  static unsigned counter = 0;
  return std::to_string(processId()) + "-" + std::to_string(milliseconds()) + "-" + std::to_string(++counter);
}
void delay(uint32_t ms) { std::this_thread::sleep_for(std::chrono::milliseconds(ms)); }
class Process {
#ifdef _WIN32
  PROCESS_INFORMATION m_process {};
#else
  pid_t m_pid = -1;
#endif
public:
  Process(const std::string& exe, const std::string& name, const std::string& mode,
      uint32_t kind, uint32_t direction, uint32_t spins) {
#ifdef _WIN32
    std::string command = "\"" + exe + "\" --child " + name + " " + mode + " "
      + std::to_string(kind) + " " + std::to_string(direction) + " " + std::to_string(spins);
    STARTUPINFOA startup {}; startup.cb = sizeof(startup);
    require(CreateProcessA(nullptr, command.data(), nullptr, nullptr, FALSE, 0, nullptr, nullptr,
      &startup, &m_process) != FALSE, "CreateProcess");
#else
    m_pid = fork(); require(m_pid >= 0, "fork");
    if (!m_pid) {
      const auto k = std::to_string(kind), d = std::to_string(direction), s = std::to_string(spins);
      execl(exe.c_str(), exe.c_str(), "--child", name.c_str(), mode.c_str(), k.c_str(), d.c_str(), s.c_str(), nullptr);
      _exit(127);
    }
#endif
  }
  ~Process() {
#ifdef _WIN32
    if (m_process.hProcess) {
      if (WaitForSingleObject(m_process.hProcess, 0) == WAIT_TIMEOUT) {
        TerminateProcess(m_process.hProcess, 99); WaitForSingleObject(m_process.hProcess, 1000);
      }
      CloseHandle(m_process.hThread); CloseHandle(m_process.hProcess);
    }
#else
    if (m_pid > 0) { kill(m_pid, SIGKILL); waitpid(m_pid, nullptr, 0); }
#endif
  }
  int wait() {
#ifdef _WIN32
    require(WaitForSingleObject(m_process.hProcess, 15000) == WAIT_OBJECT_0, "child deadline");
    DWORD code = 0; GetExitCodeProcess(m_process.hProcess, &code); return static_cast<int>(code);
#else
    const uint64_t start = milliseconds();
    int status = 0;
    while (waitpid(m_pid, &status, WNOHANG) == 0) {
      require(milliseconds() - start < 15000, "child deadline"); delay(1);
    }
    m_pid = -1; return WIFEXITED(status) ? WEXITSTATUS(status) : 99;
#endif
  }
};

void localTests() {
  Config c; c.blockCount = 2; c.blockBytes = 64;
  {
    Channel channel(uniqueName(), c, true); Writer writer(channel, 20); Reader reader(channel, 5);
    // Zero length and exact block capacity, uncommitted visibility and rollback.
    auto empty = writer.begin(6, 9, 0, 4); require(empty.blob(nullptr, 0), "zero blob");
    require(empty.finish(false) == Result::Success, "zero commit");
    require(channel.shared().producer.published.load() == 0, "unpublished block");
    require(reader.consume([](Message&) { return true; }) == Result::Timeout, "unpublished invisible");
    require(writer.flush() == Result::Success, "flush");
    require(reader.consume([](Message& m) {
      const uint8_t* p = nullptr; uint32_t n = 1;
      return m.header.command == 6 && m.blob(p, n) && n == 0;
    }) == Result::Success, "zero decode");
    auto failed = writer.begin(6, 9, 1, 4); require(failed.scalar(7), "scalar");
    require(!failed.scalar(8), "encoder bound");
    require(failed.finish() == Result::Invalid, "abort oversize");
    require(channel.shared().producer.published.load() == 1, "failure no publication");
    require(!writer.begin(6, 9, 2, UINT32_MAX).valid(), "overflow");
    auto exact = writer.begin(6, 9, 3, 40);
    for (uint32_t i = 0; i < 10; ++i) { require(exact.scalar(i), "full scalar"); }
    require(exact.finish() == Result::Success, "exact full block");
    require(reader.consume([](Message& m) {
      for (uint32_t i = 0; i < 10; ++i) { uint32_t v; if (!m.scalar(v) || v != i) { return false; } }
      return true;
    }) == Result::Success, "full decode");
    auto aborted = writer.begin(6, 9, 4, 4); require(aborted.scalar(1), "partial");
    require(writer.flush() == Result::Invalid, "open record not published"); aborted.abort();
    require(writer.close() == Result::Success, "close");
    require(reader.consume([](Message&) { return true; }) == Result::Closed, "eof");
  }
  {
    const auto name = uniqueName(); Channel channel(name, c, true);
    Config wrong = c; ++wrong.build[0]; bool refused = false;
    try { Channel peer(name, wrong, false); } catch (const std::exception&) { refused = true; }
    require(refused, "build mismatch");
    ++channel.shared().version; refused = false;
    try { Channel peer(name, c, false); } catch (const std::exception&) { refused = true; }
    require(refused, "protocol mismatch");
  }
  {
    Channel channel(uniqueName(), c, true); Writer writer(channel, 20);
    for (unsigned i = 0; i < 2; ++i) {
      auto record = writer.begin(6, 0, i, 0); require(record.finish() == Result::Success, "fill two blocks");
    }
    const auto start = milliseconds(); require(!writer.begin(6, 0, 3, 0).valid(), "bounded full");
    require(milliseconds() - start < 500 && channel.shared().fault.load() == static_cast<uint32_t>(Fault::Timeout), "poison on deadline");
    require(!writer.begin(6, 0, 4, 0).valid(), "post fault refused");
    require(channel.shared().producer.published.load() == 2, "no extra header after timeout");
  }
  {
    Channel channel(uniqueName(), c, true); Reader reader(channel, 20);
    Event::failNextWait = true;
    require(reader.consume([](Message&) { return true; }) == Result::SystemFailure, "OS failure");
    require(!channel.healthy(), "OS failure poison");
  }
  {
    Channel channel(uniqueName(), c, true); Writer writer(channel); Reader reader(channel);
    auto record = writer.begin(6, 0, 1, 4); record.scalar(3); record.finish();
    auto& b = channel.block(0); auto* h = reinterpret_cast<Record*>(channel.data(b)); h->bytes = UINT32_MAX;
    require(reader.consume([](Message&) { return true; }) == Result::Fault, "reject forged length");
    require(channel.shared().consumer.completed.load() == 0, "failed handler no credit");
  }
  {
    Channel channel(uniqueName(), c, true);
    Metrics metrics;
    require(channel.wait(false, [&]() { return channel.shared().messages.armed.load() == 1; }, 20, 0, 0, metrics) == Result::Success,
      "register then recheck progress");
    require(metrics.waits == 0 && !channel.shared().messages.armed.load(), "no wait after registration progress");
  }
  {
    Channel channel(uniqueName(), c, true); Writer writer(channel);
    auto reader = std::make_unique<Reader>(channel);
    auto record = writer.begin(6, 0, 1, 4); require(record.scalar(9), "pending before close");
    reader.reset();
    require(record.finish() == Result::Fault, "cooperative close refuses pending record");
    require(channel.shared().producer.published.load() == 0, "closed peer no publication");
  }
  {
    Channel channel(uniqueName(), c, true); Writer writer(channel); Reader reader(channel);
    auto record = writer.begin(6, 0, 1, 4); require(record.blob(nullptr, 0), "blob corruption fixture"); record.finish();
    auto& b = channel.block(0); const uint32_t bad = UINT32_MAX;
    std::memcpy(channel.data(b) + sizeof(Record), &bad, sizeof(bad));
    require(reader.consume([](Message& m) { const uint8_t* p; uint32_t n; return m.blob(p, n); }) == Result::Fault,
      "reject overflow blob length");
    require(channel.shared().consumer.completed.load() == 0, "corrupt blob no reclaim");
  }
  {
    Channel channel(uniqueName(), c, true); Writer writer(channel); Reader reader(channel);
    auto record = writer.begin(6, 0, 1, 0); record.finish();
    require(reader.consume([](Message&) -> bool { throw std::runtime_error("backend failure"); }) == Result::Fault,
      "throwing handler stops channel");
    require(!writer.begin(6, 0, 2, 0).valid(), "no submission after backend failure");
  }
  // Map-exit release/recreate model: this tests ordered transport of versions,
  // not D3D9 Lock semantics or a versioned upload allocator.
  {
    Config lifecycle = c; lifecycle.blockBytes = 512;
    Channel channel(uniqueName(), lifecycle, true); Writer writer(channel); Reader reader(channel);
    uint32_t hostGeneration = 0; bool live = false;
    for (uint32_t map = 1; map <= 1000; ++map) {
      for (uint16_t command : { uint16_t(1), uint16_t(2), uint16_t(3) }) {
        auto record = writer.begin(command, 1, map, 4, 0, map); require(record.scalar(map), "lifecycle version");
        require(record.finish(false) == Result::Success, "lifecycle batch");
      }
      require(writer.flush() == Result::Success, "map boundary flush");
      require(reader.consume([&](Message& m) {
        uint32_t version;
        if (!m.scalar(version) || version != map || m.header.generation != map || m.header.resource != 1) { return false; }
        if (m.header.command == 1) { if (live || map <= hostGeneration) { return false; } hostGeneration = map; live = true; }
        else if (m.header.command == 2) { if (!live || hostGeneration != map) { return false; } }
        else if (m.header.command == 3) { if (!live || hostGeneration != map) { return false; } live = false; }
        else { return false; }
        return true;
      }) == Result::Success, "destroy before reuse across map epochs");
    }
    require(!live && hostGeneration == 1000, "map model final state");
  }
  std::puts("IPC_V2_LOCAL_PASS");
}

Config processConfig(uint32_t kind, uint32_t direction) {
  Config c; c.blockCount = 4; c.blockBytes = 512; c.kind = kind; c.direction = direction; return c;
}
Config blobConfig(uint32_t kind) {
  Config c; c.kind = kind; c.blockCount = 2; c.blockBytes = aligned(2 * 1024 * 1024 + 36, 64); return c;
}
bool validateBlob(Message& m, uint32_t expected, const uint8_t*& data, uint32_t& bytes) {
  uint32_t sequence;
  if (m.header.command != 5 || m.header.uid != expected || !m.scalar(sequence) || sequence != expected || !m.blob(data, bytes)) { return false; }
  for (uint32_t i = 0; i < bytes; ++i) { if (data[i] != static_cast<uint8_t>(expected + i)) { return false; } }
  return true;
}
int blobChild(const std::string& name, uint32_t kind, uint32_t spins) {
  Config c = blobConfig(kind); Channel forward(name, c, false);
  c.direction = 1; Channel reverse(name + "-reply", c, false);
  Reader reader(forward, 5000, spins); Writer writer(reverse, 5000, spins);
  for (uint32_t i = 0; i < 16; ++i) {
    const uint32_t sequence = UINT32_MAX - 7 + i;
    require(reader.consume([&](Message& m) {
      const uint8_t* data = nullptr; uint32_t bytes = 0;
      if (!validateBlob(m, sequence, data, bytes)) { return false; }
      auto reply = writer.begin(5, 100, sequence, 8 + aligned(bytes), 0, 1);
      return reply.scalar(sequence) && reply.blob(data, bytes) && reply.finish() == Result::Success;
    }) == Result::Success, "full-byte request and reverse encode");
  }
  return 0;
}
void crossProcessBlobs(const std::string& host, uint32_t kind, uint32_t spins) {
  const auto name = uniqueName(); Config c = blobConfig(kind); Channel forward(name, c, true);
  c.direction = 1; Channel reverse(name + "-reply", c, true);
  Writer writer(forward, 5000, spins); Reader reader(reverse, 5000, spins);
  Process process(host, name, "blob", kind, 0, spins);
  const std::array<uint32_t, 4> sizes { 0, 65536, 524288, 2097152 };
  std::vector<uint8_t> payload(sizes.back());
  for (uint32_t i = 0; i < 16; ++i) {
    const uint32_t sequence = UINT32_MAX - 7 + i, bytes = sizes[i % sizes.size()];
    for (uint32_t j = 0; j < bytes; ++j) { payload[j] = static_cast<uint8_t>(sequence + j); }
    auto request = writer.begin(5, 100, sequence, 8 + aligned(bytes), 1, 1);
    require(request.scalar(sequence) && request.blob(payload.data(), bytes) && request.finish() == Result::Success, "large request");
    require(reader.consume([&](Message& m) {
      const uint8_t* data = nullptr; uint32_t length = 0;
      return validateBlob(m, sequence, data, length) && length == bytes;
    }) == Result::Success, "full-byte Host to Client blob");
  }
  require(writer.close() == Result::Success && process.wait() == 0, "large peer completion");
  std::printf("IPC_V2_BIDIRECTIONAL_BLOB_PASS kind=%u spins=%u max_bytes=2097152 records=32\n", kind, spins);
}
bool checkPacket(Message& m, uint32_t expected, uint32_t& flags) {
  uint32_t seq = 0, size = 0; const uint8_t* p = nullptr; uint32_t n = 0;
  if (m.header.command != 6 || m.header.uid != expected || !m.scalar(seq) || seq != expected
      || !m.scalar(size) || !m.blob(p, n) || n != size || n > 128) { return false; }
  for (uint32_t i = 0; i < n; ++i) { if (p[i] != static_cast<uint8_t>(expected + i)) { return false; } }
  flags = m.header.flags; return true;
}
int child(const std::string& name, const std::string& mode, uint32_t kind, uint32_t direction, uint32_t spins) {
  if (mode == "blob") { return blobChild(name, kind, spins); }
  Config c = processConfig(kind, direction);
  Channel forward(name, c, false);
  c.direction ^= 1; Channel reverse(name + "-reply", c, false);
  Reader reader(forward, 5000, spins); Writer response(reverse, 5000, spins);
  if (mode == "exit") { std::_Exit(23); }
  uint32_t expected = UINT32_MAX - 17;
  while (true) {
    const auto status = reader.consume([&](Message& m) {
      uint32_t flags = 0;
      if (!checkPacket(m, expected, flags)) { return false; }
      if (mode == "slow") { delay(1); }
      if (flags & 1) {
        auto reply = response.begin(6, 0, expected, 4);
        if (!reply.scalar(expected) || reply.finish() != Result::Success) { return false; }
      }
      ++expected; return true;
    });
    if (status == Result::Closed) { break; }
    require(status == Result::Success, "child ordered consumption");
  }
  require(response.close() == Result::Success, "reply close");
  return 0;
}

void crossProcess(const std::string& host, uint32_t kind, uint32_t direction, uint32_t spins,
    const std::string& mode, bool multithread) {
  const auto name = uniqueName(); Config c = processConfig(kind, direction);
  Channel forward(name, c, true); c.direction ^= 1; Channel reverse(name + "-reply", c, true);
  // Exercise uint32 sequence rollover with a bounded number of live blocks.
  forward.shared().producer.published = UINT32_MAX - 2;
  forward.shared().consumer.completed = UINT32_MAX - 2;
  Writer writer(forward, 5000, spins); Reader replies(reverse, 5000, spins);
  Process process(host, name, mode, kind, direction, spins);
  if (mode == "exit") {
    require(process.wait() == 23, "abrupt peer exit");
    for (unsigned i = 0; i < 4; ++i) { auto e = writer.begin(6, 0, i, 0); require(e.finish() == Result::Success, "fill exited ring"); }
    const auto start = milliseconds(); require(!writer.begin(6, 0, 5, 0).valid(), "peer exit stops writes");
    require(milliseconds() - start < 1000, "peer exit wait bounded"); return;
  }
  std::mutex mutex;
  uint32_t seq = UINT32_MAX - 17;
  const uint32_t perThread = mode == "slow" ? 100 : multithread ? 2500 : 20000;
  auto send = [&]() {
    for (uint32_t i = 0; i < perThread; ++i) {
      std::lock_guard<std::mutex> lock(mutex);
      std::array<uint8_t, 128> payload {};
      const uint32_t bytes = seq % 129;
      for (uint32_t j = 0; j < bytes; ++j) { payload[j] = static_cast<uint8_t>(seq + j); }
      const bool rpc = i % 257 == 0;
      auto e = writer.begin(6, 100, seq, 12 + aligned(bytes), rpc ? 1 : 0, 1);
      require(e.valid() && e.scalar(seq) && e.scalar(bytes) && e.blob(payload.data(), bytes), "packet encode");
      require(e.finish(rpc || i % 7 == 6) == Result::Success, "packet commit");
      if (rpc) {
        uint32_t returned = 0;
        require(replies.consume([&](Message& m) { return m.header.uid == seq && m.scalar(returned) && returned == seq; })
          == Result::Success, "synchronous response");
      }
      ++seq;
    }
  };
  if (multithread) {
    std::array<std::thread, 4> threads;
    for (auto& t : threads) { t = std::thread(send); }
    for (auto& t : threads) { t.join(); }
  } else { send(); }
  require(writer.close() == Result::Success, "final flush close");
  require(process.wait() == 0, "child success");
  require(writer.metrics.records == static_cast<uint32_t>(seq - (UINT32_MAX - 17)), "record count");
  require(forward.shared().consumer.completed.load() == forward.shared().producer.published.load(), "all blocks returned");
  std::printf("IPC_V2_CROSS_PASS kind=%u direction=%u spins=%u mode=%s threads=%u records=%llu blocks=%llu waits=%llu bits=%u\n",
    kind, direction, spins, mode.c_str(), multithread ? 4u : 1u,
    static_cast<unsigned long long>(writer.metrics.records), static_cast<unsigned long long>(writer.metrics.blocks),
    static_cast<unsigned long long>(writer.metrics.waits), static_cast<unsigned>(sizeof(void*) * 8));
}
int main(int argc, char** argv) {
  try {
    // child arguments are program + --child + name/mode/kind/direction/spins.
    if (argc == 7 && std::string(argv[1]) == "--child") {
      return child(argv[2], argv[3], static_cast<uint32_t>(std::stoul(argv[4])),
        static_cast<uint32_t>(std::stoul(argv[5])), static_cast<uint32_t>(std::stoul(argv[6])));
    }
    const std::string host = argc == 3 && std::string(argv[1]) == "--host" ? argv[2] : argv[0];
    localTests();
    for (uint32_t spins : { 0u, 128u }) {
      for (uint32_t kind : { 1u, 2u }) {
        crossProcessBlobs(host, kind, spins);
        for (uint32_t direction : { 0u, 1u }) { crossProcess(host, kind, direction, spins, "normal", false); }
        crossProcess(host, kind, 0, spins, "normal", true);
      }
      crossProcess(host, 1, 0, spins, "slow", false);
    }
    crossProcess(host, 1, 0, 0, "exit", false);
    std::puts("IPC_V2_NATIVE_PASS"); return 0;
  } catch (const std::exception& e) { std::fprintf(stderr, "IPC_V2_FAIL %s\n", e.what()); return 1; }
}
