# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$receipt = Get-Content "$root/work/ipc-c32-build.json" -Raw | ConvertFrom-Json
$env:L4D2_BRIDGE_BUILD_ID = $receipt.build_id
Push-Location "$root/.deps/dxvk-remix/bridge"
try {
  foreach ($arch in @('x64','x86')) {
    $command = ". .\build_bridge.ps1; Build -Platform $arch -BuildFlavour release -BuildSubDir _ipcC32_$arch -VcVarsVer 14.29; exit `$LASTEXITCODE"
    & powershell.exe -NoProfile -Command $command
    if ($LASTEXITCODE -ne 0) { throw "C32 Release build failed: $arch" }
  }
  $command = '. .\build_common.ps1; SetupVS -Platform x86 -VcVarsVer 14.29; & meson setup _ipcC32_x86_server --buildtype release --backend ninja -Dexperimental_x86_server=true; if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }; & meson compile -C _ipcC32_x86_server; exit $LASTEXITCODE'
  & powershell.exe -NoProfile -Command $command
  if ($LASTEXITCODE -ne 0) { throw 'C32 x86 Host build failed' }
} finally { Pop-Location }
python "$PSScriptRoot/package_ipc_c32.py"
if ($LASTEXITCODE -ne 0) { throw 'C32 package verification failed' }
