# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Reuse the frozen PR6 extraction seams, replacing only application test dispatch."""
from pathlib import Path
import shutil
import sys
ROOT = Path(__file__).resolve().parents[1]
pr6 = ROOT / '.deps/ipc-v2-pr6'
sys.path.insert(0, str(pr6 / 'scripts'))
from generate_ipc_transport_test import generate
source = ROOT / '.deps/dxvk-remix'
out = ROOT / 'work/ipc-c32-native'
generate(source, out)
shutil.copytree(source / 'bridge/src/util/ipc_v2', out / 'ipc_v2', dirs_exist_ok=True)
shutil.copy2(source / 'bridge/src/util/ipc_c32_message_queue.h', out / 'ipc_c32_message_queue.h')
code = (out / 'ipc_transport.cpp').read_text()
code = code.replace('#include "ipc_transport_cases.cpp"', '#include "c32_bridge_cases.cpp"')
(out / 'ipc_transport.cpp').write_text(code)
shutil.copy2(ROOT / 'tests/ipc-v2/c32_bridge_cases.cpp', out / 'c32_bridge_cases.cpp')
# Required by the unchanged explicit OS-wait injection seam.
shutil.copy2(pr6 / 'tests/ipc_wait_injection.h', out / 'ipc_wait_injection.h')
