# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Exercise production startup gates and API logger with deterministic adapters."""
import argparse
from pathlib import Path
from generate_buffer_contract_test import method

ROOT = Path(__file__).resolve().parents[1]


def generate(source, output):
    src = source / 'bridge/src'
    host = (src / 'server/main.cpp').read_text()
    client = (src / 'client/d3d9_lss.cpp').read_text()
    di = (src / 'client/di_hook.cpp').read_text()
    util = (src / 'client/d3d9_util.h').read_text()
    logger = (src / 'util/log/log.h').read_text()
    window = (src / 'client/window.cpp').read_text()
    generated = ['#include "runtime_observation_support.h"\n']
    for marker in ['class FunctionEntryExitLogger']:
        start, end = method(util, marker)
        generated.append(util[start:end] + ';\n')
    for marker in ['std::map<std::thread::id, std::atomic<size_t>>& FunctionEntryExitLogger::counters()', 'FunctionEntryExitLogger::FunctionEntryExitLogger(', 'FunctionEntryExitLogger::~FunctionEntryExitLogger(']:
        start, end = method(client, marker)
        generated.append(client[start:end] + '\n')
    # Use the real lazy producer method, not a substitute implementation.
    for name in ['traceLazy', 'debugLazy']:
        start, end = method(logger, 'template<typename Message> static void ' + name)
        generated.append(logger[start:end].replace('static void ' + name, 'void LazyLogger::' + name) + '\n')
    for marker in ['bool DInputHooksEnabled()', 'void DInputHookAttach()', 'void DInputHookDetach()']:
        start, end = method(di, marker)
        generated.append(di[start:end] + '\n')
    for marker in ['static l4d2_host_memory::Recorder& hostMemoryRecorder()', 'static void sampleHostMemory(',
                   'static HWND configureOverlayPresenter(', 'static HWND overlayPresentWindow(']:
        start, end = method(host, marker)
        generated.append(host[start:end] + '\n')
    start, end = method(window, 'void WndProc::sampleSteamInput()')
    generated.append(window[start:end] + '\n')
    generated.append('#include "runtime_observation_cases.cpp"\n')
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(''.join(generated))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / '.deps/dxvk-remix')
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    generate(args.source, args.output)
