# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Exercise production Client hook installation, DirectInput results and Query delegation."""
import argparse
from pathlib import Path
from generate_buffer_contract_test import method

ROOT = Path(__file__).resolve().parents[1]


def generate(source, output):
    client = source / 'bridge/src/client'
    di = (client / 'di_hook.cpp').read_text(encoding='utf-8')
    query = (client / 'd3d9_query.cpp').read_text(encoding='utf-8')
    pieces = []
    for marker in ['static void InputWinHooksAttach()', 'static void InputWinHooksDetach()']:
        start, end = method(di, marker)
        pieces.append(di[start:end])
    pieces.append('class DirectInput7Hook { public:')
    pieces.append('inline static Create OrigDirectInputCreateA = createA;')
    pieces.append('inline static Create OrigDirectInputCreateW = createW;')
    for marker in ['static void LogCreateResult(', 'static HRESULT WINAPI HookedDirectInputCreateA(',
                   'static HRESULT WINAPI HookedDirectInputCreateW(']:
        start, end = method(di, marker)
        pieces.append(di[start:end])
    pieces.append('};')
    for marker in ['ULONG Direct3DQuery9_LSS::AddRef()', 'ULONG Direct3DQuery9_LSS::Release()']:
        start, end = method(query, marker)
        pieces.append(query[start:end])
    fixture = (ROOT / 'tests/input_hooks_test.cpp').read_text(encoding='utf-8')
    marker = '// PRODUCTION_METHODS'
    if fixture.count(marker) != 1:
        raise ValueError('Unexpected input hook fixture layout')
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(fixture.replace(marker, '\n'.join(pieces)), encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / '.deps/dxvk-remix')
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    generate(args.source, args.output)
