# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Extract production setters for check-only A/B measurement; never enable filtering.

Adapters model COM/transport boundaries, not Win32 IPC or DXVK performance.
Requires a prepared v1.2.1 source tree and g++ (C++17). Results are JSON.
"""
import argparse
import hashlib
import json
from pathlib import Path
import platform
import statistics
import subprocess
import sys

from generate_buffer_contract_test import method

ROOT = Path(__file__).resolve().parents[1]
PATCH_SHA = "8ce8005da14ea40a4a10d6d7be848be05ce8ac9da25676667fa67820178b87e3"
METHOD_SHA = {
    "SetStreamSource": "11d38cf89f1f4950f328e5753b7a12311d7b493d4a7abc657dc5373f919608e6",
    "SetIndices": "a4ddee6c0e2b5808807ba15239139d6e3ce2ad6f0024096f990635636c764fac",
    "DrawPrimitiveUP": "fcf64702908fd00a2eeb18a32c41814265b59b893b9b641e74993a6ac31807f8",
    "DrawIndexedPrimitiveUP": "7183e3f9798ca6ea95587dc426f30e74e0414326c3a3d0a042fdb0ee60a51e9e",
}


def generate(source, destination):
    client = source / "bridge/src/client"
    text = (client / "d3d9_device.cpp").read_text(encoding="utf-8")
    base = (client / "base.h").read_text(encoding="utf-8")
    if hashlib.sha256(base.encode()).hexdigest() != "eb2df6ed1f088ff860ff9aab0713618d758e842ddfe0d3783f3b595bdb79d5f9":
        raise ValueError("prepared refcount source differs from the audited baseline")
    # Refcount and smart pointer implementations are extracted without rewriting.
    refs = base[base.index("class D3DRefCounted {"):base.index("class D3dBaseIdFactory {")]
    pieces = []
    hashes = {}
    for name in ("SetStreamSource", "SetIndices", "DrawPrimitiveUP", "DrawIndexedPrimitiveUP"):
        marker = f"HRESULT Direct3DDevice9Ex_LSS<EnableSync>::{name}("
        start, end = method(text, marker)
        original = text[start:end]
        hashes[name] = hashlib.sha256(original.encode()).hexdigest()
        if hashes[name] != METHOD_SHA[name]:
            raise ValueError(f"prepared production method differs: {name}")
        body = original.replace("<EnableSync>", "<EnableSync, Check>")
        if name in ("SetStreamSource", "SetIndices"):
            if name == "SetStreamSource":
                predicate = "!m_stateRecording && StreamNumber < m_state.streams.size() && *m_state.streams[StreamNumber] == pLssStreamData && (!pStreamData || (m_state.streamOffsets[StreamNumber] == OffsetInBytes && m_state.streamStrides[StreamNumber] == Stride))"
            else:
                predicate = "!m_stateRecording && *m_state.indices == pLssIndexData"
            # Necessity-only predicate, deliberately not a safe filtering decision.
            insertion = f"\n      if constexpr (Check) {{ lastMatch = {predicate}; ++checks; if (lastMatch) {{ ++matches; }} }}"
            body = body.replace("BRIDGE_DEVICE_LOCKGUARD();", "BRIDGE_DEVICE_LOCKGUARD();" + insertion, 1)
        pieces.append("template<bool EnableSync, bool Check>\n" + body)
    support = (ROOT / "tests/binding_filter_support.h").read_text(encoding="utf-8")
    support = support.replace("// INSERT_PRODUCTION_REFS", refs)
    output = support + "\n" + "\n".join(pieces) + '\n#include "binding_filter_cases.cpp"\n'
    destination.write_text(output, encoding="utf-8")
    return hashes


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=ROOT / ".deps/dxvk-remix")
    parser.add_argument("--work", type=Path, default=ROOT / "work/binding-filter")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--compiler", default="g++")
    parser.add_argument("--calls", type=int, default=2000000)
    parser.add_argument("--repeats", type=int, default=11)
    args = parser.parse_args()
    if args.calls < 10000 or args.repeats < 3:
        parser.error("use at least 10000 calls and 3 repeats")
    patch_sha = hashlib.sha256((args.source / "../../patches/l4d2-bridge.patch").resolve().read_bytes()).hexdigest()
    if patch_sha != PATCH_SHA:
        parser.error("this investigation is pinned to the v1.2.1 patch")
    args.work.mkdir(parents=True, exist_ok=True)
    generated = args.work / "binding_filter_generated.cpp"
    hashes = generate(args.source, generated)
    flags = ["-std=c++17", "-O2", "-pthread", "-Wall", "-Wextra", "-Werror", "-I", str(ROOT / "tests")]
    executables = {}
    for mode in ("semantic", "benchmark"):
        executable = args.work / mode
        subprocess.run([args.compiler, *flags, *(["-DSEMANTIC"] if mode == "semantic" else []), str(generated), "-o", str(executable)], check=True)
        executables[mode] = executable
    semantics = json.loads(subprocess.check_output([str(executables["semantic"])], text=True))
    samples = []
    # Alternate A/B order per repeat; warmup uses a separate process.
    subprocess.run([str(executables["benchmark"]), "A", "stream", "4446", "10000"], check=True, stdout=subprocess.DEVNULL)
    subprocess.run([str(executables["benchmark"]), "B", "stream", "4446", "10000"], check=True, stdout=subprocess.DEVNULL)
    for api, reality in (("stream", 4446), ("indices", 6546)):
        for rate in (100, reality, 9500):
            for repeat in range(args.repeats):
                for mode in (("A", "B") if repeat % 2 == 0 else ("B", "A")):
                    result = json.loads(subprocess.check_output([str(executables["benchmark"]), mode, api, str(rate), str(args.calls)], text=True))
                    result.update(api=api, mode=mode, requested_same_fraction=rate / 10000, repeat=repeat)
                    samples.append(result)
    summary = []
    for api, reality in (("stream", 4446), ("indices", 6546)):
        for rate in (100, reality, 9500):
            row = dict(api=api, requested_same_fraction=rate / 10000)
            for mode in ("A", "B"):
                selected = [s for s in samples if s["api"] == api and s["mode"] == mode and s["requested_same_fraction"] == rate / 10000]
                row[mode] = {key: {"median": statistics.median(s[key] for s in selected), "min": min(s[key] for s in selected), "max": max(s[key] for s in selected)} for key in ("client_ns_per_call", "client_cpu_ns_per_call", "host_adapter_ns_per_call", "total_ns_per_call")}
            row["client_delta_ns"] = row["B"]["client_ns_per_call"]["median"] - row["A"]["client_ns_per_call"]["median"]
            row["paired_delta_ns"] = [next(s["client_ns_per_call"] for s in samples if s["api"] == api and s["mode"] == "B" and s["requested_same_fraction"] == rate / 10000 and s["repeat"] == i) - next(s["client_ns_per_call"] for s in samples if s["api"] == api and s["mode"] == "A" and s["requested_same_fraction"] == rate / 10000 and s["repeat"] == i) for i in range(args.repeats)]
            summary.append(row)
    report = dict(scope="production setters + production refcount/smart pointers; deterministic COM/IPC adapters; no C", patch_sha256=patch_sha, method_sha256=hashes, compiler=subprocess.check_output([args.compiler, "--version"], text=True).splitlines()[0], platform=platform.platform(), python=sys.version.split()[0], calls=args.calls, repeats=args.repeats, semantics=semantics, summary=summary, samples=samples)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(dict(semantics=semantics, summary=summary), indent=2))


if __name__ == "__main__":
    main()
