# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Cost investigation only: compile extracted production uploads on Windows x86.

The no-copy executable is an invalid-payload counterfactual, never a game DLL.
No source under .deps/dxvk-remix is modified. See DYNAMIC-UPLOAD-COST.md.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import statistics
import subprocess
import sys

from generate_buffer_contract_test import method

ROOT = Path(__file__).resolve().parents[1]
PATCH_SHA = "8ce8005da14ea40a4a10d6d7be848be05ce8ac9da25676667fa67820178b87e3"
FILES = (
    "util_common.h", "util_commands.h", "util_circularqueue.h",
    "util_circularbuffer.h", "util_atomiccircularqueue.h", "util_ipcchannel.h",
    "util_sharedmemory.h", "util_sharedmemory.cpp", "util_semaphore.h",
    "util_semaphore.cpp", "util_guid.h", "api_wait_diagnostics.h",
    "data_diagnostics.h", "data_diagnostics.cpp", "exception_diagnostics.h",
    "exception_diagnostics.cpp", "queue_wait_diagnostics.h", "runtime_observation.h",
)


def generate(source, work):
    util = source / "bridge/src/util"
    client = source / "bridge/src/client"
    hashes = {}
    for name in FILES:
        text = (util / name).read_text(encoding="utf-8")
        hashes[name] = hashlib.sha256(text.encode()).hexdigest()
        if name == "util_ipcchannel.h":
            # Unused alternate queue drags in unrelated dependencies.
            text = text.replace('#include "util_blockingcircularqueue.h"', '')
        if name == "util_circularbuffer.h":
            needle = "memcpy(m_data + m_pos, obj, size);"
            if text.count(needle) != 1:
                raise ValueError("unexpected payload copy layout")
            text = text.replace(needle, "#ifndef L4D2_COST_NO_COPY\n          " + needle + "\n#endif")
        (work / name).write_text(text, encoding="utf-8")
    (work / "log").mkdir(exist_ok=True)
    (work / "log/log.h").write_text('''#pragma once
#include <cstdlib>
#include <string>
namespace bridge_util { enum class LogLevel { Trace }; }
template<typename... T> std::string format_string(const char*, T...) { return {}; }
struct Logger {
  static bool isEnabled(bridge_util::LogLevel) { return false; }
  static void info(const std::string&) {} static void warn(const std::string&) {}
  static void err(const std::string&) {} static void debug(const std::string&) {}
  template<typename T> static void traceLazy(T&&) {}
  template<typename T> static void debugLazy(T&&) {}
  [[noreturn]] static void errLogMessageBoxAndExit(const std::string&) { std::abort(); }
};
''', encoding="utf-8")
    (work / "log/log_strings.h").write_text('''#pragma once
namespace logger_strings {
inline const char* OutOfBufferMemory="OutOfBufferMemory";
inline const char* OutOfBufferMemory1="OutOfBufferMemory1";
inline const char* MultipleActiveCommands="MultipleActiveCommands";
inline std::string bufferNameToOption(const std::string&) { return {}; }
}
''', encoding="utf-8")
    (work / "config").mkdir(exist_ok=True)
    (work / "config/global_options.h").write_text('''#pragma once
struct GlobalOptions {
  static unsigned getCommandTimeout() { return 1000; }
  static unsigned getCommandRetries() { return 3; }
  static unsigned getSemaphoreTimeout() { return 1000; }
  static bool getUseSharedHeap() { return false; }
  static bool getUseSharedHeapForDynamicBuffers() { return false; }
  static bool getUseSharedHeapForStaticBuffers() { return false; }
  static bool getAlwaysCopyEntireStaticBuffer() { return false; }
};
''', encoding="utf-8")
    header = (util / "util_bridgecommand.h").read_text(encoding="utf-8")
    cpp = (util / "util_bridgecommand.cpp").read_text(encoding="utf-8")
    buf = (client / "lockable_buffer.h").read_text(encoding="utf-8")
    for name, text in (("util_bridgecommand.h", header), ("util_bridgecommand.cpp", cpp), ("lockable_buffer.h", buf)):
        hashes[name] = hashlib.sha256(text.encode()).hexdigest()
    command_class = header[header.index("  class Command {"):header.index("\nprivate:\n  Bridge()")]
    statics = header[header.index("  static inline WriterChannel*"):header.index("#if defined(REMIX_BRIDGE_CLIENT)", header.index("  static inline WriterChannel*"))]
    start, end = method(cpp, "DECL_BRIDGE_FUNC(void, syncDataQueue,")
    sync = cpp[start:end]
    definitions = cpp[cpp.index("#define DECL_COMMAND_FUNC"):]
    bridge = '''namespace BridgeId { struct Device {}; struct Module {}; }
template<typename BridgeId> class Bridge {
  using DataT = uint32_t;
public:
  static void syncDataQueue(size_t, bool);
  static const WriterChannel& getWriterChannel() { return *s_pWriterChannel; }
''' + command_class + statics + '''};
#define DECL_BRIDGE_FUNC(RETURN_T, NAME, ...) \\
  template<typename BridgeId> RETURN_T Bridge<BridgeId>::NAME(__VA_ARGS__)
''' + sync + definitions + '''
using DeviceBridge = Bridge<BridgeId::Device>;
using ClientMessage = DeviceBridge::Command;
'''
    template = buf[buf.index("template <typename T>"):]
    support = (ROOT / "tests/dynamic_upload_support.h").read_text(encoding="utf-8")
    support = support.replace("// INSERT_PRODUCTION_BRIDGE", bridge)
    generated = work / "dynamic_upload_generated.cpp"
    generated.write_text(support + "\n" + template + '\n#include "dynamic_upload_cases.cpp"\n', encoding="utf-8")
    return generated, hashes


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=ROOT / ".deps/dxvk-remix")
    parser.add_argument("--work", type=Path, default=ROOT / "work/dynamic-upload")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--repeats", type=int, default=11)
    parser.add_argument("--generate-only", action="store_true")
    args = parser.parse_args()
    if args.repeats < 3:
        parser.error("at least three repeats required")
    if hashlib.sha256((ROOT / "patches/l4d2-bridge.patch").read_bytes()).hexdigest() != PATCH_SHA:
        parser.error("this investigation is pinned to the v1.2.1 runtime patch")
    args.work = args.work.resolve()
    args.work.mkdir(parents=True, exist_ok=True)
    generated, hashes = generate(args.source.resolve(), args.work)
    if args.generate_only:
        print(json.dumps(hashes, indent=2))
        return
    if sys.platform != "win32":
        parser.error("native measurement requires Windows x86 MSVC; generation has completed")
    compiler_banner = subprocess.run(["cl.exe"], capture_output=True, text=True)
    banner = compiler_banner.stdout + compiler_banner.stderr
    if "for x86" not in banner:
        parser.error("use an x86 vcvars environment")
    sources = [generated, args.work / "util_sharedmemory.cpp", args.work / "util_semaphore.cpp", args.work / "data_diagnostics.cpp", args.work / "exception_diagnostics.cpp"]
    exes = {}
    for mode in ("full", "floor"):
        exe = args.work / (mode + ".exe")
        command = ["cl.exe", "/nologo", "/std:c++17", "/EHsc", "/O2", "/DNOMINMAX", "/DWIN32", "/W3", "/I" + str(args.work), "/I" + str(ROOT / "tests")]
        if mode == "floor":
            command.append("/DL4D2_COST_NO_COPY")
        subprocess.run([*command, *map(str, sources), "/Fe:" + str(exe), "/link", "ole32.lib", "psapi.lib"], cwd=args.work, check=True)
        exes[mode] = exe
    semantics = json.loads(subprocess.check_output([str(exes["full"]), "semantic"], text=True))
    # Nothing claiming equivalent bytes runs in the floor executable.
    samples = []
    sizes = (1, 64, 256, 1024, 4096, 16384, 65536, 262144)
    for working in ("hot", "stream"):
        for size in sizes:
            for kind in ("vb", "ib"):
                for mode in ("full", "floor"):
                    subprocess.run([str(exes[mode]), "bench", kind, str(size), working, "warm"], check=True, stdout=subprocess.DEVNULL)
                for repeat in range(args.repeats):
                    for mode in (("full", "floor") if repeat % 2 == 0 else ("floor", "full")):
                        result = json.loads(subprocess.check_output([str(exes[mode]), "bench", kind, str(size), working], text=True))
                        result.update(mode=mode, repeat=repeat, kind=kind, size=size, working=working)
                        samples.append(result)
    summary = []
    for working in ("hot", "stream"):
        for size in sizes:
            for kind in ("vb", "ib"):
                chosen = [s for s in samples if (s["working"], s["size"], s["kind"]) == (working, size, kind)]
                row = dict(working=working, size=size, kind=kind)
                for mode in ("full", "floor"):
                    entries = [s for s in chosen if s["mode"] == mode]
                    row[mode] = {key: dict(median=statistics.median(s[key] for s in entries), min=min(s[key] for s in entries), max=max(s[key] for s in entries)) for key in ("upload_ns", "upload_cpu_ns", "consume_ns")}
                row["paired_saved_ns"] = [next(s["upload_ns"] for s in chosen if s["mode"] == "full" and s["repeat"] == r) - next(s["upload_ns"] for s in chosen if s["mode"] == "floor" and s["repeat"] == r) for r in range(args.repeats)]
                row["copy_delta_ns"] = statistics.median(row["paired_saved_ns"])
                row["copy_share"] = row["copy_delta_ns"] / row["full"]["upload_ns"]["median"]
                summary.append(row)
    output = dict(schema=1, scope="Windows x86 native shared memory and queues; production template and command path; allocation/options/logger/device/peer adapters; uncontended staged batches; no game/GPU", patch_sha256=PATCH_SHA, source_sha256=hashes, compiler=banner.strip(), platform=platform.platform(), processor=platform.processor(), cpu_count=os.cpu_count(), repeats=args.repeats, semantics=semantics, summary=summary, samples=samples)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")
    print("DYNAMIC_UPLOAD_RESULT " + json.dumps({k: v for k, v in output.items() if k != "samples"}))


if __name__ == "__main__":
    main()
