# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Package only a matched experimental bridge; never modify VERSION or releases."""
from pathlib import Path
import hashlib
import json
import shutil
import struct
import subprocess
import zipfile
from package_release import machine
ROOT=Path(__file__).resolve().parents[1]
receipt=json.loads((ROOT/'work/ipc-c32-build.json').read_text())
build=receipt['build_id']
source=ROOT/'.deps/dxvk-remix/bridge'
files={
 'bin/dxvk_d3d9.dll':(source/'_ipcC32_x86/src/client/d3d9.dll',0x14c),
 'bin/.l4d2bridge/L4D2Bridge64.exe':(source/'_ipcC32_x64/src/server/L4D2Bridge64.exe',0x8664),
 'bin/.l4d2bridge/L4D2Bridge32.exe':(source/'_ipcC32_x86_server/src/server/L4D2Bridge32.exe',0x14c),
}
out=ROOT/'dist/ipc-c32'
out.mkdir(parents=True,exist_ok=False)
hashes={}
for name,(path,arch) in files.items():
    if machine(path)!=arch or build.encode() not in path.read_bytes():
        raise RuntimeError(f'Architecture/build identity mismatch: {name}')
    if arch==0x14c:
        raw=path.read_bytes();pe=struct.unpack_from('<I',raw,60)[0]
        if not struct.unpack_from('<H',raw,pe+22)[0]&0x20: raise RuntimeError('x86 must be LARGEADDRESSAWARE')
    dest=out/name;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(path,dest)
    hashes[name]=hashlib.sha256(dest.read_bytes()).hexdigest()
receipt.update(source_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),
               distribution='experimental',build_type='Release',compiler='MSVC 14.29',
               kind='matched-update',default_batch=32,lazy_check_ms=1,
               files=hashes,gameplay_validated=False,status='AWAITING GAME VALIDATION')
(out/'BUILD-INFO.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
(out/'SHA256.json').write_text(json.dumps(hashes,indent=2)+'\n',encoding='utf-8')
shutil.copy2(ROOT/'docs/IPC-C32-DEVELOPMENT.md',out/'INSTALL-AND-TEST.md')
for filename in ('LICENSE','THIRD_PARTY.md'):
    shutil.copy2(ROOT/filename,out/filename)
(out/'licenses').mkdir()
for filename in ('LICENSE-MIT','ThirdPartyLicenses.txt'):
    shutil.copy2(source/filename,out/'licenses'/filename)
zip_path=out.parent/f'l4d2-bridge-ipc-c32-dev-{build.split("+")[1]}.zip'
with zipfile.ZipFile(zip_path,'w',zipfile.ZIP_DEFLATED,compresslevel=9) as archive:
    for path in sorted(out.rglob('*')):
        if path.is_file():archive.write(path,path.relative_to(out))
digest=hashlib.sha256(zip_path.read_bytes()).hexdigest()
(zip_path.parent/'SHA256SUMS.txt').write_text(f'{digest}  {zip_path.name}\n',encoding='utf-8')
print(zip_path.name,digest)
