# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Extract frozen actual A/B hot paths; never substitute a queue simulation."""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
A = 'cf49175e8a3c6c2fe45c99aec0680b0d1c864d24'
B = '14fc5db13d4a9e637fc6b001d06ab5ca3f1eed11'
PR6 = '8730d84b77c596efdabfad54b7458a8f0aeb01a4'
B_PATCH_SHA = '9c0f063939cd14fb3d6571880dfb1e27bdcd8649b746f1f1480c845f4b89e24c'


def prepare(pr6, a_source=None, b_source=None):
    sys.path.insert(0, str(pr6 / 'scripts'))
    from generate_ipc_performance_test import baseline
    from generate_ipc_transport_test import generate
    if a_source is None or b_source is None:
        import subprocess
        head = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=pr6, text=True).strip()
        if head != PR6:
            raise RuntimeError('PR6 generator checkout is not the frozen audited revision')
        if hashlib.sha256((pr6 / 'patches/l4d2-bridge.patch').read_bytes()).hexdigest() != B_PATCH_SHA:
            raise RuntimeError('PR6 production patch identity mismatch')
        from prepare_bridge import prepare as prepare_bridge
        from prepare_ipc_baseline import prepare as prepare_a
        b_source = pr6 / '.deps/dxvk-remix'
        prepare_bridge(b_source)
        a_source = prepare_a()
    for variant, source in [('A', a_source), ('B', b_source)]:
        directory = ROOT / f'.deps/ipc-v2-{variant}'
        (baseline if variant == 'A' else generate)(source, directory)
        code = (directory / 'ipc_transport.cpp').read_text(encoding='utf-8')
        seam = code.index('\nnamespace {')
        header = code[:seam]
        header = header.replace('std::atomic<bool> gbBridgeRunning {true};', 'extern std::atomic<bool> gbBridgeRunning;')
        header = header.replace('bool gbBridgeRunning=true;', 'extern bool gbBridgeRunning;')
        header = header.replace('std::atomic<bool> ipcInjectWaitFailure {false};', 'extern std::atomic<bool> ipcInjectWaitFailure;')
        header = header.replace('bridge_util::Guid gUniqueIdentifier;', 'extern bridge_util::Guid gUniqueIdentifier;')
        end = code.index('#include "ipc_' + ('performance' if variant == 'A' else 'transport') + '_cases.cpp"')
        body = code[seam:end]
        if variant == 'A':
            # Keep the real v1.2.1 completion path, with an explicit declaration.
            header += '\nvoid benchmarkComplete();\n'
        (directory / 'ipc_fixture.h').write_text('#pragma once\n' + header, encoding='utf-8')
        running = 'bool' if variant == 'A' else 'std::atomic<bool>'
        globals_ = f'{running} gbBridgeRunning {{true}};\nstd::atomic<bool> ipcInjectWaitFailure {{false}};\nbridge_util::Guid gUniqueIdentifier;\n'
        (directory / 'ipc_command.cpp').write_text('#include "ipc_fixture.h"\n' + globals_ + body, encoding='utf-8')
        manifest = directory / 'source-manifest.json'
        data = json.loads(manifest.read_text())
        data.update(variant=variant, production_commit=A if variant == 'A' else B,
                    generator_commit=PR6, compilation='caller/Command separate TU, no LTO, /O2',
                    caller='tests/ipc-v2/benchmark.cpp', semantics='command 5, UID + sequence + length + blob',
                    dispatch='test validation, no D3D9 backend; immediate packet path for PR6')
        manifest.write_text(json.dumps(data, indent=2) + '\n')
        print('IPC_V2_BASELINE', variant, source)


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--pr6-repo', type=Path, default=ROOT / '.deps/ipc-v2-pr6')
    p.add_argument('--a-source', type=Path)
    p.add_argument('--b-source', type=Path)
    args = p.parse_args()
    prepare(args.pr6_repo.resolve(), args.a_source.resolve() if args.a_source else None,
            args.b_source.resolve() if args.b_source else None)
