# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Apply the experimental overlay to an already prepared, pristine main build."""
from pathlib import Path
import hashlib
import json
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]

def identity():
    paths = [ROOT / 'patches/l4d2-bridge.patch', ROOT / 'patches/ipc-c32.patch']
    paths += sorted((ROOT / 'experiments/ipc-c32').glob('*.h'))
    paths += [ROOT / 'experiments/ipc-v2/platform.h', ROOT / 'experiments/ipc-v2/transport.h']
    digest = hashlib.sha256()
    for path in paths:
        # Git Windows checkout line endings do not change the protocol identity.
        digest.update(path.relative_to(ROOT).as_posix().encode() + b'\0')
        digest.update(path.read_bytes().replace(b'\r\n', b'\n') + b'\0')
    return digest.hexdigest()

def prepare(source):
    patch = ROOT / 'patches/ipc-c32.patch'
    subprocess.run(['git', 'apply', '--check', str(patch)], cwd=source, check=True)
    subprocess.run(['git', 'apply', str(patch)], cwd=source, check=True)
    util = source / 'bridge/src/util'
    (util / 'ipc_v2').mkdir(exist_ok=True)
    for name in ('platform.h', 'transport.h'):
        shutil.copy2(ROOT / 'experiments/ipc-v2' / name, util / 'ipc_v2' / name)
    shutil.copy2(ROOT / 'experiments/ipc-c32/message_queue.h', util / 'ipc_c32_message_queue.h')
    digest = identity()
    definitions = ''.join(f'#define LDB_IPC_V2_BUILD{i} 0x{digest[i*8:i*8+8]}u\n' for i in range(4))
    (util / 'ipc_v2/ipc_v2_build.h').write_text(definitions, encoding='utf-8')
    receipt = {'build_id': f'ldb-ipc-c32-dev+{digest[:16]}', 'protocol_source_sha256': digest,
               'foundation': 'PR6 production 14fc5db13d4a9e637fc6b001d06ab5ca3f1eed11',
               'gameplay_validated': False}
    (ROOT / 'work').mkdir(exist_ok=True)
    (ROOT / 'work/ipc-c32-build.json').write_text(json.dumps(receipt, indent=2)+'\n', encoding='utf-8')
    print(receipt['build_id'])

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / '.deps/dxvk-remix')
    args = parser.parse_args()
    prepare(args.source.resolve())
