#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
"""Repeat native cross-process tests and counterbalanced IPC comparisons.

Linux runs C1/C32/C32-spin only. Windows adds immutable actual A/B fixtures.
Failed samples remain failures and are excluded from timing ratios.
"""
import argparse
import hashlib
import itertools
import json
import os
from pathlib import Path
import platform
import statistics
import subprocess
import uuid

ROOT = Path(__file__).resolve().parents[1]
SCENARIOS = [('stream', n, 24000 if n <= 256 else 12000 if n <= 4096 else
              3000 if n <= 16384 else 190 if n <= 65536 else 48, 8388608)
             for n in (0, 16, 64, 256, 1024, 4096, 16384, 65536, 524288, 2097152)]
SCENARIOS += [('batch', 64, 4096, 8388608), ('rpc', 64, 3000, 8388608),
              ('mixed', 524288, 2048, 8388608), ('slow', 64, 12000, 4096),
              ('stream', 64, 12000, 4096), ('idle', 0, 1, 8388608)]


def run_checked(cmd, **kwargs):
    subprocess.run([str(v) for v in cmd], check=True, timeout=90, **kwargs)


def build_linux(out):
    out.mkdir(parents=True, exist_ok=True)
    stamp_build(out)
    prepare_old_controls(out)
    for name in ('native', 'benchmark'):
        run_checked(['g++', '-std=c++17', '-O2', '-Wall', '-Wextra', '-Werror', '-pthread',
                     '-I', out, ROOT / f'tests/ipc-v2/{name}.cpp', '-o', out / name])

    run_checked(['g++', '-std=c++17', '-O2', '-Wall', '-Wextra', '-Werror', '-pthread',
                 '-DIPC_V2_OLD_CONTROL', '-I', out, ROOT / 'tests/ipc-v2/benchmark.cpp',
                 '-o', out / 'benchmark-old-controls'])


def prepare_old_controls(out):
    frozen = '58890170fcd1b3b599fc270b2127717d03ad07e1'
    old = out / 'old-controls'; old.mkdir(exist_ok=True)
    for name in ('platform.h', 'transport.h'):
        (old / name).write_bytes(subprocess.check_output(
            ['git', 'show', f'{frozen}:experiments/ipc-v2/{name}'], cwd=ROOT))
    (old / 'source-manifest.json').write_text(json.dumps(dict(commit=frozen,
        scope='old C control layout only, same current caller, no production changes',
        source_sha256={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in old.glob('*.h')}),indent=2)+'\n')


def stamp_build(out):
    paths = sorted((ROOT / 'experiments/ipc-v2').glob('*.h')) + sorted((ROOT / 'tests/ipc-v2').glob('*.cpp'))
    digest = hashlib.sha256(b''.join(str(p.relative_to(ROOT)).encode() + b'\0' + p.read_bytes() for p in paths)).hexdigest()
    (out / 'ipc_v2_build.h').write_text(''.join(f'#define LDB_IPC_V2_BUILD{i} 0x{digest[i*8:(i+1)*8]}u\n' for i in range(4)))
    (out / 'BUILD-INFO.json').write_text(json.dumps(dict(build_id='ipc-v2-prototype-' + digest[:32],
        source_sha256=digest, gameplay_validated=False, production_integrated=False), indent=2) + '\n')
    return digest


def binaries(out, variant, arch):
    if variant in ('A', 'B'):
        base = ROOT / f'.deps/ipc-v2-{variant}'
        return base / 'perf-client32.exe', base / f'perf-host{arch}.exe'
    if variant == 'C1-old-control':
        if platform.system() == 'Windows':
            return out / 'benchmark-old-controls32.exe', out / f'benchmark-old-controls{arch}.exe'
        return out / 'benchmark-old-controls', out / 'benchmark-old-controls'
    if platform.system() == 'Windows':
        return out / 'benchmark32.exe', out / f'benchmark{arch}.exe'
    return out / 'benchmark', out / 'benchmark'


def sample(out, arch, variant, scenario, iteration):
    mode, size, count, words = scenario
    client_exe, host_exe = binaries(out, variant, arch)
    batch = 1 if variant in ('A', 'B', 'C1', 'C1-old-control') else 32
    spins = 128 if variant.endswith('-spin') else 0
    block_bytes = 4096 if '-4K' in variant else 65536
    common = [str(uuid.uuid4()), str(count), str(size), mode, str(batch), str(spins), str(words), str(block_bytes)]
    row = dict(arch=arch, variant=variant, mode=mode, bytes=size, count=count,
               arena_words=words, batch=batch, spins=spins, block_bytes=block_bytes, iteration=iteration, valid=False)
    processes = []
    try:
        processes = [subprocess.Popen([str(host_exe), 'host', *common], stdout=subprocess.PIPE,
                                      stderr=subprocess.STDOUT, text=True),
                     subprocess.Popen([str(client_exe), 'client', *common], stdout=subprocess.PIPE,
                                      stderr=subprocess.STDOUT, text=True)]
        logs = [p.communicate(timeout=20)[0] for p in processes]
        metrics = [json.loads(line) for log in logs for line in log.splitlines() if line.startswith('{')]
        if any(p.returncode for p in processes) or len(metrics) != 2:
            raise RuntimeError(str(logs))
        if {m['role'] for m in metrics} != {'host', 'client'}:
            raise RuntimeError('missing roles')
        expected_client_bits = 32 if platform.system() == 'Windows' else 64
        for metric in metrics:
            expected = expected_client_bits if metric['role'] == 'client' else int(arch)
            if metric['pointer_bits'] != expected:
                raise RuntimeError('architecture mismatch')
        row.update(valid=True, metrics=metrics)
    except (OSError, subprocess.TimeoutExpired, RuntimeError) as error:
        row['error'] = str(error)
    finally:
        for process in processes:
            if process.poll() is None:
                process.kill()
            process.wait(timeout=5)
    return row


def summarize(rows):
    result = []
    keys = sorted({(r['arch'], r['mode'], r['bytes'], r['arena_words']) for r in rows})
    for arch, mode, size, words in keys:
        group = [r for r in rows if (r['arch'], r['mode'], r['bytes'], r['arena_words'])
                 == (arch, mode, size, words) and r['iteration'] >= 0]
        item = dict(arch=arch, mode=mode, bytes=size, arena_words=words, variants={}, paired={})
        variants = sorted({r['variant'] for r in group})
        for variant in variants:
            samples = [r for r in group if r['variant'] == variant]
            valid = [r for r in samples if r['valid']]
            stats = dict(passed=len(valid), failed=len(samples) - len(valid))
            for role in ('client', 'host'):
                for metric in ('wall_ns', 'cpu_ns', 'cycles', 'end_to_end_ns',
                               'rpc_p50_ns', 'rpc_p95_ns', 'rpc_p99_ns', 'mapping_bytes',
                               'private_bytes', 'publications', 'copy_bytes'):
                    values = []
                    for row in valid:
                        data = next(m for m in row['metrics'] if m['role'] == role)
                        if metric == 'cycles' and not data['cycles_supported']:
                            continue
                        value = data[metric]
                        if metric in ('wall_ns', 'cpu_ns', 'cycles', 'end_to_end_ns'):
                            value /= row['count']
                        values.append(value)
                    if values:
                        stats[f'{role}_{metric}'] = dict(median=statistics.median(values),
                                                         min=min(values), max=max(values))
            item['variants'][variant] = stats
        for old, new in itertools.combinations(variants, 2):
            changes = {}
            for role in ('client', 'host'):
                for metric in ('wall_ns', 'cpu_ns', 'cycles', 'end_to_end_ns', 'rpc_p50_ns', 'rpc_p95_ns', 'rpc_p99_ns'):
                    differences = []
                    for i in sorted({r['iteration'] for r in group}):
                        a = next((r for r in group if r['iteration'] == i and r['variant'] == old and r['valid']), None)
                        b = next((r for r in group if r['iteration'] == i and r['variant'] == new and r['valid']), None)
                        if not a or not b:
                            continue
                        av = next(m for m in a['metrics'] if m['role'] == role)
                        bv = next(m for m in b['metrics'] if m['role'] == role)
                        if metric == 'cycles' and not (av['cycles_supported'] and bv['cycles_supported']):
                            continue
                        if av[metric]:
                            differences.append((bv[metric] / av[metric] - 1) * 100)
                    if differences:
                        changes[f'{role}_{metric}'] = dict(paired_delta_percent_median=statistics.median(differences),
                                                           min=min(differences), max=max(differences), pairs=len(differences))
            item['paired'][f'{old}_to_{new}'] = changes
        result.append(item)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=ROOT / 'work/ipc-v2')
    parser.add_argument('--no-build', action='store_true')
    parser.add_argument('--windows-baselines', action='store_true')
    parser.add_argument('--rounds', type=int, default=11)
    parser.add_argument('--quick', action='store_true')
    args = parser.parse_args()
    out = args.output.resolve(); out.mkdir(parents=True, exist_ok=True)
    if not args.no_build:
        if platform.system() == 'Windows':
            raise RuntimeError('Use scripts/test_ipc_v2.ps1 to build MSVC binaries first')
        build_linux(out)
    native = out / ('native32.exe' if platform.system() == 'Windows' else 'native')
    if platform.system() == 'Windows':
        for arch in ('32', '64'):
            run_checked([native, '--host', out / f'native{arch}.exe'])
    else:
        run_checked([native])
    variants = ['C1', 'C1-old-control', 'C32', 'C32-spin', 'C32-4K', 'C32-4K-spin']
    if args.windows_baselines:
        if platform.system() != 'Windows':
            raise RuntimeError('Actual A/B require Windows; Linux emulation is intentionally excluded')
        variants = ['A', 'B', *variants]
    scenarios = SCENARIOS if not args.quick else [SCENARIOS[2], SCENARIOS[11]]
    rows = []
    metadata = dict(platform=platform.platform(), processor=platform.processor(), cpu_count=os.cpu_count(),
                    compiler='MSVC 14.29 /O2, separate production caller/Command TU' if platform.system() == 'Windows'
                    else 'GCC C++17 -O2 -pthread',
                    scope='independent transport, no D3D9/DXVK/GPU, no upload pool or Reply Slot',
                    source_sha256={str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                                   for p in sorted((ROOT / 'experiments/ipc-v2').glob('*.h'))
                                   + sorted((ROOT / 'tests/ipc-v2').glob('*.cpp'))})
    for arch in ('32', '64') if platform.system() == 'Windows' else ('64',):
        for scenario in scenarios:
            for iteration in range(-1, args.rounds):
                order = variants[iteration % len(variants):] + variants[:iteration % len(variants)]
                if iteration % 2:
                    order = list(reversed(order))
                for variant in order:
                    row = sample(out, arch, variant, scenario, iteration)
                    rows.append(row)
                    (out / 'raw.json').write_text(json.dumps(dict(metadata=metadata, samples=rows), indent=2) + '\n')
                    if not row['valid']:
                        print('IPC_V2_SAMPLE_FAILED ' + json.dumps(row), flush=True)
                        if variant != 'A':
                            (out / 'summary.json').write_text(json.dumps(summarize(rows), indent=2) + '\n')
                            raise RuntimeError('Checked transport failed; performance gate blocked')
            print(f'IPC_V2_SCENARIO_DONE host={arch} mode={scenario[0]} bytes={scenario[1]}', flush=True)
    (out / 'summary.json').write_text(json.dumps(summarize(rows), indent=2) + '\n')
    print(f'IPC_V2_RESULTS {out} samples={len(rows)}', flush=True)


if __name__ == '__main__':
    main()
