# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
import os
from pathlib import Path
import subprocess
import uuid
ROOT=Path(__file__).resolve().parents[1]
out=ROOT/'work/ipc-c32-native'
for arch in ('x86','x64'):
    subprocess.run([out/f'c32-{arch}.exe'],check=True,timeout=20)
for batch in ('1','32'):
    for arch in ('32','64'):
        guid='{'+str(uuid.uuid4())+'}'
        env=dict(os.environ,LDB_IPC_BATCH=batch)
        host=subprocess.Popen([out/f'transport-host{arch}.exe',guid],env=env)
        client=None
        try:
            client=subprocess.Popen([out/'transport-client32.exe',guid],env=env)
            client_rc=client.wait(timeout=30)
            host_rc=host.wait(timeout=30)
            if client_rc or host_rc: raise RuntimeError(f'C32 native failed: {batch=} {arch=} {client_rc=} {host_rc=}')
            print(f'C32_CROSS_PROCESS_PASS batch={batch} x86->x{arch}',flush=True)
        finally:
            for child in (client,host):
                if child is not None and child.poll() is None:
                    child.kill();child.wait()
