# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
import json
import os
from pathlib import Path
import subprocess
import uuid
ROOT=Path(__file__).resolve().parents[1]
out=ROOT/'work/ipc-c32-native'
for arch in ('x86','x64'):
    subprocess.run([out/f'c32-{arch}.exe'],check=True,timeout=20)
for mode in ('abort','timeout'):
    subprocess.run([out/'transport-client32.exe',mode],check=True,timeout=10)
rows=[]
for iteration in range(3):
    for batch in (('1','32') if iteration%2==0 else ('32','1')):
        for arch in ('32','64'):
            for mode in ('stream','mixed','threaded'):
                guid=str(uuid.uuid4())
                env=dict(os.environ,LDB_IPC_BATCH=batch)
                host=subprocess.Popen([out/f'transport-host{arch}.exe',guid,mode],env=env,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
                client=None
                try:
                    client=subprocess.Popen([out/'transport-client32.exe',guid,mode],env=env,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
                    client_text=client.communicate(timeout=30)[0]
                    host_text=host.communicate(timeout=30)[0]
                    row=dict(iteration=iteration,batch=batch,host_arch=arch,mode=mode,
                             client_rc=client.returncode,host_rc=host.returncode,client=client_text,host=host_text)
                    rows.append(row)
                    (out/'c32-native-results.json').write_text(json.dumps(rows,indent=2)+'\n')
                    if client.returncode or host.returncode:
                        print(client_text,host_text,flush=True)
                        raise RuntimeError(f'C32 native failed: {batch=} {arch=} {mode=}')
                    print(f'C32_CROSS_PROCESS_PASS iteration={iteration} batch={batch} x86->x{arch} mode={mode}',flush=True)
                finally:
                    for child in (client,host):
                        if child is not None and child.poll() is None:
                            child.kill();child.wait()
