# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param([ValidateSet('32','64')][string]$CompileArch,
      [ValidateSet('A','B')][string]$Baseline,
      [ValidateSet('client32','host32','host64')][string]$Role,
      [switch]$BuildOnly)
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$out = Join-Path $repoRoot 'work/ipc-v2'
$source = Join-Path $repoRoot '.deps/ipc-v2-pr6/.deps/dxvk-remix'
if ($CompileArch -or $Baseline) {
  $arch = if (($CompileArch -eq '64') -or ($Role -eq 'host64')) { 'x64' } else { 'x86' }
  . (Join-Path $source 'bridge/build_common.ps1')
  SetupVS -Platform $arch -VcVarsVer '14.29'
  if ($CompileArch) {
    Push-Location $out
    try {
      foreach ($name in @('native','benchmark')) {
        # C4324 is intentional cache-line padding, verified by ABI assertions.
        & cl.exe /nologo /std:c++17 /EHsc /O2 /W4 /WX /wd4324 /DNOMINMAX /DWIN32 "/I$out" "$repoRoot/tests/ipc-v2/$name.cpp" "/Fe:$name$CompileArch.exe" /link /LARGEADDRESSAWARE psapi.lib
        if ($LASTEXITCODE -ne 0) { throw "Prototype compile failed: $name$CompileArch" }
      }
    } finally { Pop-Location }
  } else {
    $fixture = Join-Path $repoRoot ".deps/ipc-v2-$Baseline"
    Push-Location $fixture
    try {
      [string[]]$flags = if ($Role -eq 'host32') { @('/DREMIX_BRIDGE_X86_SERVER','/DREMIX_BRIDGE_SERVER') } else { @() }
      if ($Baseline -eq 'A') { $flags += '/DIPC_OLD_BASELINE' }
      & cl.exe /nologo /std:c++17 /EHsc /O2 /W3 /DNOMINMAX /DWIN32 /DIPC_LEGACY @flags "/I$fixture" "/I$out" "/I$repoRoot/.deps/ipc-v2-pr6/tests" "$repoRoot/tests/ipc-v2/benchmark.cpp" ipc_command.cpp util_sharedmemory.cpp util_semaphore.cpp data_diagnostics.cpp exception_diagnostics.cpp "/Fe:perf-$Role.exe" /link /LARGEADDRESSAWARE ole32.lib psapi.lib
      if ($LASTEXITCODE -ne 0) { throw "Baseline compile failed: $Baseline $Role" }
    } finally { Pop-Location }
  }
} else {
  New-Item -ItemType Directory -Force $out | Out-Null
  python -c "import sys;sys.path.insert(0,r'$repoRoot/scripts');from run_ipc_v2 import stamp_build;from pathlib import Path;stamp_build(Path(r'$out'))"
  if ($LASTEXITCODE -ne 0) { throw 'Build identity generation failed' }
  foreach ($arch in @('32','64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -CompileArch $arch
    if ($LASTEXITCODE -ne 0) { throw "Prototype build failed: $arch" }
  }
  foreach ($variant in @('A','B')) {
    foreach ($role in @('client32','host32','host64')) {
      & powershell.exe -NoProfile -File $PSCommandPath -Baseline $variant -Role $role
      if ($LASTEXITCODE -ne 0) { throw "Baseline build failed: $variant $role" }
    }
  }
  Get-ChildItem $out, "$repoRoot/.deps/ipc-v2-A", "$repoRoot/.deps/ipc-v2-B" -Filter '*.exe' |
    Get-FileHash -Algorithm SHA256 | Select-Object Path, Hash |
    ConvertTo-Json | Set-Content (Join-Path $out 'BINARY-SHA256.json')
  if (-not $BuildOnly) {
    python "$repoRoot/scripts/run_ipc_v2.py" --no-build --windows-baselines --rounds 11
    if ($LASTEXITCODE -ne 0) { throw 'Native assertions or benchmark gate failed' }
  }
}
