# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param([ValidateSet('x86', 'x64')][string]$Platform)
$ErrorActionPreference = 'Stop'
if (!$Platform) {
  foreach ($arch in @('x86', 'x64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -Platform $arch
    if ($LASTEXITCODE -ne 0) { throw "Runtime observation test failed for $arch" }
  }
  exit 0
}
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
. (Join-Path $source 'bridge/build_common.ps1')
SetupVS -Platform $Platform -VcVarsVer '14.29'
$output = Join-Path $repoRoot ".deps/observation-test-$Platform"
New-Item -ItemType Directory -Force $output | Out-Null
Push-Location $output
try {
  $generated = Join-Path $output 'actual_runtime_observation.cpp'
  & python "$repoRoot/scripts/generate_runtime_observation_test.py" --source $source --output $generated
  if ($LASTEXITCODE -ne 0) { throw 'Runtime observation source generation failed' }
  & cl.exe /nologo /std:c++17 /EHsc /O2 /W4 /WX /DNOMINMAX /DL4D2_EXCEPTION_TEST /DL4D2_DATA_TEST_STATE /wd4018 "/FI$repoRoot/tests/diagnostic_work_hooks.h" "/I$source/bridge/src/client" "/I$source/bridge/src/server" "/I$source/bridge/src/util" "/I$repoRoot/tests" $generated "$source/bridge/src/util/color_diagnostics.cpp" "$source/bridge/src/util/data_diagnostics.cpp" "$source/bridge/src/util/exception_diagnostics.cpp" /Fe:observation-test.exe /link psapi.lib bcrypt.lib user32.lib
  if ($LASTEXITCODE -ne 0) { throw 'Runtime observation compilation failed' }
  foreach ($mode in @('off', 'monitor-on', 'input-on', 'crash-on', 'logging-on', 'init-failure', 'allocation-failure', 'data-on', 'lg-off', 'retention-log-failure', 'retention-write-failure', 'retention-callback-failure')) {
    # Each process starts with fresh startup-only flags and lazy subsystem state.
    if ($mode -eq 'off') { Get-ChildItem $output -Filter '*.log' | Remove-Item -Force }
    & .\observation-test.exe $mode
    if ($LASTEXITCODE -ne 0) { throw "Runtime observation $mode failed" }
    if ($mode -eq 'off' -and (Get-ChildItem $output -Filter '*.log')) {
      throw 'Disabled subsystems created a diagnostic log'
    }
  }
} finally { Pop-Location }
