# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
. (Join-Path $source 'bridge/build_common.ps1')
SetupVS -Platform x86 -VcVarsVer '14.29'
$output = Join-Path $repoRoot '.deps/buffer-contract-test'
New-Item -ItemType Directory -Force $output | Out-Null
$generated = Join-Path $output 'actual_buffer_contract.cpp'
& python "$repoRoot/scripts/generate_buffer_contract_test.py" --source $source --output $generated
if ($LASTEXITCODE -ne 0) { throw 'Buffer contract source generation failed' }
Push-Location $output
try {
  & cl.exe /nologo /std:c++17 /EHsc /W4 /WX /DNOMINMAX "/I$source/bridge/src/util" "/I$source/bridge/src/client" "/I$repoRoot/tests" $generated "$source/bridge/src/util/data_diagnostics.cpp" /Fe:buffer-contract.exe
  if ($LASTEXITCODE -ne 0) { throw 'Buffer contract test compilation failed' }
  & .\buffer-contract.exe
  if ($LASTEXITCODE -ne 0) { throw 'Buffer contract regression test failed' }
} finally { Pop-Location }
