# SPDX-License-Identifier: MIT
# Copyright (c) 2026 yeyunyyds.
# All newly added implementation code in this fork was generated by OpenAI Codex from prompts and specifications provided by yeyunyyds.
param([ValidateSet('x86', 'x64')][string]$Platform)
$ErrorActionPreference = 'Stop'
if (!$Platform) {
  foreach ($arch in @('x86', 'x64')) {
    & powershell.exe -NoProfile -File $PSCommandPath -Platform $arch
    if ($LASTEXITCODE -ne 0) { throw "Client input/logging regression failed for $arch" }
  }
  exit 0
}
$repoRoot = Split-Path $PSScriptRoot -Parent
$source = Join-Path $repoRoot '.deps/dxvk-remix'
. (Join-Path $source 'bridge/build_common.ps1')
SetupVS -Platform $Platform -VcVarsVer '14.29'
$output = Join-Path $repoRoot ".deps/input-hooks-test-$Platform"
New-Item -ItemType Directory -Force $output | Out-Null
Push-Location $output
try {
  $generated = Join-Path $output 'actual_input_hooks.cpp'
  & python "$repoRoot/scripts/generate_input_hooks_test.py" --source $source --output $generated
  if ($LASTEXITCODE -ne 0) { throw 'Input hook source generation failed' }
  & cl.exe /nologo /std:c++17 /EHsc /O2 /W4 /WX $generated /Fe:input-hooks-test.exe
  if ($LASTEXITCODE -ne 0) { throw 'Input hook regression compilation failed' }
  & .\input-hooks-test.exe
  if ($LASTEXITCODE -ne 0) { throw 'Input hook/log classification regression failed' }
} finally { Pop-Location }
